### ISSUE TITLE
Adding Tag to GKE cluster does not work with Pulumi

### ISSUE THREAD

**Issue by Pithikos** [pulumi/pulumi-gcp#1015]
### What happened?

I'm trying to add a tag to a GKE cluster programmatically but it seems impossible.

Works fine with gcloud:
```
gcloud resource-manager tags bindings create --location=europe-south2-a --parent //container.googleapis.com/projects/myproject-1234/locations/europe-south2-a/clusters/mycluster-4567 --tag-value=tagValues/5555
```

Refs:
- GCP cluster parent https://cloud.google.com/iam/docs/full-resource-names
- GCP tag docs https://cloud.google.com/kubernetes-engine/docs/how-to/tags``

### Expected Behavior

I expect that following [Pulumi's Python examples](https://www.pulumi.com/registry/packages/gcp/api-docs/tags/tagbinding/
) I would be able to replicate the gcloud command but I can't.

### Steps to reproduce

```python
from pulumi_gcp import tags

tags.TagBinding(
    "binding",
    parent="//container.googleapis.com/projects/myproject-1234/locations/europe-south2-a/clusters/mycluster-4567",
    tag_value="tagValues/5555",
    # location=europe-south2-a,  # this doesn't work either
)
```

Output
```
Diagnostics:
  pulumi:pulumi:Stack (myproject-1234):
    error: update failed

  gcp:tags:TagBinding (binding):
    error: 1 error occurred:
    	* Error creating TagBinding: googleapi: Error 400: field [binding.resource] has issue [Must be a valid One Platform resource name of a tag-compatible global resource. Did you forget to specify the correct location?]
    Details:
    [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "description": "Must be a valid One Platform resource name of a tag-compatible global resource. Did you forget to specify the correct location?",
            "field": "binding.resource"
          }
        ]
      }
    ]
```

Based on that, it seems that Pulumi doesn't know where to put location.

### Output of `pulumi about`

```
CLI          
Version      3.55.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME        VERSION
command     0.7.1
gcp         6.50.0
kubernetes  3.24.1
python      unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
Hi @Pithikos and thanks for reporting this.

It looks like this is a known [upstream issue in the terraform GCP provider](https://github.com/hashicorp/terraform-provider-google/issues/11448). From that issue, it appears that trying to tag a resource that requires a location (eg. Compute Instance or GKE) had been broken. A recent fix about a month ago works for regional locations, but zonal locations are still broken. In your example, `europe-south2-a` is a zonal location, and therefore attempting to create a tag for this with our Pulumi provider would currently still fail. If your cluster is regional (eg. `europe-south2`) then Pulumi should be able to carry out this flow.

It does appear that a fix for zonal locations has been merged upstream last week. We're currently in the process of releasing a new version of our Pulumi GCP provider, so this should hopefully be resolved with our release that will happen this week.

**Comment by AaronFriel** [comment]
Looks like this is fixed upstream and in our latest release.
