### ISSUE TITLE
GCP Security Policy Creation Failure with expr expression

### ISSUE THREAD

**Issue by dnyanesh-markad** [pulumi/pulumi-gcp#1029]
### What happened?

I am trying to create a security policy in GCP through pulumi with typescript code. I am using below block for policy creation

```typescript
const SpArgs: SecurityPolicyArgs = {
    name: SpName,
    description: `SecurityPolicy for Web`,
    rules: [
      {
        action: SecurityPolicyActionType.DENY_403,
        priority: 2147483647,
        description: `Default rule, higher priority overrides it`,
        match: {
          expr: {
            expression: `request.path.matches('/dashboard/login') && !inIpRange(origin.ip, '125.103.175.102/32')`,
          },
        },
      },
createSecurityPolicy(SpName, SpArgs)

createSecurityPolicy(name: string, args: SecurityPolicyArgs): SecurityPolicy {
    return new SecurityPolicy(name, args)
  }
```

If I create with versiondExpr it works, it creates the poilicy but if I use expr it fails.

### Expected Behavior

The code should create policy using 

```typescript
match: {
          expr: {
            expression: `request.path.matches('/dashboard/login') && !inIpRange(origin.ip, '123.23.44.67/32')`,
          },
        },
```

in GCP

### Steps to reproduce

Try to create a security policy using

```typescript
match: {
  expr: {
     expression :  expression: `request.path.matches('/dashboard/login') && !inIpRange(origin.ip, '123.23.44.67/32')`,
     }
}
```

### Output of `pulumi about`

```
gcp:storage:Bucket dgraph-backup  
    gcp:compute:SecurityPolicy jupiter-security-policy  error: gcp:compute/securityPolicy:SecurityPolicy resource 'security-policy' has a problem: expected rule.0.match.0.versioned_expr to be one of [SRC_IPS_V1], got . Examine values at 'SecurityPolicy.Rules'.
    gcp:compute:SecurityPolicy security-policy  1 error
    pulumi:pulumi:Stack zeals-dev  2 messages

Diagnostics:
  gcp:compute:SecurityPolicy (security-policy):
    error: gcp:compute/securityPolicy:SecurityPolicy resource 'security-policy' has a problem: expected rule.0.match.0.versioned_expr to be one of [SRC_IPS_V1], got . Examine values at 'SecurityPolicy.Rules'.
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
@dnyanesh-markad Can you clarify what your config is when working. You mentioned setting `versiondExpr`. Can you provide your code sample for this as well so I can get a better understanding of what you're configuring. Thanks

**Comment by dnyanesh-markad** [comment]
@rquitales I have provided the code in the issue itself. We are not using versionedExpr. We are using expr: expression, please find reference below

const SpArgs: SecurityPolicyArgs = {
    name: SpName,
    description: `SecurityPolicy for Web`,
    rules: [
      {
        action: SecurityPolicyActionType.DENY_403,
        priority: 2147483647,
        description: `Default rule, higher priority overrides it`,
        match: {
          expr: {
            expression: `request.path.matches('/dashboard/login') && !inIpRange(origin.ip, '125.103.175.102/32')`,
          },
        },
      },
createSecurityPolicy(SpName, SpArgs)

createSecurityPolicy(name: string, args: SecurityPolicyArgs): SecurityPolicy {
    return new SecurityPolicy(name, args)
  }

**Comment by dnyanesh-markad** [comment]
@rquitales @justinvp  Did you get a time to look into this.
Main problem is the gcp provider does not create a policy using block

`match: {
          expr: {
            expression: ``,
          },
        },`

**Comment by rquitales** [comment]
@dnyanesh-markad Thanks for the clarification. I've tracked down the issue, and it's related to an upstream bug in https://github.com/pulumi/pulumi-terraform-bridge.

Thankfully, the latest version of this dependency (v3.39.2) solves this issue, so I will upgrade our dependencies to the latest version and cut a new release.

In the meantime as a workaround, you can downgrade your GCP provider to v6.48.0 which I've tested is working.
