### ISSUE TITLE
GCP API Gateway Gateway YAML example not been generated

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-gcp#1030]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

https://www.pulumi.com/registry/packages/gcp/api-docs/apigateway/gateway/#example-usage

Click on the YAML tab and you see this:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/109047/224284583-6feed29a-25b7-4146-9b28-d82e6837a2a9.png">

The examples in other languages are present.

**Comment by jazzyfresh** [comment]
Thank you for reporting this!

This seems like it could be a bug, as other resources for AWS have generated YAML resources. We've had a few docs generation bugs due to the bridge, so we will investigate and move the the [pulumi-terraform-bridge](https://github.com/pulumi/pulumi-terraform-bridge) repo if related.

**Comment by squaremo** [comment]
There's other docs generation issues in the vicinity: https://www.pulumi.com/registry/packages/gcp/api-docs/apigateway/apiiambinding/ just runs all the examples together, with no tabs for selecting the language (similarly https://www.pulumi.com/registry/packages/gcp/api-docs/apigateway/apiiammember/ and possibly others).

Not that I did an exhaustive search, but like Jasmine I don't see these problems elsewhere, so I'm inclined to keep it here for further investigation.

**Comment by mjeffryes** [comment]
This appears to be fixed in the latest version of these docs.
