### ISSUE TITLE
GCP CloudRun `value_from` is deprecated

### ISSUE THREAD

**Issue by snamber** [pulumi/pulumi-gcp#1039]
File: [themes/default/content/docs/reference/pkg/gcp/cloudrun/service.md](https://www.pulumi.com/docs/reference/pkg/gcp/cloudrun/service/)

The "Cloud Run Service Secret Environment Variables" example uses a configuration—the `value_from` field for environment variables— that is deprecated and does not allow to be applied through `pulumi up` anymore.

**Comment by mikhailshilkov** [comment]
That example doesn't exist anymore, also not in [upstream](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service). I'll assume it's for good reason and will mark this issue as fixed.
