### ISSUE TITLE
GCP Compute/Instance and Compute/InstanceTemplate resources do not explain how to use custom machine types.

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-gcp#1041]
### Problem description

- I saw a product documentation issue on the following URLs: 
https://www.pulumi.com/docs/reference/pkg/gcp/compute/instance/
https://www.pulumi.com/docs/reference/pkg/gcp/compute/instancetemplate/

GCP supports custom machine types (i.e. instead of using a predefined type like e2-standard-2 one can specify the number of CPUs and the amount of RAM.
In the GCP compute Instance and InstanceTemplate resources this is done by setting the machine type property as 
`custom-X-Y` where “X” and “Y” specify the CPUs and RAM (in MBs), respectively.

Our documentation does not explain this for the machine type property.
The source Terraform documentation (https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs) includes this information in the machine_type description but our documentation generation tooling appears to be ignoring it.

There are some nonobvious/buried links about this at the bottom of our doc pages listed above, but nobody would think to look at the bottom for this information and so is not useful.

**Comment by mikhailshilkov** [comment]
I can see this explanation in our docs now:

<img width="685" alt="image" src="https://github.com/pulumi/pulumi-gcp/assets/1454008/c0201c6d-cfd1-4d8b-b28e-24991d74bfce">
