### ISSUE TITLE
gcp.Provider.isInstance always returns false

### ISSUE THREAD

**Issue by mleclercq** [pulumi/pulumi-gcp#1045]
### What happened?

At least in nodeJs (didn't tested others) the `gcp.Provider.isInstance` function seem to always return false even when provided a proper `gcp.Provider` instance.

### Expected Behavior

`gcp.Provider.isInstance` function should return true when provided an instance of `gcp.Provider`.

### Steps to reproduce

With the following pulumi program:

```typescript
import * as gcp from '@pulumi/gcp';

const gcpProvider= new gcp.Provider("default");
console.log('isInstance', gcp.Provider.isInstance(gcpProvider))
```

A `pulumi preview` shows `inInstance false` while it should show `isInstance true`

### Output of `pulumi about`

CLI          
Version      3.55.0
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME        VERSION
aws         4.5.1
gcp         6.50.0
kubernetes  3.21.4
nodejs      unknown
postgresql  3.0.1
random      4.1.1
tls         4.10.0

Host     
OS       darwin
Version  12.1
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v14.19.3'

Current Stack: ####

Found no resources associated with test

Found no pending operations associated with test

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/mleclercq
User           mleclercq
Organizations  mleclercq, automat-ai

Dependencies:
NAME                              VERSION
@types/node                       12.20.46
@typescript-eslint/parser         2.6.1
eslint-plugin-prettier            3.1.1
eslint                            6.6.0
prettier                          1.19.1
typescript                        3.9.10
@types/js-base64                  2.3.2
@typescript-eslint/eslint-plugin  2.3.1
eslint-config-prettier            6.5.0
js-base64                         2.6.4
nano                              8.2.2

### Additional context

Looking at how `gcp.Provider.isInstance` is implemented:

https://github.com/pulumi/pulumi-gcp/blob/e970ef2fc800c841a8518a0d8398999eeaf02a1a/sdk/nodejs/provider.ts#L23-L28

It looks for the `__pulumiType` property on the given object and check if it is equals to `"gcp"` but it looks like this property has value `"pulumi:providers:gcp"' according to:

```typescript
console.log('__pulumiType', (gcpProvider as any)['__pulumiType'])
```

So looks like the following line should be changed:

https://github.com/pulumi/pulumi-gcp/blob/e970ef2fc800c841a8518a0d8398999eeaf02a1a/sdk/nodejs/provider.ts#L17

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
I verified that this is fixed by https://github.com/pulumi/pulumi/issues/12584 with the latest version of the provider
