### ISSUE TITLE
Service account regex matching failing

### ISSUE THREAD

**Issue by salotz** [pulumi/pulumi-gcp#1058]
### What happened?

I am setting up Workload Identity for my GKE cluster and am trying to bind a K8s SA to a GCP SA. I manually created a service account: `external-secrets@ibeks-sandbox.iam.gserviceaccount.com`

When I try to use the `gcp.serviceaccount.IAMBinding` resource I specify the `service_account_id` correctly but it still gives me this error (along with a log message printing the expanded `ES_GSA_ID` see below):

```
Diagnostics:
  pulumi:pulumi:Stack (services-sandbox):
    external-secrets@ibeks-sandbox.iam.gserviceaccount.com

  gcp:serviceAccount:IAMBinding (external-secrets-sa-iam-binding):
    error: gcp:serviceAccount/iAMBinding:IAMBinding resource 'external-secrets-sa-iam-binding' has a problem: "service_account_id" ("external-secrets@ibeks-sandbox.iam.gserviceaccount.com") doesn't match regexp "projects/(?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?)|-)/serviceAccounts/((?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?))@[a-z]+.gserviceaccount.com$|[0-9]{1,20}-compute@developer.gserviceaccount.com|[a-z](?:[-a-z0-9]{4,28}[a-z0-9])@[-a-z0-9\\.]{1,63}\\.iam\\.gserviceaccount\\.com$)". Examine values at 'IAMBinding.ServiceAccountId'.
```

You can even see that the string it has for the service account in the error message is correct so I think its a mistake in the regex.

### Expected Behavior

I expected that the service account ID would be valid, since this is what the GCP console is giving me.

### Steps to reproduce

You would need to set up a GCP project with a service account. 

Then here is the full script, although most is not relevant to the problem (I think):

```
import pulumi
import pulumi_gcp as gcp
from pulumi_kubernetes.helm.v3 import Release, ReleaseArgs, RepositoryOptsArgs
from pulumi_kubernetes.core.v1 import ServiceAccount
from pulumi_kubernetes.meta.v1.outputs import ObjectMeta
from pulumi_kubernetes.apiextensions import CustomResource

gcp_config = pulumi.Config("gcp")
gcp_project = gcp_config.require("project")

ES_NAMESPACE = "external-secrets"
ES_KSA_NAME = "external-secrets"
ES_GSA_NAME = "external-secrets"
ES_GSA_ID = f"{ES_GSA_NAME}@{gcp_project}.iam.gserviceaccount.com"

external_secrets = Release(
    "external-secrets-controller",
    chart="external-secrets",
    version="0.8.1",
    namespace=ES_NAMESPACE,
    repository_opts=RepositoryOptsArgs(
        repo="https://charts.external-secrets.io/",
    ),
    create_namespace=True,
    skip_crds=False,
    values={
        "installCRDs": "true",
    },
)


gcpsm_k8s_sa = ServiceAccount(
    "gcpsm_k8s_sa",
    metadata=ObjectMeta(
        name="external-secrets",
        namespace=ES_NAMESPACE,
        annotations={
            # this is a manually created service account
            "iam.gke.io/gcp-service-account": ES_GSA_ID,
        },
    ),
    opts=pulumi.ResourceOptions(depends_on=[external_secrets]),
)

# Then bind this K8s-SA to the GCP-SA
sa_binding = gcp.serviceaccount.IAMBinding(
    "external-secrets-sa-iam-binding",
    service_account_id=ES_GSA_ID,
    role="roles/iam.workloadIdentityUser",
    members=[
        f"serviceAccount:ibeks-sandbox.svc.id.goog[{ES_NAMESPACE}/{ES_KSA_NAME}]",
    ],
    opts=pulumi.ResourceOptions(depends_on=[external_secrets, gcpsm_k8s_sa]),
)

```

### Output of `pulumi about`

{Mon Apr 10 23:22:04}  0:
--> pulumi about -s sandbox
CLI          
Version      3.60.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME        VERSION
gcp         6.52.0
kubernetes  3.24.2
python      unknown

Host     
OS       opensuse-tumbleweed
Version  
Arch     x86_64

This project is written in python: executable='/home/salotz/tree/ibeks/devel/ops/.venv/bin/python3' version='3.11.1
'

Current Stack: ibeks-technology/services/sandbox

TYPE                               URN
pulumi:pulumi:Stack                urn:pulumi:sandbox::services::pulumi:pulumi:Stack::services-sandbox
pulumi:providers:kubernetes        urn:pulumi:sandbox::services::pulumi:providers:kubernetes::default_3_24_2
kubernetes:core/v1:ServiceAccount  urn:pulumi:sandbox::services::kubernetes:core/v1:ServiceAccount::gcpsm_k8s_sa
kubernetes:helm.sh/v3:Release      urn:pulumi:sandbox::services::kubernetes:helm.sh/v3:Release::external-secrets-controller

Found no pending operations associated with sandbox

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/sam-ibeks
User           sam-ibeks
Organizations  sam-ibeks, ibeks-technology

Dependencies:
NAME               VERSION
ipython            8.12.0
Jinja2             3.1.2
pdbpp              0.10.3
pip                23.0.1
pulumi-gcp         6.52.0
pulumi-kubernetes  3.24.2
setuptools         67.6.1
wheel              0.38.4

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Hello @salotz thank you for the detailed write-up.

Looking at [the REST example for creating a service account](https://cloud.google.com/iam/docs/service-accounts-create#iam-service-accounts-create-rest), it looks like the `name` property in the response matches what the regex is looking for: 

```json
{
  "name": "projects/my-project/serviceAccounts/my-service-account@my-project.iam.gserviceaccount.com",
  "projectId": "my-project",
  "uniqueId": "123456789012345678901",
  "email": "my-service-account@my-project.iam.gserviceaccount.com",
  "displayName": "My service account",
  "etag": "BwUp3rVlzes=",
  "description": "A service account for running jobs in my project",
  "oauth2ClientId": "987654321098765432109"
}
```

From what I remember GCP normally expects all identifiers to be the fully qualified path but in this Pulumi provider we attempt to pre-fill the project context to make things easier, but it looks like this property doesn't do that.

Give it a try with the following and let us know how that works:

```python
ES_GSA_ID = f"projects/{gcp_project}/servicesAccounts/{ES_GSA_NAME}@{gcp_project}.iam.gserviceaccount.com"
```

**Comment by salotz** [comment]
That seems to work, thank you. I suspected it was something like this but I couldn't find the difference between a "fully-qualified" SA ID and the name/id (?).

I guess if I was better at reading regex I could have figured that out.

Only thing was that I had to change `servicesAccounts` to `serviceAccounts` in your suggestion.
