### ISSUE TITLE
Document how to create `google_beta` provider

### ISSUE THREAD

**Issue by tomdottom** [pulumi/pulumi-gcp#1059]
File: [themes/default/content/docs/reference/pkg/gcp/artifactregistry/repository.md](https://www.pulumi.com/docs/reference/pkg/gcp/artifactregistry/repository/)

The examples all reference `provider=google_beta` but it's unclear where this comes from.
Please add an example of how to create it.

```python
import pulumi
import pulumi_gcp as gcp

my_repo = gcp.artifactregistry.Repository("my-repo",
    location="us-central1",
    repository_id="my-repository",
    description="example docker repository",
    format="DOCKER",
    opts=pulumi.ResourceOptions(provider=google_beta))
```

**Comment by mjeffryes** [comment]
Examples have been fixed to avoid this unneeded explicit provider
