### ISSUE TITLE
Add support for GCP Cloud Domains

### ISSUE THREAD

**Issue by aryehb** [pulumi/pulumi-gcp#1061]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The [GCP Native plugin has support for Domains](https://www.pulumi.com/registry/packages/google-native/api-docs/domains/v1/), but the GCP Classic plugin does not.

https://cloud.google.com/domains/docs/reference/rest/v1/projects.locations.registrations

**Comment by besserwisser** [comment]
@mikhailshilkov thank you :) Didn't see it. Looking forward to stable "gcp native". Do you have any idea when we could use it in production?

**Comment by mikhailshilkov** [comment]
The upstream issue has been implemented: https://github.com/hashicorp/terraform-provider-google/issues/7696

Closing this as done.
