### ISSUE TITLE
Description of accountId is an incomplete sentence in gcp.serviceaccount.getAccount 

### ISSUE THREAD

**Issue by dantheman39** [pulumi/pulumi-gcp#1073]
File: [themes/default/content/registry/packages/gcp/api-docs/serviceAccount/getaccount/_index.md](https://www.pulumi.com/registry/packages/gcp/api-docs/serviceaccount/getaccount/)

There's an incomplete sentence, missing key information. I'd like to see a complete description of what accountId could be, but it simply says "This be one of:", then ends. See the screenshot.

<img width="776" alt="Screenshot 2023-04-29 at 11 32 18 AM" src="https://user-images.githubusercontent.com/10103957/235310804-5589156c-3345-42a5-81dc-70131c2a4a32.png">

**Comment by rquitales** [comment]
@dantheman39 Thanks for reporting this issue with documentation. It looks like we didn't not accurately generate documentation from: https://github.com/hashicorp/terraform-provider-google-beta/blob/355737a9303a7848e891676e304eb76605daaf2e/website/docs/d/service_account.html.markdown?plain=1#L44-L52

For now, here are the valid `accountid` values:
* The name of the service account within the project (e.g. `my-service`)
* The fully-qualified path to a service account resource (e.g.
      `projects/my-project/serviceAccounts/...`)
* The email address of the service account (e.g.
      `my-service@my-project.iam.gserviceaccount.com`)

It looks like doc generation is not accurate when the text is multiline. We'll need to update our doc generation to account for multiline descriptions as next steps!

**Comment by mnlumi** [comment]
This is resolved and the accountId values are displayed properly.
