### ISSUE TITLE
Add support for provisionedIops and provisionedThroughput

### ISSUE THREAD

**Issue by isaac-pulumi** [pulumi/pulumi-gcp#1099]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We have a customer request to support two new capabilities for storage accounts: 
- provisoinedIops - please refer here [pr_link](https://github.com/GoogleCloudPlatform/magic-modules/pull/8066)

You will want to refer to this documentation, it's not documented as a parameter and hard to find: [doc_link](https://cloud.google.com/compute/docs/disks/modify-hyperdisks#api)

 POST https://compute.googleapis.com/compute/v1/projects/PROJECT_ID/zones/ZONE/disks/DISK_NAME/update { "provisionedIops": "IOPS_LIMIT" }   

https://compute.googleapis.com/compute/v1/projects/<project_name>/zones/<zone>/disks/<disk_name>?alt=json&paths=provisionedIops

You will need to pass both the name of the disk and the provisionedIops in the patch request.

- provisionedThroughput - please see this PR: 
[pr_link](https://github.com/GoogleCloudPlatform/magic-modules/pull/8153) on line 447 in mmv1/products/compute/Disk.yaml

The process is similar to provisionedIops

**Comment by danielrbradley** [comment]
Removing triage label as it looks like you've already assigned people directly on this @isaac-pulumi

**Comment by mnlumi** [comment]
[Provisioned_iops](https://www.pulumi.com/registry/packages/gcp/api-docs/compute/disk/#provisionediops_go) and [provisioned_throughput](https://www.pulumi.com/registry/packages/gcp/api-docs/compute/disk/#provisionedthroughput_go) are available as of https://github.com/pulumi/pulumi-gcp/commit/dfacd8a41f257a7011712346177aea9721e8e882.
