### ISSUE TITLE
Artifact Registry Output 'Name' Does Not Include Full Registry Path

### ISSUE THREAD

**Issue by cainenielsen** [pulumi/pulumi-gcp#1105]
Under `name` output is documented with the following note.
> The name of the repository, for example: "projects/p1/locations/us-central1/repositories/repo1"

However, this simply results in "repo1", not including the full path.

I found that the `id` output result _does_ include the full registry path, however, it does not feature the above example in the documentation. It simply includes:

> The provider-assigned unique ID for this managed resource.

Can the documentation be updated to reflect the actual expected output values?

File: [themes/default/content/registry/packages/gcp/api-docs/artifactregistry/repository/_index.md](https://www.pulumi.com/registry/packages/gcp/api-docs/artifactregistry/repository/)

**Comment by guineveresaenger** [comment]
It appears that this was fixed:
<img width="683" alt="Screen Shot 2023-06-21 at 10 47 08 AM" src="https://github.com/pulumi/pulumi-gcp/assets/13116240/381c8ba9-cf0f-4764-8e1e-5f07c94f1450">
