### ISSUE TITLE
Cannot update Project folder_id

### ISSUE THREAD

**Issue by geekflyer** [pulumi/pulumi-gcp#112]
Somehow pulumi fails while attempting to move a project into a folder.
Versions:
pulumi CLI: v0.17.1
pulumi-gcp: 0.17.1
Runtime: nodejs

Error message:
```
   * updating urn:pulumi:gcp-project-redacted::gcp-project-redacted::gcp:organizations/project:Project::redacted: 'org_id' and 'folder_id' cannot be both set.
```

Reproduction:

1. Step 1:  Pulumi up the following program which creates a project directly underneath an org:
```ts
import * as gcp from '@pulumi/gcp';

const GCP_ORG_ID = 'foo';
const GCP_BILLING_ACCOUNT_ID = 'bar';

new gcp.organizations.Project(
  'some-project-123',
  {
    name: 'some-project-123',
    projectId: 'some-project-123',
    billingAccount: GCP_BILLING_ACCOUNT_ID,
    orgId: GCP_ORG_ID
  }
);
```

2. Step 2: Create a GCP Folder resource and attempt to move the project underneath that folder:
```ts
import * as gcp from '@pulumi/gcp';

const GCP_ORG_ID = 'foo';
const GCP_BILLING_ACCOUNT_ID = 'bar';

// this new folder is supposed to contain all prod relevant subprojects underneath.
export const prodFolder = new gcp.organizations.Folder('prod-folder', {
  displayName: 'prod',
  parent: `organizations/${GCP_ORG_ID}`
});

new gcp.organizations.Project(
  'some-project-123',
  {
    name: 'some-project-123',
    projectId: 'some-project-123',
    billingAccount: GCP_BILLING_ACCOUNT_ID,
    folderId: prodFolder.id
  }
);
```

The error mentioned above will occur. I couldn't really find a good workaround. Even when I move the project underneath the folder manually via the UI pulumi continues to show that error.

**Comment by lukehoban** [comment]
@swgillespie @jen20 This sounds like it could be a core engine issue around applying old `inputs` that are no longer part of the new `inputs`?  https://github.com/pulumi/pulumi-terraform/pull/305 was a recent fix somewhat related to this - though in that case it was related to there being a default.

**Comment by geekflyer** [comment]
fyi what's the status on this? I just tried this with pulumi CLI v0.17.22 and
```
    "@pulumi/gcp": "0.18.12",
    "@pulumi/pulumi": "0.17.22",
```
but the issue persists.

**Comment by mikhailshilkov** [comment]
I believe this has been fixed upstream in https://github.com/hashicorp/terraform-provider-google/issues/7197

I gave it a quick test locally and it seems to work fine now.
