### ISSUE TITLE
Errors in the schema for `gcp:organizations/getProject:getProject`

### ISSUE THREAD

**Issue by jplewa** [pulumi/pulumi-gcp#1125]
### What happened?

The schema for `gcp:organizations/getProject:getProject` defines two outputs (`autoCreateNetwork` and `skipDelete`) as required, but when I run the function generated in Java, I end up getting nulls in both fields.

<img width="223" alt="image" src="https://github.com/pulumi/pulumi-gcp/assets/34098778/8a79d17f-b93e-4ef2-b3e7-d7c9bb6b29a9">

![image](https://github.com/pulumi/pulumi-gcp/assets/34098778/cee803ab-99aa-41ab-9ee6-6ec0b46f7955)

### Expected Behavior

The fields should be marked as optional in the schema, as they are [in Terraform](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project.html#skip_delete).

### Steps to reproduce

```kotlin
import com.pulumi.Pulumi
import com.pulumi.gcp.organizations.OrganizationsFunctions

fun main() {
    Pulumi.run { ctx ->
        val project = OrganizationsFunctions.getProject()

        ctx.export("name", project.applyValue { it.name() })
        ctx.export("autoCreateNetwork", project.applyValue { it.autoCreateNetwork() })
        ctx.export("skipDelete", project.applyValue { it.skipDelete() })

        ctx.export("nameIsNull", project.applyValue { it.name() }.applyValue { it == null })
        ctx.export("autoCreateNetworkIsNull", project.applyValue { it.autoCreateNetwork() }.applyValue { it == null })
        ctx.export("skipDeleteIsNull", project.applyValue { it.skipDelete() }.applyValue { it == null })
    }
}
```

### Output of `pulumi about`

```
CLI          
Version      3.74.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME  VERSION
gcp   6.59.0
java  unknown

Host     
OS       darwin
Version  13.4.1
Arch     arm64

This project is written in java: executable='/usr/bin/java' version='openjdk 20.0.1 2023-04-18
OpenJDK Runtime Environment (build 20.0.1+9-29)
OpenJDK 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)' java='/usr/bin/java' javac='20.0.1' maven='Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f)' gradle='8.2'

Current Stack: jplewa/gcp-sample-project/test

TYPE                  URN
pulumi:providers:gcp  urn:pulumi:test::gcp-sample-project::pulumi:providers:gcp::default_6_59_0
pulumi:pulumi:Stack   urn:pulumi:test::gcp-sample-project::pulumi:pulumi:Stack::gcp-sample-project-test


Found no pending operations associated with test

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/jplewa
User           jplewa
Organizations  jplewa, jvm-lab

No dependencies found

Pulumi locates its logs in /var/folders/7t/4c40hycs62g6ms5l8qql3nhr0000gn/T/ by default
```

### Additional context

I stumbled upon this issue in my work on [Pulumi Kotlin](https://github.com/VirtuslabRnD/pulumi-kotlin), which is a Kotlin wrapper on top of the Java library. Because of this error in the schema, the Kotlin code ends up throwing a NPE while processing the response.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Thank you for the detailed report, @jplewa! First thing we'll try is whether upgrading some of the provider's dependencies helps since there have been a number of fixes in this area.

**Comment by mjeffryes** [comment]
It looks like these fields are now optional: [gcp.organizations.getProject | Pulumi Registry](https://www.pulumi.com/registry/packages/gcp/api-docs/organizations/getproject/)
