### ISSUE TITLE
Cloudrunv2 get url not addressed in docs

### ISSUE THREAD

**Issue by yehudamakarov** [pulumi/pulumi-gcp#1135]
- in the examples for GCP cloud run v1, there is a pub-sub example showing how to use the URL of your service (presumably, other infrastructure will call it)
- In v2, that example is gone, and there is a new set of reconciliation fields, a possible mention of polling, and I can't tell from the docs where the URL should come from. 

Would you be able to help me here?

Should I use v1 because the notion of accessing the service's URL is forever gone? What shall I do?

(was redirected from https://github.com/pulumi/pulumi/issues/13574)

**Comment by mnlumi** [comment]
Hey @yehudamakarov Could you link me to the specific resource api doc you are looking at?

**Comment by yehudamakarov** [comment]
https://www.pulumi.com/registry/packages/gcp/api-docs/cloudrun/service/#cloud-run-service-pubsub here you can get the service url

https://www.pulumi.com/registry/packages/gcp/api-docs/cloudrunv2/service/
Here there’s no example like above and hence no clue how to get the url

Thanks,
Yehuda Makarov

**Comment by rquitales** [comment]
Hi @yehudamakarov apologies that you're facing difficulties with getting the URL of a CloudRun service. It is recommended to use the newer v2 CloudRun API provided by GCP, though v1 is still supported by GCP.

To get the service URL, you should be able to use the `uri` field: https://www.pulumi.com/registry/packages/gcp/api-docs/cloudrunv2/service/#uri_nodejs.

Below is an example of how to achieve this using Javascript:
```
const svc = new gcp.cloudrunv2.Service("default", {
    ingress: "INGRESS_TRAFFIC_ALL",
    location: "us-central1",
    template: {
        containers: [{
            image: "us-docker.pkg.dev/cloudrun/container/hello",
        }],
    },
});

exports.svcURL = svc.uri;
```
