### ISSUE TITLE
adding, deleting or modifying Taints on a nodepool forces replacement

### ISSUE THREAD

**Issue by amaldonadomat** [pulumi/pulumi-gcp#1139]
### What happened?

I'm trying to implement by code the addition of Taints to the node pools in GKE. When I add, modify or delete any Taint pulumi prompts for replacement of the entire node pool when it shouldn't. 
![image](https://github.com/pulumi/pulumi-gcp/assets/104778429/0e017b29-0494-4f6e-ad06-5c47229c90cc)

It's possible to do it manually using kubectl or directly on GKE UI and it won't replace the nodepool, just update it. 

I'm using `github.com/pulumi/pulumi-gcp/sdk/v6 v6.61.0`

### Expected Behavior

Just update the node pool not replace it

### Steps to reproduce

Add any taint to a node pool using the property https://www.pulumi.com/registry/packages/gcp/api-docs/container/nodepool/#taints_go. 

It actually says in the documentation that it forces replacement, but it shouldn't

### Output of `pulumi about`

CLI          
Version      3.76.1
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME        VERSION
gcp         6.61.0
go          unknown
kubernetes  3.22.1

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.18.2 linux/amd64'

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @amaldonadomat - thank you for filing this issue.

Can you help us out by sending us a minimum viable program we can run to duplicate this on our end? 🙏

**Comment by danielrbradley** [comment]
This appears to be by design - given that the documentation for the taints property indicates that an update will cause a replacement. Do you have a source reference as to why you you don't think it should cause replacement?

**Comment by amaldonadomat** [comment]
Hello @danielrbradley 
Thanks for looking into this. I've found a related issue in terraform. I guess if terraform is the underlying provider, the issue is propagated. We will apply them manually
