### ISSUE TITLE
Assigning static internal ip to instances

### ISSUE THREAD

**Issue by apichick** [pulumi/pulumi-gcp#114]
Hi,

I am setting up a cassandra cluster in GCP using pulumi. I would like to assign a static internal ip to each of the cassandra nodes, so this is my script:

```
const services = new gcp.projects.Services("services", {   
//    project: 'apigee-csa-meetup-kong',
    services: ["compute.googleapis.com"],
});

const network = new gcp.compute.Network("kong-vpc", {
//    project: 'apigee-csa-meetup-kong',
    autoCreateSubnetworks: false
}, {
    dependsOn: [ services ]
});

const dataSubnetwork = new gcp.compute.Subnetwork("kong-data-subnet", {
    ipCidrRange: "10.2.1.0/24",
    network: network.selfLink
});

const cassandraNodeTemplate = new gcp.compute.InstanceTemplate("cassandra-node-template", {
    canIpForward: false,
    description: "This template is used for Cassandra nodes",
    disks: [
        {
            autoDelete: true,
            boot: true,
            sourceImage: "centos-cloud/centos-7",
            diskSizeGb: 100
        }
    ],
    instanceDescription: "Cassandra node",
    machineType: "n1-standard-4",
    networkInterfaces: [{
        subnetwork: dataSubnetwork.selfLink
    }],
    schedulings: [{
        automaticRestart: true,
        onHostMaintenance: "MIGRATE",
    }],
    tags: [
        "cassandra"
    ],
});

const cassandraNodeIps = [];
const cassandraNodes = [];

for (let i = 0; i < 3; i++) {
    cassandraNodeIps.push(new gcp.compute.Address(`cassandra-node-${i}-ip`, {
        address: "10.2.1." + (2 + i),
        addressType: "INTERNAL",
        subnetwork: dataSubnetwork.selfLink,
    }));
}

for (let i = 0; i < 3; i++) {
    cassandraNodes.push(new gcp.compute.InstanceFromTemplate(`cassandra-node-${i}`, {
        sourceInstanceTemplate: cassandraNodeTemplate.selfLink,
        zone: "europe-west3-a",
        networkInterfaces: [
            {
                subnetwork: dataSubnetwork.selfLink,
                network_ip: cassandraNodeIps[i].selfLink
            }
        ],
        tags: [ "cassandra" ]
    });
}
```

If I run ```pulumi up``` and then I make a change to my script, for instance to add metadataStartupScript and rerun the ```pulumi up``` command, I am alway running into an error when it is replacing the instances saying  ```error: Plan apply failed: IP '10.2.1.2' is already being used by another resource```
 
Am I doing something wrong? How can I get around this?

**Comment by lukehoban** [comment]
>  I am alway running into an error when it is replacing the instances saying error: Plan apply failed: IP '10.2.1.2' is already being used by another resource

By default, Pulumi will try to create the new instance before deleting the old instance to ensure there is not downtime.  It sounds like in this case, you want to share a single static IP across the instances, which means this is not possible - you'll have to delete the previous instance before creating the new one (and will experience some downtime as a result).  You can opt-in to this by passing `deleteBeforeReplace: true` to the resource options of the resource you are defining.  See also [`deleteBeforeReplace`](https://pulumi.io/reference/programming-model.html#deletebeforereplace) in the docs.
