### ISSUE TITLE
resource names should not use camelCase as it causes errors, a kebab-case would be a solution for this

### ISSUE THREAD

**Issue by Jaafar-Nasrallah** [pulumi/pulumi-gcp#1148]
File: [themes/default/content/registry/packages/gcp/api-docs/compute/targethttpproxy/_index.md](https://www.pulumi.com/registry/packages/gcp/api-docs/compute/targethttpproxy/)

in the examples. resources where created with strings such as `defaultTargetHttpProxy` and `defaultURLMap` and these names produce an error
a solution would be to use `default-target-http-proxy` and `default-url-map` instead

**Comment by lukehoban** [comment]
This is an issue with the default autonaming being applied to this resource.  You can workaround this by passing `name: ` explicitly.  But we should also fix this by adding an override similar to https://github.com/pulumi/pulumi-gcp/blob/41c8c3bc39a2cdfc927808d1074a3cf7750bedaf/provider/resources.go#L771 for this resource.
