### ISSUE TITLE
Remove "unable to detect a global setting for GCP Project" warning.

### ISSUE THREAD

**Issue by shadiramadan** [pulumi/pulumi-gcp#1168]
https://github.com/pulumi/pulumi-gcp/blob/f0115d920cb100c5fc4f39abfb54d90bf6146b61/provider/resources.go#L318

I have pulumi configuration which creates GCP projects (thus no global project ID is set) and I've found this warning very annoying in my outputs.

Could we remove or supress this specific warning?

**Comment by iwahbe** [comment]
Hi @shadiramadan. Thanks for telling us about the issue. I agree that the warning should be addressable.

**Comment by SpainTrain** [comment]
Curious whether there is any progress on this?  

Configurable warnings (generally, and specific to this) are very helpful for better DX.  In our case developers think they are doing something wrong when they interact with our stacks because we do not use the default project feature.  Thanks!

**Comment by VenelinMartinov** [comment]
blocked on https://github.com/pulumi/pulumi-terraform-bridge/issues/2702

**Comment by carlpaten** [comment]
This isn't working for me on 8.16. I've run `pulumi config set gcp:disableGlobalProjectWarning true` and it has updated my stack file (Pulumi.main.yaml):

```yaml
config:
  gcp:disableGlobalProjectWarning: "true"
```

However when running pulumi preview I still see the warning:

```
% pulumi preview                                        
Previewing update (main):
     Type                     Name               Plan     Info
     pulumi:pulumi:Stack      pulumi-infra-main           
     └─ pulumi:providers:gcp  default_8_16_0              1 warning

Diagnostics:
  pulumi:providers:gcp (default_8_16_0):
    warning: unable to detect a global setting for GCP Project.
    Pulumi will rely on per-resource settings for this operation.
    Set the GCP Project by using:
        `pulumi config set gcp:project <project>`
    If you would like to disable this warning use:
        `pulumi config set gcp:disableGlobalProjectWarning true`

Resources:
    8 unchanged
```

**Comment by iwahbe** [comment]
Hi @carlpaten. I have replicated the issue locally. I'm not sure why setting `pulumi config set gcp:disableGlobalProjectWarning true` doesn't work. Setting `PULUMI_GCP_DISABLE_GLOBAL_PROJECT_WARNING=true` does work, so that should be an immediate work-around. I'll look into why the config var doesn't work, since it should.
