### ISSUE TITLE
Audit the set of patches we maintain against upstream

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-gcp#1179]
In preparation for the upcoming major version bump from upstream, we should audit our patches to make sure they are surgical, explainable and under test. Patch code is code that we wrote, so it must be code that we understand and test.

Patches:
- 0001-Allow-disabling-the-partner-name.patch
- 0002-Add-nil-checks-for-sql-database-instance-flattening.patch
- 0003-Only-set-bigquery-dataset-selflink-if-available.patch
- 0004-Add-flattening-of-self-managed-certificates.patch
- 0005-Remove-security-policy-default-versioned_expr.patch
- 0006-website-docs-d-tweaks.patch
- 0007-Significant-docs-changes.patch
- 0008-Exclude-scripts-dir-from-provider-go-module.patch
- 0009-Remove-duplicative-resource-token.patch: https://github.com/pulumi/pulumi-gcp/pull/1180

**Comment by iwahbe** [comment]
- 0001-Allow-disabling-the-partner-name.patch
Augments the partner name. The change is straight forward and well scoped. It is not tested.
- 0002-Add-nil-checks-for-sql-database-instance-flattening.patch
This is harmless, but should not be necessary. If this is necessary, we have a bridge bug. It is not tested.
- 0003-Only-set-bigquery-dataset-selflink-if-available.patch
[CHANGELOG_OLD.md](https://github.com/pulumi/pulumi-gcp/blob/6a64ebe5b6c70e184843f2c014ed7fa727d1d829/CHANGELOG_OLD.md#L80) indicates this fixed a panic. There is no test.
- 0004-Add-flattening-of-self-managed-certificates.patch
Looks like this is a fix for https://github.com/hashicorp/terraform-provider-google/issues/12091. It is not tested.
- 0005-Remove-security-policy-default-versioned_expr.patch
This removes `Default: ""` from a field. Presumably this is because it is not compatible with the field validator: `ValidateFunc: validation.StringInSlice([]string{"SRC_IPS_V1"}, false)`. We should confirm that this is still an issue and open a tracking issue in the bridge.
- 0006-website-docs-d-tweaks.patch
Docs changes. Mostly removing links to the tf registry.
- 0007-Significant-docs-changes.patch
Lots of docs changes, lots of removed links. We should consider programatically removing these links to cut down on our patch set.
- 0008-Exclude-scripts-dir-from-provider-go-module.patch
Exclude the scripts package by adding a go.mod file. Apparently there is a reference to a private module.
- 0009-Remove-duplicative-resource-token.patch
Removes some (presumably) duplicated resources from the sdkv2 provider. We should just back this change out, swapping `MuxShimWithDisjointgPF` with `MuxShimWithPF` if necessary.

**Comment by mikhailshilkov** [comment]
Thank you! Two questions/asks:
- Could you please open issues for each patch, the same we did for AWS?
- Out of this list - are there patches that we recommend removing/changing for 7.0? If so, let's have estimates and move those issues to an iteration (M94 if small, M95 if large)

**Comment by iwahbe** [comment]
All my recommended changes are small (< 1 day), but they will take time. I have added them to #1183. Since the team is fully booked for this iteration, what should we bump to take these on?

**Comment by iwahbe** [comment]
Since there is now a tracking issue for each patch, I'm closing this issue.
