### ISSUE TITLE
Only-set-bigquery-dataset-selflink-if-available.patch

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-gcp#1187]
[This patch](https://github.com/pulumi/pulumi-gcp/blob/6a64ebe/patches/0003-Only-set-bigquery-dataset-selflink-if-available.patch) makes an action conditional on a property being present.

Presumably, this is not necessary when the provider is run against terraform, indicating a bridge bug. I looked but could not find an upstream issue.

### Tests
None

### Recommendation
If upstream removes the `self_link` field, this will introduce the field back into the resource, potentially erroring out. We should confirm that this patch is still necessary, and make sure that `resource_bigquery_dataset` is under test before the next major release.

**Comment by guineveresaenger** [comment]
A little bit more context about this patch:

- It was [originally added as part of a fork fix to prevent a panic on the dataset _datasource_ in #626 (the SHA of the Pulumi fork will eventually unearth the changes).
- This patch was created as part of the patch set generated when we moved to patches for upstream fixes.
- It seems to have been dropped accidentally during an upgrade earlier this year, as outlined in #1016
- We have a potential repro in #61, which we may be able to use as a test.

Preliminary thought: Leave this patch; add a test for this datasource that makes sure to look for the `selfLink` field. If and when that tests fails, we will know upstream removed the field and we can re-evaluate.

**Comment by t0yv0** [comment]
I've taken a look at related PRs. This panic reproduces for me with one of the user supplied programs:

```
import * as pulumi from "@pulumi/pulumi";
import * as gcp from "@pulumi/gcp";

const dataset = gcp.bigquery.Dataset.get(
  'salesforce',
  'salesforce',
  {
    project: 'bc-prod-fusion',
  },
  {},
);

dataset.id.apply((id) => {
  console.log(`got dataset ${id}`);
});

```

```
pulumi preview
```

```
CLI          
Version      3.86.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME    VERSION
gcp     6.50.0
nodejs  unknown

Host     
OS       darwin
Version  14.0
Arch     x86_64

This project is written in nodejs: executable='/Users/t0yv0/bin/node' version='v18.16.1'

Current Stack: t0yv0/gcp-621/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/t0yv0
User           t0yv0
Organizations  t0yv0, pulumi
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/gcp     6.50.0
@pulumi/pulumi  3.87.0
@types/node     16.18.58

Pulumi locates its logs in /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/ by default

```

We can extract this into a unit test specifically for the `/tfbridge.(*Provider).Read` method using replay tests. Once this is tested and passing, if removing the patch still passes the test the patch is safe to remove.

**Comment by guineveresaenger** [comment]
Verified same panic persists if we remove the patch.

Filing a bridge issue here: https://github.com/pulumi/pulumi-terraform-bridge/issues/1423
