### ISSUE TITLE
Remove Add-flattening-of-self-managed-certificates.patch

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-gcp#1188]
[This patch](https://github.com/pulumi/pulumi-gcp/blob/6a64ebe/patches/0004-Add-flattening-of-self-managed-certificates.patch) sets a property during read. Looks like this is a fix for https://github.com/hashicorp/terraform-provider-google/issues/12091.

### Tests
None

### Recommendation
On an infinite time scale, we should add tests.

**Comment by guineveresaenger** [comment]
The upstream issue has since been resolved. 

Additionally I have verified that removing this patch and running a program with a self-managed certificate against a local build of this provider, succeeds.

We can remove this patch.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-gcp/issues/2290

**Comment by iwahbe** [comment]
> The upstream issue has since been resolved.
> 
> Additionally I have verified that removing this patch and running a program with a self-managed certificate against a local build of this provider, succeeds.
> 
> We can remove this patch.

Awesome. Can we just open a PR to remove the patch? Do you want to do the honors?

**Comment by guineveresaenger** [comment]
Fixed via https://github.com/pulumi/pulumi-gcp/pull/2355.
