### ISSUE TITLE
Remove-security-policy-default-versioned_expr.patch

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-gcp#1189]
[This patch](https://github.com/pulumi/pulumi-gcp/blob/6a64ebe/patches/0005-Remove-security-policy-default-versioned_expr.patch) removes `Default: ""` from a field. Presumably this is because it is not compatible with the field `validator: ValidateFunc: validation.StringInSlice([]string{"SRC_IPS_V1"}, false).` We should confirm that this is still an issue and open a tracking issue in the bridge. This is almost certainly a bridge bug.

### Tests
None

### Recommendation
If the upstream provider assumes that a field is non-empty but we removed the default, we could see a panic. This should have a test before the next major release.

**Comment by guineveresaenger** [comment]
Update: The bridge bug has been fixed as per https://github.com/pulumi/pulumi-gcp/issues/1029#issuecomment-1472632119.

I built v7 of this provider and verified that we the default security policy no longer errors.

Will add a test to this effect.
