### ISSUE TITLE
Incorrect statement about secrets being plain text

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi-gcp#1195]
A community user noticed our [GCP secretversion docs](https://www.pulumi.com/registry/packages/gcp/api-docs/secretmanager/secretversion/) contain a statement inherited from the [Terraform docs](https://github.com/hashicorp/terraform-provider-google-beta/blob/0af9b04b0d8b2db64ea947b900b2ed76bdef465e/website/docs/r/secret_manager_secret_version.html.markdown#L26-L28) about secrets being stored in plain text:

![image](https://github.com/pulumi/registry/assets/274700/86f1cbf0-a37d-4917-be51-8ce7e344c6be)

In our case, however, this isn't true; secret data is stored in cyphertext. We should correct this so users aren't alarmed by it.

**Comment by mikhailshilkov** [comment]
@thomas11 Your second link goes to our triage google doc, I think you may have wanted to link to another place?

**Comment by lukehoban** [comment]
Another user mentioned hitting this issue today.  They believed the statement in the docs, and that led them to build a very complex and brittle workaround.  Reminder of how important this is to fix.
