### ISSUE TITLE
GCP release failed

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-gcp#1197]
### What happened?

https://github.com/pulumi/pulumi-gcp/actions/runs/6172103906 didn't release. 

### Expected Behavior

Releasing works as expected.

### Steps to reproduce

See above.

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
https://github.com/pulumi/ci-mgmt/pull/572 was merged in to remove the goreleaser post hook steps which should help unblock releasing.

**Comment by t0yv0** [comment]
I'll run it to update workflows in gcp. Thank you!

**Comment by rquitales** [comment]
[v6.65.1](https://github.com/pulumi/pulumi-gcp/releases/tag/v6.65.1) of this provider is now released.
