### ISSUE TITLE
Enabling compute service in project before using getZones.

### ISSUE THREAD

**Issue by apichick** [pulumi/pulumi-gcp#120]
I need to get the available zones in a region provided that the compute service has already being enabled in the project. 

```
const services = new gcp.projects.Services('services', {
    services: ['compute.googleapis.com'],
});

const available = pulumi.output(gcp.compute.getZones({}));

```

How can I make sure that getZones runs once the service has been enabled. I don't see a way of handling the dependency.

Thx

**Comment by lukehoban** [comment]
I expect the following should work:

```typescript
const services = new gcp.projects.Services('services', {
    services: ['compute.googleapis.com'],
});

const available = services.id.apply(_ => gcp.compute.getZones({}));
```

The `apply` will only run after the services have been registered.
