### ISSUE TITLE
enabling cloud billing on a project using the gcp.billing.ProjectInfo class returns 404.

### ISSUE THREAD

**Issue by aaron-tillekeratne** [pulumi/pulumi-gcp#1212]
### What happened?

Trying to enable billing on a newly created GCP project using gcp.billing.ProjectIinfo() returns 
`gcp:billing:ProjectInfo (billing-account-association):
    error: 1 error occurred:
        * Error creating ProjectInfo: googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
    <html lang=en>
      <meta charset=utf-8>
      <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
      <title>Error 404 (Not Found)!!1</title>
      <style>
        *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
      </style>
      <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
      <p><b>404.</b> <ins>That’s an error.</ins>
      <p>The requested URL <code>/v1/projects/projects/{project-name}/billingInfo/?alt=json</code> was not found on this server.  <ins>That’s all we know.</ins>`

### Example

```python
import pulumi_gcp as gcp

ORG_ID="some-org-id"
PROJECT_ID="foo"
BILLING_ACCOUNT_ID="some-billing-account-id"
# create a project
proj= gcp.organizations.Project(
            resource_name="project",
            project_id=PROJECT_ID,
            org_id=ORG_ID,
        )
# enable cloud billing api
billing_api = gcp.projects.Service(
            resource_name="billing-api",
            project=proj.id,
            service="cloudbilling.googleapis.com",
            opts=pulumi.ResourceOptions(depends_on=proj),
        )
# associate billing 
gcp.billing.ProjectInfo(
            resource_name="billing-account-association",
            billing_account=BILLING_ACCOUNT_ID,
            project=proj.id,
            opts=pulumi.ResourceOptions(depends_on=[billing_api]),
        )
```

### Output of `pulumi about`

CLI          
Version      3.84.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME    VERSION
gcp     6.66.0
python  unknown

Host     
OS       debian
Version  11.7
Arch     x86_64

This project is written in python: executable='/usr/local/bin/python3' version='3.11.5

### Additional context

The pulumi AI is also not producing runnable python code in regards to this matter. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
It looks like the URL is indeed incorrect: `/v1/projects/projects/{project-name}/billingInfo/?alt=json` has two `projects` in it. I suppose that it's because you should pass `proj.project_id`(project name) instead of `proj.id` (resource ID):

```
gcp.billing.ProjectInfo(
            resource_name="billing-account-association",
            billing_account=BILLING_ACCOUNT_ID,
            project=proj.project_id, # here
            opts=pulumi.ResourceOptions(depends_on=[billing_api]),
        )
```

Could you please give it a try?

**Comment by aaron-tillekeratne** [comment]
Hi @mikhailshilkov , yep you're correct. it should be `proj.project_id`. It worked fine after that. Closing this one.
