### ISSUE TITLE
There is no way to execute a CloudRunv2 Job through Pulumi using the gcp provider

### ISSUE THREAD

**Issue by alextricity25** [pulumi/pulumi-gcp#1213]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
There is no way to execute a CloudRunv2 Job through Pulumi using the gcp provider.

The cloudrunv2 nodejs library doesn't seem to have the [`ExecutionsClient`](https://cloud.google.com/nodejs/docs/reference/run/latest/run/v2.executionsclient) implemented. Without this client, there is no way to execute a defined CloudRun job through Pulumi using the gcp provider.

### Affected area/feature
`gcp.sdk.nodjs.cloudrunv2`

**Comment by mikhailshilkov** [comment]
It looks like this is tracked upstream in https://github.com/hashicorp/terraform-provider-google/issues/13390

Is this what you are looking for @alextricity25?

**Comment by mikhailshilkov** [comment]
The upstream issue has been close with this comment: https://github.com/hashicorp/terraform-provider-google/issues/13390#issuecomment-2348911791

I suppose we need to follow them and close this issue as done. Feel free to report a new issue if the solution is not satisfactory.
