### ISSUE TITLE
TTL policy for Firestore in Datastore mode database.

### ISSUE THREAD

**Issue by lrnq** [pulumi/pulumi-gcp#1215]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The `pulumi_gcp.firestore` module allows for the creation of a Firestore database in Datastore mode using `pulumi_gcp.firestore.Datastore` by setting `type="DATASTORE_MODE"`. A Firestore database in Datastore mode enables you to [manage data retention with TTL policies](https://cloud.google.com/datastore/docs/ttl). As far as I can determine, this feature is missing from `pulumi-gcp`.

Note: If the Firestore database is created in Firestore native mode, one can attach a Field (analogous to a Property in Datastore mode) with a TTL policy as demonstrated [here](https://www.pulumi.com/registry/packages/gcp/api-docs/firestore/field/#firestore-field-timestamp).

### Affected area/feature

Presumably the `pulumi_gcp.firestore` module.

**Comment by mikhailshilkov** [comment]
I think the same was requested upstream here: https://github.com/hashicorp/terraform-provider-google/issues/14806

Once this ships, we'll provide it as well.

**Comment by twhc20** [comment]
Any updates on this?

**Comment by mikhailshilkov** [comment]
@twhc20 Based on the upstream comment, you should be able to configure TTL with the `Field` resource: https://www.pulumi.com/registry/packages/gcp/api-docs/firestore/field/#ttlconfig_nodejs
