### ISSUE TITLE
After creating GKE cluster, calling Pulumi Refresh causes a recreate on the cluster/node pools without other changes.

### ISSUE THREAD

**Issue by mfacenet** [pulumi/pulumi-gcp#122]
After I run pulumi up and create: 
1 network
1 subnetwork (with multiple cidrs)
1 GKE cluster
2 Node Pools

calling pulumi refresh followed by pulumi up recreates the cluster and node pools, makes additional changes to the subnetwork.

config.ts:
```ts
import { Config } from "@pulumi/pulumi";
import * as pulumi from "@pulumi/pulumi";
const config = new Config();

export const name = pulumi.getStack();
export const maintenanceWindow = config.get("startTime") || "09:00";
export const gkeVersion = config.get("gkeVersion") || "1.12.6-gke.7";
export const mainCIDR = config.get("mainCIDR") || "10.0.0.0/16";
export const clusterCIDR = config.get("clusterCIDR") || "10.1.0.0/16";
export const serviceCIDR = config.get("serviceCIDR") || "10.2.0.0/16";
export const coreMin = config.getNumber("coreMin") || 2;
export const coreInitial = config.getNumber("coreInitial") || 2;
export const coreType = config.get("coreType") || "n1-standard-1";
export const coreMax = config.getNumber("coreMax") || 10;
export const coreDisk = config.getNumber("coreDisk") || 100;
export const siteMin= config.getNumber("siteMin") || 1;
export const siteInitial = config.getNumber("siteInitial") || 1;
export const siteType = config.get("siteType") || "n1-standard-1";
export const siteMax = config.getNumber("siteMax") || 10;
export const siteDisk = config.getNumber("siteDisk") || 100;
```

index.ts:
```ts
import * as pulumi from "@pulumi/pulumi";
import * as gcp from "@pulumi/gcp";

import {
    name,
    maintenanceWindow,
    gkeVersion,
    coreInitial,
    coreMax,
    coreMin,
    coreType,
    coreDisk,
    siteInitial,
    siteMax,
    siteMin,
    siteType,
    siteDisk,
    mainCIDR,
    serviceCIDR,
    clusterCIDR
} from "./config";

export const vpc = new gcp.compute.Network(name, {
    name: name,
    autoCreateSubnetworks: false
});

const subnet = new gcp.compute.Subnetwork(name, {
    name: name,
    network: vpc.selfLink,
    ipCidrRange: mainCIDR,
    secondaryIpRanges: [
        {
            ipCidrRange: serviceCIDR,
            rangeName: "services",
        },
        {
            ipCidrRange: clusterCIDR,
            rangeName: "pods",
        }]
}, {
    dependsOn: vpc,
    parent: vpc
});

const k8sCluster = new gcp.container.Cluster("gke-cluster",
    {
        name: name,
        network: vpc.selfLink,
        subnetwork: subnet.selfLink,
        minMasterVersion: gkeVersion,
        nodeVersion: gkeVersion,
        loggingService: "logging.googleapis.com/kubernetes",
        monitoringService: "monitoring.googleapis.com/kubernetes",
        addonsConfig: {
            httpLoadBalancing: {
                disabled: false
            }
        },
        maintenancePolicy: {
            dailyMaintenanceWindow: {
                startTime: maintenanceWindow
            }
        },
        ipAllocationPolicy: {
            servicesSecondaryRangeName: "services",
            clusterSecondaryRangeName: "pods"
        },
        networkPolicy: {
            provider: "CALICO",
            enabled: true
        },
        nodePools: [{name: "default-pool",}],
        removeDefaultNodePool: true,
    },
    {
        deleteBeforeReplace: true,
        parent: subnet,
        dependsOn: subnet
    }
);
//Setup NodePools
export const corePool = new gcp.container.NodePool("corePool", {
    name: "core",
    cluster: k8sCluster.name,
    initialNodeCount: coreInitial,
    nodeConfig: {
        machineType: coreType,
        diskSizeGb: coreDisk,
        diskType: "pd-standard",
        oauthScopes: [
            "https://www.googleapis.com/auth/cloud-platform"
        ],
        imageType: "COS",
    },
    autoscaling: {
        maxNodeCount: coreMax,
        minNodeCount: coreMin
    },
    management: {
        autoUpgrade: true,
        autoRepair: true
    },
    version: gkeVersion
}, {
    deleteBeforeReplace: true,
    parent: k8sCluster,
    dependsOn: k8sCluster
});

const sitePool = new gcp.container.NodePool("sitePool", {
    name: "sites",
    cluster: k8sCluster.name,
    initialNodeCount: siteInitial,
    nodeConfig: {
        machineType: siteType,
        diskSizeGb: siteDisk,
        diskType: "pd-standard",
        oauthScopes: [
            "https://www.googleapis.com/auth/cloud-platform"
        ],
        imageType: "COS",
    },
    autoscaling: {
        minNodeCount: siteMin,
        maxNodeCount: siteMax
    },
    management: {
        autoRepair: true,
        autoUpgrade: true
    },
    version: gkeVersion
},{
    parent: k8sCluster,
    deleteBeforeReplace: true,
});
```

 Refresh on existing resources:
```
 ~         └─ gcp:container:Cluster           gke-cluster    update     [diff: +nodeConfig~instanceGroupUrls,nodePools]
              ├─ gcp:container:NodePool       corePool                  
              ├─ pulumi:providers:kubernetes  gkeK8s                    
              └─ gcp:container:NodePool       sitePool                  
```

Update Run 
```
  +-        └─ gcp:container:Cluster           gke-cluster    replace     [diff: -additionalZones,clusterAutoscaling,clusterIpv4Cidr,defaultMaxPodsPerNode,masterAuth,nodeConfig,project,zone~addonsConfig,ipAllocationPolicy,maintenancePolicy,network,nodePools,subnetw
 +-           ├─ gcp:container:NodePool       sitePool       replace     [diff: -maxPodsPerNode,namePrefix,nodeCount,project,zone~nodeConfig]
 +-           ├─ gcp:container:NodePool       corePool       replace     [diff: -maxPodsPerNode,namePrefix,nodeCount,project,zone~nodeConfig]
 ~            └─ pulumi:providers:kubernetes  gkeK8s         update      [
 diff: ~kubeconfig]
```

Refresh after "Console Upgrade of cluster"
```
~         └─ gcp:container:Cluster           gke-cluster    update     [diff: +nodeConfig~instanceGroupUrls,masterVersion,nodePools,nodeVersion]
              ├─ pulumi:providers:kubernetes  gkeK8s                    
 ~            ├─ gcp:container:NodePool       sitePool       update     [diff: ~nodeCount,version]
 ~            └─ gcp:container:NodePool       corePool       update     [diff: ~version]

 Update Plan:
      pulumi:pulumi:Stack                      cluster-repro              
     └─ gcp:compute:Network                   repro                      [diff: -description,ipv4Range,project,routingMode]
        └─ gcp:compute:Subnetwork             repro                      [diff: -description,enableFlowLogs,privateIpGoogleAccess,project,region]
 +-        └─ gcp:container:Cluster           gke-cluster    replace     [diff: -additionalZones,clusterAutoscaling,clusterIpv4Cidr,defaultMaxPodsPerNode,masterAuth,nodeConfig,project,zone~addonsConfig,ipAllocationPolicy,maintenancePolicy,network,nodePools,nodeVer
 +-           ├─ gcp:container:NodePool       corePool       replace     [diff: -maxPodsPerNode,namePrefix,nodeCount,project,zone~nodeConfig,version]
 +-           ├─ gcp:container:NodePool       sitePool       replace     [diff: -maxPodsPerNode,namePrefix,nodeCount,project,zone~nodeConfig,version]
 ~            └─ pulumi:providers:kubernetes  gkeK8s         update      [diff: ~kubeconfig]
```

**Comment by mfacenet** [comment]
Note that in this case, I overwrote the version using pulumi config set to test (set it to a 1.12 version)

**Comment by clstokes** [comment]
"Console Upgrade of cluster" in this case is upgrading the cluster from 1.12 to 1.13 in the compute console.

**Comment by lukehoban** [comment]
I would guess this is related to https://github.com/pulumi/pulumi-gcp/issues/88 - which I suspect is also the root cause of https://github.com/pulumi/pulumi-gcp/issues/116.  If so, we will pick up the fix as part of adopting the (not yet released) `2.4.0` version of the Google Terraform Provider from upstream.  See https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGELOG.md#240-unreleased.

We could better confirm that this is truly the root cause if you could run `pulumi preview --logtostderr -v-7 2> out.txt` and then find lines that mention `replaces=` in that output and share them here.  This should make clear what properties are actually triggering the replacement in your particular case.

**Comment by mfacenet** [comment]
> pulumi preview --logtostderr -v-7 2> out.txt

I0403 12:07:49.445090   21056 log.go:56] Error closing 'nodejs' language plugin during shutdown; ignoring: 1 error occurred:

* operation not permitted

Not quite the output that I think you were hoping for.

**Comment by mfacenet** [comment]
These are the resources in red on the output: 
gke-cluster  replace     [diff: -additionalZones,clusterAutoscaling,clusterIpv4Cidr,defaultMaxPodsPerNode,location,masterAuth,nodeConfig,nodeLocations,project,zone

**Comment by lukehoban** [comment]
Sorry - looks like I had a typo - I meant to say: `pulumi preview --logtostderr -v=7 2> out.txt`.  Could you try that?

Unfortunately, due to https://github.com/pulumi/pulumi/issues/2453, the diff presented in the user output is not reliable in these cases, and so to debug this we need to see what the provider really reported was requiring replacement.

**Comment by mfacenet** [comment]
Output provided out of band, will let @lukehoban add any relevant output as needed.

**Comment by lukehoban** [comment]
Confirmed from looking at logs that this is the same issue discussed in https://github.com/pulumi/pulumi-gcp/issues/88#issuecomment-477463185.

In particular, in @mfacenet's case - he is seeing:

```
#replaces=[nodePools]
```

So only the perceived `nodePools` change is triggering this as in https://github.com/pulumi/pulumi-gcp/issues/88#issuecomment-477463185 (and also related to use of `removeDefaultNodePool: true`.

**Comment by mfacenet** [comment]
So interestingly enough, this seems to be related to the empty default-pool being specified, I was able to rectify this specific happening of the issue, however, after running a cluster node upgrade and refresh, pulumi tries to update what is labeled as (minVersion)
` ~         └─ gcp:container:Cluster      gke-cluster  update     [diff: ~nodeVersion]
 ~            └─ gcp:container:NodePool  corePool     update     [diff: ~version]
`

and then fails in the update run itself:
`
Updating (repro):

     Type                            Name         Status                  Info
     pulumi:pulumi:Stack             repro-repro  **failed**              1 error
     └─ gcp:compute:Network          repro                                
        └─ gcp:compute:Subnetwork    repro                                
 ~         └─ gcp:container:Cluster  gke-cluster  **updating failed**     [diff: ~nodeVersion]; 1 error
 
Diagnostics:
  pulumi:pulumi:Stack (repro-repro):
    error: update failed
 
  gcp:container:Cluster (gke-cluster):
    error: Plan apply failed: 1 error occurred:
    
    * updating urn:pulumi:repro::repro::gcp:compute/network:Network$gcp:compute/subnetwork:Subnetwork$gcp:container/cluster:Cluster::gke-cluster: node_version was updated but default-pool was not found. To update the version for a non-default pool, use the version attribute on that pool.
 

`

**Comment by mfacenet** [comment]
Meh, looks like only the masters reflect a minimum version, this is fixed by remove nodeVersion from the nodePools and the master.
