### ISSUE TITLE
Publish a GCP 7.0 migration guide

### ISSUE THREAD

**Issue by mnlumi** [pulumi/pulumi-gcp#1247]
Migration details will be in both the release notes in github and published as a page on https://www.pulumi.com/registry/packages/gcp/how-to-guides/.

**Comment by guineveresaenger** [comment]
Collaborative drafting doc here: https://docs.google.com/document/d/1GOovPt6gDKDiks9wo1ha6vMV8-0FOdhH4kmaTwmOito/edit#heading=h.5cb0dzlaz83h

**Comment by mnlumi** [comment]
https://github.com/pulumi/registry/pull/3474
