### ISSUE TITLE
Added/removed accessConfigs after inital instance creation do not get recognized

### ISSUE THREAD

**Issue by tferazzi** [pulumi/pulumi-gcp#1252]
### What happened?

Deploying an instance with a public IP initially and removing it afterwards does not get recognized by pulumi.

### Example

Deploying an instance with a public IP like this:
```typescript
new gcp.compute.Instance('my-instance-name', {
    name: 'my-instance-name',
    zone: 'europe-west4-a',
    machineType: 'f1-micro',
    networkInterfaces: [
      {
        subnetwork: args.subnetworkId,
        accessConfigs: [
          {
            networkTier: 'PREMIUM',
          },
        ],
      },
    ],
    bootDisk: {
      initializeParams: {
        image: 'ubuntu-2204-jammy-v20230727',
      },
    },
  });
```
And then removing the `accessConfigs` block like this:
```typescript
new gcp.compute.Instance('my-instance-name', {
    name: 'my-instance-name',
    zone: 'europe-west4-a',
    machineType: 'f1-micro',
    networkInterfaces: [
      {
        subnetwork: args.subnetworkId,
        // accessConfigs: [
        //   {
        //     networkTier: 'PREMIUM',
        //   },
        // ],
      },
    ],
    bootDisk: {
      initializeParams: {
        image: 'ubuntu-2204-jammy-v20230727',
      },
    },
  });
```
And doing `pulumi up` again, results in no update/change of the instance.

### Output of `pulumi about`

```
CLI
Version      3.88.0
Go Version   go1.21.2
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       darwin
Version  13.6
Arch     arm64
```

### Additional context

This also does not work the other way round:
1. Instance without public IP address
2. Add `accessConfigs` block to `networkInterfaces`
3. `pulumi up` -> results in no changes 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Unfortunately, it looks like this issue hasn't seen any updates in a while. If you're still encountering this problem, could you leave a quick comment to let us know so we can prioritize it?

**Comment by tferazzi** [comment]
Hi, just tested this again: Removing the `accessConfigs` block now results in a diff/replace. So everything working as expected. Thank you for following up on this.

Tested with
```
> pulumi about

CLI
Version      3.134.0
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  gcp     7.38.0
language  nodejs  3.134.0-dev.0

Host
OS       darwin
Version  14.7
Arch     arm64
```
