### ISSUE TITLE
Fix up documentation for new Labels

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-gcp#1274]
Depends on #1273

We will need to address all references to `terraform` in the documentation for the about-to-become-ubiquitous [new labels]https://github.com/pulumi/pulumi-gcp/issues/1273. 

Prior art using `DocRules` can be found here: https://github.com/pulumi/pulumi-aws/pull/2883

**Comment by guineveresaenger** [comment]
There seem to be no `terraform` references in the new Labels documentation so this issue is likely a no-op.

**Comment by iwahbe** [comment]
What do we need to do to mark this as closed?

**Comment by guineveresaenger** [comment]
Unfortunately one instance did escape bot human and bridge detection: https://www.pulumi.com/registry/packages/gcp/api-docs/storage/bucket/. 

I do not know why tfgen failed to detect this. The reason we did not detect it locally is because the schema is difficult to search due to its size.

Linking #1332 to address this.
