### ISSUE TITLE
Verify behavior of upstream Labels 

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-gcp#1275]
Reference: https://docs.google.com/document/d/1pZDKjs4xbKj-vvtxr5ETNB_fGWZ0m6uQErrLLWn4AFw/edit#heading=h.kz0qlzp5i6vk

Add test cases that verify:

- Create sets defaultLabels on resources

- Update detects a Label diff correctly and applies changes at the correct time in the lifecycle
    - Removing defaultLabels percolates to resources
- Ensure `pulumiLabels` and `effectiveLabels` get updated similarly

**Comment by guineveresaenger** [comment]
First findings:

- Create works as expected
- Removing a defaultLabel works as expected, with a diff on both provider and resource
- _Adding_ a defaultLabel to an already existing stack does _not_ percolate to the relevant resource.

<details>
  <summary>Expand for detailed output when running an update to add a new defaultLabel</summary>
  The diff shows for defaultLabels but it does not persist down to the pulumiAllLabels Output. This is true whether we are adding a label to already-existing defaultLabels or whether we add the `defaultLabels` field.
  
```
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/guinevere-pulumi-corp/dev/dev/previews/215619a8-a832-43a7-8c05-c15eb96d3239

     Type                     Name          Plan       Info
     pulumi:pulumi:Stack      dev-dev                  2 warnings
 ~   └─ pulumi:providers:gcp  gcp-provider  update     [diff: ~defaultLabels]

Diagnostics:
  pulumi:pulumi:Stack (dev-dev):
    warning: using pulumi-resource-gcp from $PATH at /Users/guin/go/src/github.com/pulumi/pulumi-gcp/bin/pulumi-resource-gcp
    warning: using pulumi-resource-gcp from $PATH at /Users/guin/go/src/github.com/pulumi/pulumi-gcp/bin/pulumi-resource-gcp

Resources:
    ~ 1 to update
    2 unchanged

Do you want to perform this update? yes
Updating (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/guinevere-pulumi-corp/dev/dev/updates/3

     Type                     Name          Status              Info
     pulumi:pulumi:Stack      dev-dev                           2 warnings
 ~   └─ pulumi:providers:gcp  gcp-provider  updated (0.09s)     [diff: ~default

Diagnostics:
  pulumi:pulumi:Stack (dev-dev):
    warning: using pulumi-resource-gcp from $PATH at /Users/guin/go/src/github.com/pulumi/pulumi-gcp/bin/pulumi-resource-gcp
    warning: using pulumi-resource-gcp from $PATH at /Users/guin/go/src/github.com/pulumi/pulumi-gcp/bin/pulumi-resource-gcp

Outputs:
    bucketName       : "gs://my-bucket-dca45c3"
    pulumiAllLabels  : {
        bad  : "things"
        good : "morning"
        hello: "goodbye"
    }
    resourceSetLabels: {
        bad : "things"
        good: "morning"
    }

Resources:
    ~ 1 updated
    2 unchanged

Duration: 2s
```
</details>

**Comment by t0yv0** [comment]
I would like to suggest adding randomized state transition tester a-la https://github.com/pulumi/pulumi-aws/pull/2944/files#diff-2e4fffe32720b3d310b4336cfdde6519ab1bf6d9e0d82b418299817fdf42a29fR87 may I contribute this here quickly?  The experience on AWS with default tags is very unfortunate, and having a comprehensive matrix for all CRUD state transitions and combinations of tags is the level of confidence I'd like to get to here.

**Comment by guineveresaenger** [comment]
Closed via https://github.com/pulumi/pulumi-terraform-bridge/pull/1502.
