### ISSUE TITLE
Compute package too big and uses 8GB for go compilation

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-gcp#1283]
### What happened?

Per the demo in https://github.com/pulumi/pulumi-cloud-requests/issues/313#issuecomment-1777105959

Currently sdk/go/gcp/compute package is too big. Since packages serve as Go compilation units, Go is compiling this package in one pass. This causes 8GB+ RAM consumption, making it unsuitable for low-memory environments such as CI.

Clearly the supplementary types are the culprit here:

```
5.4M    pulumiTypes.go
1.4M    pulumiTypes1.go
```

One possibility here is that if we find a way to partition this package by moving the supplementary types to other packages (or removing them), it could greatly reduce RAM consumption for programs consuming the compute module.

### Example

```go
package main

import (
	"github.com/pulumi/pulumi-gcp/sdk/v6/go/gcp/compute"
)

func main() {
	_ = compute.NewNetworkPeeringRoutesConfig
}
```

### Output of `pulumi about`

3.86.0

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
I'm going to add this to the GCP v7 release epic, since splitting up the compute package in any way must happen during a major release.

We might come up with some other solution, but until we do we should make sure this is taken into account when making the release.

**Comment by t0yv0** [comment]
It sounds like we could take change that would be "breaking around the edges" technically breaking but not affecting too many programs hopefully. A few options.

Options involving editing codegen to move or remove supplementary types, perhaps with some partitioning. The advantage of these is that things like second-level "a.b.c." supplementary types or types that e.g. support Input/Output monomorphic forms are not used as often and moving them is "slightly" breaking.

- teach codegen to split/move pulumiTypes specifically to a different Go package, perhaps informed by flags
- audit pulumiTypes to see if any can be removed completely to reduce the set

Options not involving editing codegen and straight in providers land, is to break up the "compute" module into more modules, at schema generation time. This will move resources as well as supplementary types and partition them into smaller boxes that can alleviate the problem greatly. 

How good are we with moving resources around and making the change not significantly breaking? Aliasing? How about documentaiton/examples/templates?
