### ISSUE TITLE
The Pulumi Docs for autoscaling in GCP Cloud Run are wrong

### ISSUE THREAD

**Issue by nick-catalist** [pulumi/pulumi-gcp#1291]
### What happened?

https://www.pulumi.com/registry/packages/gcp/api-docs/cloudrun/service/

The docs describe how to set autoscaling via knative annotations in a Cloud Run service. They claim that this should be in the top level "metadata" field on the service, of type ServiceMetadataArgs:

```
Optional metadata for this Revision, including labels and annotations. Name will be generated by the Configuration. To set minimum instances for this revision, use the "autoscaling.knative.dev/minScale" annotation key. To set maximum instances for this revision, use the "autoscaling.knative.dev/maxScale" annotation key. To set Cloud SQL connections for the revision, use the "run.googleapis.com/cloudsql-instances" annotation key. Structure is documented below.
```

However, this is incorrect, and setting this annotation will not set autoscaling on your Cloud Run service. It's easy to reproduce this, just create a cloud run via Pulumi using this recommendation. It will indeed set an annotation on the service-level metadata, but you can see in the GCP console that the "min instances" is unset. If you set min instances via the GCP console, you'll see that this annotation actually gets set at `spec.template.metadata` instead.

### Example

```
cloud_run_service = cloudrun.Service(
            "cloud-run",
            name="service",
...
            metadata=cloudrun.ServiceMetadataArgs(
                annotations={
                    "autoscaling.knative.dev/minScale": "1",
                }
            ),
```

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
This is defined upstream, the same comment exists for both annotations:
- https://github.com/hashicorp/terraform-provider-google/blob/6d08dda9b0fcff1897fbf786b438819e5cadf64a/google/services/cloudrun/resource_cloud_run_service.go#L750
- https://github.com/hashicorp/terraform-provider-google/blob/6d08dda9b0fcff1897fbf786b438819e5cadf64a/google/services/cloudrun/resource_cloud_run_service.go#L902

I'm not exactly sure why, but I think we apply all the docs truthfully.

**Comment by mjeffryes** [comment]
I believe this is fixed now, the top level metadata field was erroneously using the description for the `ServiceTemplate.metadata` field before, but it now correctly reads "Metadata associated with this Service, including name, namespace, labels, and annotations."
