### ISSUE TITLE
Duplicate URN error when trying to create 2 GKE clusters in differents projects/regions

### ISSUE THREAD

**Issue by kurlzor** [pulumi/pulumi-gcp#130]
I'm trying to create several clusters with the same name in different regions within the same stack, but it's impossible (eg. identical clusters named `prod` in regions `europe-west3` and `us-east1`).
I understand that the cluster name is used by terraform to generate the actual cluster name (with the random string at the end) if you don't specify `name` in the args. The problem is, the cluster name is used as-is to build the URN, so you can't have 2 clusters named the same, even though they're in different regions/projects and that it's perfectly valid (even in terraform).
Do you have plans to only have unique names by default so it's not up to the user to come up with one ? Here, you could use the combination of project id, region/zone and cluster name to ensure that it's unique.

**Comment by lukehoban** [comment]
You can create the cluster with:

```
let cluster = new gcp.container.Cluster("puluminame", {
    name: "googlename",
});
```

This allows the `puluminame` which must be unique for all resources in the Pulumi program to differ from the `googlename` which you want to be the same in each region.  

The `name: ...` argument is optional, and will default to a randomly generated name with `puluminame` as a prefix if not provided - but you can override this by specifying an explicit `name:`.

I believe this should address your scenario - but let me know if it does not.
