### ISSUE TITLE
bug: big query routines using table functions

### ISSUE THREAD

**Issue by terekete** [pulumi/pulumi-gcp#1324]
### What happened?

- when defining a stored procedure (routine) via Pulumi whose query contains a table function, it requires the table function include the full path; `<project id>.<dataset id>.<table function>`.
- if one tries this exact operations on the console or running on bq studio it allows for not using full table function path, it works; <dataset id>.<table function>

example: `BEGIN select * from <project id>.<dataset id>.<table function>; END`

Wondering if something is not being passed down from the pulumi reference for it to know to look at the same project for the dataset and table function reference. This only appears to be happening when building from IaC.

### Example

When defining the routine this way it works:
example: `BEGIN select * from <project id>.<dataset id>.<table function>; END`

When defining the routine this way it does not work:
example: `BEGIN select * from <dataset id>.<table function>; END`

When defining the routine via the BQ console with either approach it works.

error: 
Error creating Routine: googleapi: Error 400: Within a standard SQL procedure, references to functions/procedures require explicit project IDs unless the entity is created in the same project that is issuing the query, but these references are not project-qualified: "ban_base.ban_msisdn_imsi_tf", invalidQuery

### Output of `pulumi about`

versions:

gcp : 6.58.0   
str :1.0.0  
pulumi : v3.72.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Hi @terekete thank you for reporting this issue. Would you be able to provide a sample program for us to reproduce the issue?
