### ISSUE TITLE
V7.0.0 has a know issue with bigquery views ans schemas

### ISSUE THREAD

**Issue by dermasmid** [pulumi/pulumi-gcp#1329]
### What happened?

this issue was reported in https://github.com/hashicorp/terraform-provider-google and has since been fixed (i think `5.2.0`) but pulumi `v7.0.0` uses `5.0.0`

### Example

heres links to the issues: 
https://github.com/hashicorp/terraform-provider-google/issues/16134
https://github.com/hashicorp/terraform-provider-google/issues/16192

### Output of `pulumi about`

CLI          
Version      3.92.0
Go Version   go1.21.3
Go Compiler  gc

Host     
OS       darwin
Version  14.1.1
Arch     arm64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Thank you for letting us know this is urgent for you. We will have the upgrade/fix for most recent upstream for you shortly.
