### ISSUE TITLE
Java build failure during SDK release job

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-gcp#1353]
### What happened?

```/home/runner/work/pulumi-gcp/pulumi-gcp/sdk/java/src/main/java/com/pulumi/gcp/compute/inputs/GlobalForwardingRuleState.java:1169: error: unknown tag: pattern:
         *   @pattern: \d+(?:-\d+)?
             ^
23 errors

```

It appears that the release workflow https://github.com/pulumi/pulumi-gcp/actions/runs/6881931301/job/18720430202#step:3:6581 did not build (or publish) the Java SDK properly.

### Example

N/A

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
A rerun resulted in the same error: https://github.com/pulumi/pulumi-gcp/actions/runs/6881931301/job/18728079843#step:3:2830

**Comment by t0yv0** [comment]
Ah I see I guess we're expecting 7.1.x patch to relese but we forfeit having 7.1.0 in https://central.sonatype.com/artifact/com.pulumi/gcp/versions .. slightly unfortunate but does indeed resolve the problem. Thank you.
