### ISSUE TITLE
Failure creating gcp:dns:ResponsePolicy

### ISSUE THREAD

**Issue by sunilrr** [pulumi/pulumi-gcp#1362]
### What happened?

Creating DNS response policy fails possibly due to wrong URL.

`The requested URL <code>/dns/v1beta2/projects/projects/myproject-26-d3fb4b/responsePolicies?alt=json</code> was not found on this server.`

Documentation [here](https://cloud.google.com/dns/docs/reference/v1beta2/responsePolicies/create).

### Example

# https://cloud.google.com/run/docs/securing/using-vpc-service-controls
        self.cloudrun_dns_policy = gcp.dns.ResponsePolicy(
            "cloudrun-private-vpc",
            response_policy_name="cloudrun-private-response-policy",
            networks=[
                gcp.dns.ResponsePolicyNetworkArgs(
                    network_url=self.network.network.name,
                ),
            ],
            project=self.project.id,
            opts=pulumi.ResourceOptions(
                depends_on=[self.vpc_access_api, self.network],
            ),
        )
        self.cloudrun_dns_policy_rule_1 = gcp.dns.ResponsePolicyRule(
            "cloudrun-private-policy-rule-1",
            response_policy=self.cloudrun_dns_policy.response_policy_name,
            rule_name="cloudrun-vpc",
            dns_name="*.run.app.",
            local_data=gcp.dns.ResponsePolicyRuleLocalDataArgs(
                local_datas=[
                    gcp.dns.ResponsePolicyRuleLocalDataLocalDataArgs(
                        name="restricted.googleapis.com.",
                        type="A",
                        ttl=300,
                        rrdatas=["199.36.153.4|199.36.153.5|199.36.153.6|199.36.153.7"],
                    )
                ],
            ),
            project=self.project.id,
            opts=pulumi.ResourceOptions(
                depends_on=[self.cloudrun_dns_policy],
            ),
        )
        self.cloudrun_dns_policy_rule_2 = gcp.dns.ResponsePolicyRule(
            "cloudrun-private-policy-rule-2",
            response_policy=self.cloudrun_dns_policy.response_policy_name,
            rule_name="cloudrun-vpc",
            dns_name="*.googleapis.com.",
            local_data=gcp.dns.ResponsePolicyRuleLocalDataArgs(
                local_datas=[
                    gcp.dns.ResponsePolicyRuleLocalDataLocalDataArgs(
                        name="restricted.googleapis.com.",
                        type="A",
                        ttl=300,
                        rrdatas=["199.36.153.4|199.36.153.5|199.36.153.6|199.36.153.7"],
                    )
                ],
            ),
            project=self.project.id,
            opts=pulumi.ResourceOptions(
                depends_on=[self.cloudrun_dns_policy],
            ),
        )

### Output of `pulumi about`

➜ pulumi about 
CLI          
Version      3.94.2
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME       VERSION
command    0.7.0
cp-deploy  0.1.0
gcp        6.67.0
python     unknown
random     4.11.2

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
The URL looks incorrect:

> v1beta2/projects/projects/myproject-26-d3fb4b

This is probably you need to replace

> project=self.project.id,

with 

> project=self.project.project_id,

`project.id` is `projects/myproject-26-d3fb4b` while `project_id` is `myproject-26-d3fb4b`.

Let me know if this helps.

**Comment by sunilrr** [comment]
Yes, this did resolve the issue. Thanks.
