### ISSUE TITLE
gcp::iam::workloadidentityPoolProvider attribute mapping error: expected property name after '.'

### ISSUE THREAD

**Issue by davidmdm** [pulumi/pulumi-gcp#1366]
### What happened?

When running pulumi preview or up with an existing stack containing a `workloadIdentityPoolProvider` with attribute mappings the following error occurs:

`error: expected property name after '.'`

The only way to resolve this issue manually has been to `pulumi stack export`, remove the attribute mappings manually and reimport the stack. 

```
...

"type": "gcp:iam/workloadIdentityPoolProvider:WorkloadIdentityPoolProvider",
"inputs": {
    "__defaults": [],
    "attributeCondition": "attribute.repository_visibility == \"private\"",
    "attributeMapping": {
        "__defaults": []
    },

...
```

### Example

```ts
new gcp.iam.WorkloadIdentityPoolProvider(
      name,
      {
        project: args.projectId,
        workloadIdentityPoolId: workloadPool.workloadIdentityPoolId,
        workloadIdentityPoolProviderId: name,
        oidc: {
          issuerUri: args.oidc.issuerUri,
        },
        attributeMapping: {
          // UNCOMMENTING THESE WILL CREATE ATTRIBUTE MAPPINGS AND BREAK THE STACK
          // ...args.oidc.attributeMapping,
          // 'google.subject': 'assertion.sub',
        },
        attributeCondition: args.oidc.attributeCondition,
      },
      { parent: workloadPool }
    );
```

### Output of `pulumi about`

Dependencies:
NAME                   VERSION
@pulumi/datadog        4.19.1
@pulumi/github         5.12.0
@pulumi/google-native  0.31.0
@pulumi/gcp            6.58.0
@googleapis/iam        7.1.0
@pulumi/pulumi         3.94.2
common                 0.0.0
fast-deep-equal        3.1.3
@pulumi/pagerduty      3.10.2
@pulumi/random         4.13.2
@types/node-fetch      2.6.4
@types/node            18.11.19
prettier               3.0.3

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Which CLI version are you running? This sounds like https://github.com/pulumi/pulumi/issues/14439 which was fixed in pulumi CLI version 3.92.0.

**Comment by davidmdm** [comment]
I am using
```
pulumi version
v3.91.1
```

I will try updating and see what happens.

**Comment by davidmdm** [comment]
Upgrading worked. Will close this error. For my own edification (and those why may stumble upon this question), what is the relationship between the pulumi CLI version and the @pulumi/pulumi npm package? I had updated the npm package after seeing [#14439](https://github.com/pulumi/pulumi/issues/14439) but did not think of upgrade the CLI

**Comment by iwahbe** [comment]
@davidmdm The CLI version and `@pulumi/pulumi` NPM package version can both float against each other. Some features require a certain version (or greater) on both the SDK and the CLI.
