### ISSUE TITLE
Docs for NodePool are misleading

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-gcp#1510]
### What happened?

The docs for the NodePool resource: https://www.pulumi.com/registry/packages/gcp/api-docs/container/nodepool/
are misleading since the name of a NodePool needs to be all lower-case.

### Example

The example yields the following error:
```
Diagnostics:
  gcp:container:NodePool (primaryPreemptibleNodes):
    error: 1 error occurred:
        * creating urn:pulumi:dev::cluster::gcp:container/nodePool:NodePool::primaryPreemptibleNodes: 1 error occurred:
        * error creating NodePool: googleapi: Error 400: Invalid value for field "node_pool.name": "primaryPreemptibleNodes-b8a97f9". Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,38}[a-z0-9])?)' (only lowercase alphanumerics and '-' allowed, must start with a letter and end with an alphanumeric, and must be no longer than 40 characters).
    Details:
    [
      {
        "@type": "type.googleapis.com/google.rpc.RequestInfo",
        "requestId": "0x946efa1f93d34437"
      }
    ]
    , badRequest

  pulumi:pulumi:Stack (cluster-dev):
    error: update failed
```

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
This looks like it has been fixed, possibly upstream?

<img width="705" alt="Screenshot 2024-04-22 at 12 28 51 PM" src="https://github.com/pulumi/pulumi-gcp/assets/13116240/c0353043-e607-4c98-bbb1-3213bd0edebc">
