### ISSUE TITLE
importing serviceAccount results in serviceaccount and does not recognize as a serviceAccount

### ISSUE THREAD

**Issue by GeoffMillerAZ** [pulumi/pulumi-gcp#1517]
### What happened?

When importing from a terraform state file, a GCP `serviceAccount` resource will try to import as a `serviceaccount` resource. This is just a casing difference but enough to cause it to be recognized as a different type of resource. As a result, it will try to delete the imported `serviceaccount` resource and create a `serviceAccount` resource. Please see the example below for excerpts from my use case.

Modifying the state file manually and importing the stack fixes the problem.

### Example

- `pulumi import --from terraform terraform.tfstate`
- This creates a pulumi import file that I rename to `pulumi-import.json`
- `pulumi import --file pulumi-import.json --protect=false`

```
     Type                                          Name                                          Plan       Info
 +   pulumi:pulumi:Stack                           gcp-bar-dev                                   create     
...
 =   ├─ gcp:serviceaccount:Account                 gke                                           import     
...
```

Select `yes`:

```

     Type                                          Name                                          Status               Info
 +   pulumi:pulumi:Stack                           gcp-forge-exp0-dev                            created (13s)        
...
 =   ├─ gcp:serviceaccount:Account                 gke                                           imported (2s)        
...
```

`pulumi preview --show-sames`

```
     Type                                          Name                                          Plan        Info
     pulumi:pulumi:Stack                           gcp-bar-dev                                          1 message
 +   ├─ components:index:Resources                 fooShape                                      create      
 +   ├─ mynode:gcp:MyNode                          bar                                           create      
...
 +   ├─ mynode:gcp:MyNodeGCP                       foo                                           create      
 +   │  ├─ mynode:gcp:Network                      network                                       create      
...
 +   │  ├─ mynode:gcp:Auth                         auth                                          create      
...
 +   │  │  ├─ gcp:serviceAccount:Account           gke                                           create      
...
 -   ├─ gcp:serviceaccount:Account                 gke                                           delete      
```

- `pulumi stack export --file state.json`
- make the following changes:
  - find    `gcp:serviceaccount/account:Account`
  - replace `gcp:serviceAccount/account:Account`
- `pulumi stack import --file state.json`
- then you can check to see if your changes worked
- `pulumi preview --show-sames`

```
     Type                                          Name                                          Plan       Info
     pulumi:pulumi:Stack                           gcp-bar-dev                                       1 message
 +   ├─ components:index:Resources                 fooShape                                      create     
 +   ├─ mynode:gcp:MyNode                          bar                                           create     
...
 +   ├─ mynode:gcp:MyNodeGCP                       foo                                           create     
 +   │  ├─ mynode:gcp:Network                      network                                       create     
 +   │  ├─ mynode:gcp:Auth                         auth                                          create     
     │  │  ├─ gcp:serviceAccount:Account           gke                                                      [diff: +disabled-project~__defaults,provider]
```

As you can see, after manually fixing the casing error, it recognizes as the same resouce.

### Output of `pulumi about`

```
Output of pulumi about
CLI
Version 3.99.0
Go Version go1.21.5
Go Compiler gc

Plugins
NAME VERSION
gcp 7.2.1
kubernetes 4.5.4
nodejs unknown
random 4.14.0
std 1.4.0
time 0.0.16

Host
OS darwin
Version 14.2.1
Arch arm64

This project is written in nodejs: executable='/usr/local/bin/node' version='v18.18.0'

...
Found no pending operations associated with dev

Backend
Name pulumi.com
URL https://app.pulumi.com/GeoffMillerAZ
User GeoffMillerAZ
Organizations GeoffMillerAZ
Token type personal

Dependencies:
NAME VERSION
@pulumiverse/time 0.0.16
@types/node 14.18.63
typescript 4.9.5
@pulumi/gcp 7.2.1
@pulumi/kubernetes 4.5.4
@pulumi/pulumi 3.95.0
@pulumi/random 4.14.0
@pulumi/std 1.4.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by GeoffMillerAZ** [comment]
related/similar? #922

**Comment by iwahbe** [comment]
Hi @GeoffMillerAZ. Thanks for opening the issue. I think the current import behavior is correct vis a vis the imported resource, since `gcp:serviceAccount/account:Account` is an old alias for `gcp:serviceaccount/account:Account`. Is it possible that `mynode:gcp:Auth` is using an old version of pulumi-gcp?

If so, my guess is that the `pulumi import` is using the wrong version of pulumi-gcp to derive names.

**Comment by GeoffMillerAZ** [comment]
> Hi @GeoffMillerAZ. Thanks for opening the issue. I think the current import behavior is correct vis a vis the imported resource, since `gcp:serviceAccount/account:Account` is an old alias for `gcp:serviceaccount/account:Account`. Is it possible that `mynode:gcp:Auth` is using an old version of pulumi-gcp?
> 
> If so, my guess is that the `pulumi import` is using the wrong version of pulumi-gcp to derive names.

How old of a version are we talking about would make the difference? I have version `@pulumi/gcp 6.66.0`. That was the latest version when I coded this component in September, so it's not that old. I've destroyed everything and put this aside, but I can stand it all back up and test with the latest versions.

**Comment by GeoffMillerAZ** [comment]
Updating appears to be working now. thanks!
