### ISSUE TITLE
Adding label to NodePool config causes replacement

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi-gcp#164]
I had a nodepool configuration with:

```
new gcp.container.NodePool('general', {
      name: 'general',
      location: gcpConfig.require('region'),
      cluster: cluster.id,
      initialNodeCount: 1, // Per zone!!!
      version: config.require('gkeVersion'),
      autoscaling: {
        minNodeCount: 1,
        maxNodeCount: 4
      },
      management: {
        autoRepair: true,
        autoUpgrade: true
      },
      nodeConfig: {
        diskSizeGb: 512,
        machineType: 'n1-standard-1'
      },
    })
  );
```

I then changed it to:

```
new gcp.container.NodePool('general', {
      name: 'general',
      location: gcpConfig.require('region'),
      cluster: cluster.id,
      initialNodeCount: 1, // Per zone!!!
      version: config.require('gkeVersion'),
      autoscaling: {
        minNodeCount: 1,
        maxNodeCount: 4
      },
      management: {
        autoRepair: true,
        autoUpgrade: true
      },
      nodeConfig: {
        diskSizeGb: 512,
        machineType: 'n1-standard-1',
        labels: {
          'node.k8s.linio.com/name': 'general'
        }
      },
    })
  );
```

```
gcp:container:NodePool        cli                  replace     [diff: -maxPodsPerNode,namePrefix,nodeCount,project
 +-  └─ gcp:container:NodePool        web                  replace     [diff: -maxPodsPerNode,namePrefix,nodeCount,project
```

this caused Pulumi to think it needs to be replaced. Which also fails because it tries to create first before deleting.

The expected behavior would be to simply add the new labels. Maybe this isn't possible with GCP? Either way, it should replace properly.

**Comment by stack72** [comment]
Hi @nesl247 	

Thanks for reporting this issue. I am sorry that this is something you are running into. Unfortunately, this is actually following the same behaviour in the upstream terraform provider that we generate the code based off. Their schema looks as follows:

```
"labels": {
				Type:     schema.TypeMap,
				Optional: true,
				ForceNew: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
			},

```

This terraform provider, and thus our code, is generated automatically against the GCP spec. This must be a limitation of the GKE API

I'd love to hear your thoughts on this?

Thanks

Paul

**Comment by nesl247** [comment]
That makes no sense to me, though I understand it's GCP's fault. I'm not sure what their reasoning is for that.

As far as fixing this goes, it appears to be that Pulumi does not properly handle the replace. It is failing because I am overriding the name mangling by specifying a static name. It's not deleting first and then creating.

**Comment by ellismg** [comment]
> It's not deleting first and then creating.

FWIW, you can explicitly set [deleteBeforeReplace](https://pulumi.io/reference/pkg/nodejs/pulumi/pulumi/#CustomResourceOptions-deleteBeforeReplace) on the resource options for your GKE cluster to force Pulumi to delete the resource before creating a new copy.  That does mean that during the update there will be a period of time where the cluster is completely gone.

https://github.com/pulumi/pulumi-terraform/issues/383 is related to the general class of problems where Pulumi in general wants to do create before delete but that doesn't usually work well if the resource is not auto-named.

**Comment by nesl247** [comment]
I think we can close this in favor of that issue then. It’s unfortunate that GCP handles labeling NodePools like this, but it seems it’s s out of Pulimi’s hands. Thanks!

**Comment by stack72** [comment]
Thanks for your understanding on this issue @nesl247
