### ISSUE TITLE
Failed to get regions list failure in previously working scripts

### ISSUE THREAD

**Issue by ddn0** [pulumi/pulumi-gcp#1641]
### What happened?

After upgrading to 7.7.1 (from 7.7.0)  I started seeing the following errors in my pulumi scripts that authenticate via GCP Workload Identity Federation / OIDC:
  
```
pulumi:providers:gcp (default_7_7_1):
    error: rpc error: code = Unknown desc = failed to get regions list: failed to create compute service: google: could not find default credentials. See https://cloud.google.com/docs/authentication/external/set-up-adc for more information
```

I'm guessing this is because the region listing code introduced in https://github.com/pulumi/pulumi-gcp/commit/fa56f090e9bfc960c6a2b7a9a70abb6ec51d89d4 uses application-default credentials instead of possibly configured OIDC ones.

This error goes away if I set `PULUMI_GCP_SKIP_REGION_VALIDATION=true` in my environment.

### Example

To reproduce, run pulumi preview (with gcp:region and gcp:project set) without application default credentials:

```
gcloud auth revoke
GOOGLE_OAUTH_ACCESS_TOKEN=any-dummy-value pulumi preview
```

With 7.7.0, the preview succeeds, and with 7.7.1, the preview fails with the above error message.

### Output of `pulumi about`

```
$ pulumi about
CLI
Version      3.102.0
Go Version   go1.21.6
Go Compiler  gc

Plugins
NAME    VERSION
docker  4.5.1
gcp     7.7.1
python  unknown
random  4.15.1

Host
OS       darwin
Version  13.5.1
Arch     x86_64
```

### Additional context

FWIW, many of my provisioning service accounts do not have the `compute.regions.list` permission so even if the correct authentication pathway were used, the region listing code would still fail with authorization failure.

My preference would be that this region caching code be run more opportunistically: if the principal can fetch the regions, use that information to make better error messages, but if it cannot, do not fail otherwise correctly configured pulumi scripts just to make nicer error messages.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Thanks so much for a detailed report @ddn0 ! #1554 was intended as a usability feature for missing credentials but it looks like we missed testing this with GOOGLE_OAUTH_ACCESS_TOKEN style of authentication. I'll arrange a revert shortly once I can confirm which change causes the problem, and we'll make sure to test Workload Identity Federation / OIDC when reintroducing.
