### ISSUE TITLE
Service Impersonation doesn't work for google beta provider

### ISSUE THREAD

**Issue by sunilrr** [pulumi/pulumi-gcp#1767]
### What happened?

Pulumi doesn't honour the impersonateServiceAccount configuration for google beta provider.

Resources using beta provider fails due to IAM permission.
After analyzing GCP logs, all failures had missing `serviceAccountDelegationInfo` under `authenticationInfo`.

### Example

```python
self.vpc_connector = gcp.vpcaccess.Connector(
            "connector",
            project=self.project.project_id,
            region=args.config.gcp_region,
            ip_cidr_range="10.8.0.0/28",
            max_throughput=300,
            network=self.network.network.name,
            opts=pulumi.ResourceOptions(
                provider=self.google_beta,
                depends_on=[self.vpc_access_api, self.network],
            ),
        )
```

Commenting out `provider=self.google_beta,` uses impersonated service account

### Output of `pulumi about`

CLI
Version      3.107.0
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME       VERSION
command    0.7.0
cp-deploy  0.1.0
gcp        7.11.2
python     unknown
random     4.11.2

Dependencies:
NAME              VERSION
flake8            5.0.4
grpcio-status     1.50.0
isort             5.11.5
mypy              1.0.0
pip               24.0
pulumi-cp-deploy  0.1.0
pytest-cov        3.0.0
setuptools        69.1.0
toml              0.10.2
twine             4.0.2
yapf              0.32.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @sunilrr. Thanks for reporting this issue. Can you please provide an example project so we understand how you are consuming `impersonateServiceAccount`?

**Comment by sunilrr** [comment]
```yaml
config:
  gcp:region: '#{Pulumi.Config.GcpRegion}'
  gcp:zone: '#{Pulumi.Config.GcpZone}'
  gcp:impersonateServiceAccount: '#{Pulumi.Config.ImpersonateServiceAccount}'
```

In my usecase, pulumi is integration with Octopus Deploy. And above configuration is used.

Following Terraform [docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference), tried adding config for gcp-beta/google-beta which had no effect.

As a workaround, we have removed beta provider.

**Comment by mjeffryes** [comment]
Sorry about the confusing docs, the pulumi provider always uses the the "google-beta" configuration of the underlying terraform provider as it provides a superset of the functionality. There is no need to define an explicit `google-beta` provider instance.
