### ISSUE TITLE
Fix `gcp.kms.CryptoKey` documentation to suggest `resource option protect` instead of a lifecycle hook

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi-gcp#1879]
### What happened?

A user brought it to my attention the gcp.kms.CryptoKey resource has the following note 

> Note: CryptoKeys cannot be deleted from Google Cloud Platform. Destroying a provider-managed CryptoKey will remove it from state and delete all CryptoKeyVersions, rendering the key unusable, but will not delete the resource from the project. When the provider destroys these keys, any data previously encrypted with these keys will be irrecoverable. For this reason, it is strongly recommended that you add lifecycle hooks to the resource to prevent accidental destruction.

I believe this is leftover from the bridged TF documentation and should be updated to be the resource option `protect`

### Example

Link to the resource documentation: https://www.pulumi.com/registry/packages/gcp/api-docs/kms/cryptokey/

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @zbuchheit. Thanks for pointing this out.

**Comment by zbuchheit** [comment]
no problem! :) @iwahbe

**Comment by guineveresaenger** [comment]
This sounds like it should be addressed via a patch, unless this is part of a larger pattern across the docs.
