### ISSUE TITLE
Sign certificates by DevOps-tiered CAs

### ISSUE THREAD

**Issue by reith** [pulumi/pulumi-gcp#1880]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I'm trying to create certificates using GCP CA Pools. It seems current `certficateauthority.Certificate` resources only work for Enterprise CAs; I don't get a Pulumi error for DevOps-tiered pools but GCP returns 404. Enterprise CAs cost ten times more than DevOps and they are not appropriate for my use case which is merely to generate client certificates for mTLS. 

Can we have an API for signing certificates by CAs in the DevOps tier?

**Comment by iwahbe** [comment]
Hi @reith. Thanks for opening an issue. This provider is bridged from https://github.com/GoogleCloudPlatform/magic-modules. I suggest you open an issue here https://github.com/hashicorp/terraform-provider-google/issues/new/choose.

**Comment by reith** [comment]
Related upstream ticket: https://github.com/hashicorp/terraform-provider-google/issues/14241
