### ISSUE TITLE
FileAsset for API gateway and APIgee

### ISSUE THREAD

**Issue by tomerslice** [pulumi/pulumi-gcp#1889]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I want to generate openapi file for API gateway or sharedflow config for APIgee.
I can't to that right now with assets, I need to write the files locally.

### Affected area/feature

Unknown.

**Comment by mikhailshilkov** [comment]
Since we haven't heard back, I'll go ahead and close the issue as non-actionable.
