### ISSUE TITLE
iap/webbackendserviceiambinding members documentation is merged into the project section

### ISSUE THREAD

**Issue by simon-brantonhousley-caribou** [pulumi/pulumi-gcp#1895]
File: [themes/default/content/registry/packages/gcp/api-docs/iap/webbackendserviceiambinding/_index.md](https://www.pulumi.com/registry/packages/gcp/api-docs/iap/webbackendserviceiambinding/)

In the documenation for iap/webbackendserviceiambinding, the members documentation is empty and the contents that should be in members has been merged into the project section.
![2024-03-29_16-18](https://github.com/pulumi/pulumi-hugo/assets/96089894/c5ac2d40-4c94-4b3d-b330-bd88e2910944)

**Comment by VenelinMartinov** [comment]
Looks like the same issue affects Bucket IAM binding: https://github.com/pulumi/pulumi-gcp/issues/1920

**Comment by guineveresaenger** [comment]
This was fixed in https://github.com/pulumi/pulumi-gcp/pull/1924 and should render correctly now!
