### ISSUE TITLE
Firebase Support 

### ISSUE THREAD

**Issue by nibtime** [pulumi/pulumi-gcp#201]
Are there any plans for a resource package to manage Firebase services?
I noticed that Firestore is available, although in the context of GCP.

As a application developer I am mostly interested in Firebase, since it offers the easiest way to offer a full-fledged backend without too much hassle and I'd love to be able to manage it with Pulumi.

**Comment by pgavlin** [comment]
Hi @nibtime! It appears that the upstream codebase does not yet support Firebase due to a lack of a Go SDK for managing Firebase services: https://github.com/terraform-providers/terraform-provider-google/issues/2973. We should have support for these services as soon as it is added upstream.

**Comment by jeduden** [comment]
Since https://github.com/terraform-providers/terraform-provider-google-beta/pull/1885 has been merged, is that enough to add firebase support to Pulumi ?

**Comment by kyeshmz** [comment]
If needed, I can create a new issue to track this, but I would like to request the support of this!
