### ISSUE TITLE
Skip Credentials on Pulumi Preview with gcp resources

### ISSUE THREAD

**Issue by wongstein** [pulumi/pulumi-gcp#2014]
It would be nice for some testing use cases to be able to pulumi preview without doing a credential check, like the AWS provider has with AWS_SKIP_CREDENTIALS_VALIDATION

Could also be an environment variable.

**Comment by mikhailshilkov** [comment]
> the AWS provider has with AWS_SKIP_CREDENTIALS_VALIDATION

@wongstein  This doesn't quite work as you describe either. This flag won't enable previews without valid AWS credentials, it's much more focused:

> Skip the credentials validation via the STS API. Useful for AWS API implementations that do not have STS available or implemented.

As @iwahbe mentioned, I don't think it's realistic to support such flag without upstream support in the terraform provider.
