### ISSUE TITLE
Cloud run service requires location property

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi-gcp#203]
When creating a `gcp.cloudrun.Service`, it requires a `location` property. From the little documentation I can find online, this is just the region. This should not be required as it should pull in from `gcp:region`.

**Comment by mikhailshilkov** [comment]
@nesl247 Thanks for the suggestion, it totally makes sense to me. I've created [an issue upstream](https://github.com/terraform-providers/terraform-provider-google/issues/4334), fill free to vote and engage there.

For now, your best bet is to refer to `gcp.config` manually:

``` ts
const cloudRun = new gcp.cloudrun.Service("asd", {
    location: gcp.config.region!,
    metadata: {
        namespace: gcp.config.project!,
    },
    spec: {
        containers: [{
            image: "gcr.io/cloudrun/hello",
        }],
    },
});
```

**Comment by nesl247** [comment]
Thanks for the sample. I actually had no idea about `gcp.config.*` either. I've been doing a `new pulumi.config()` for it.

I've voted on the linked issue. Thanks!

**Comment by mikhailshilkov** [comment]
The upstream issue got closed as "won't fix", so I'll do the same here
