### ISSUE TITLE
Bug in Cloud SQL

### ISSUE THREAD

**Issue by benglewis** [pulumi/pulumi-gcp#2030]
### What happened?

I was trying to use a private IP instance for GCP Cloud SQL. The docs are wrong.

### Example

The docs indicate that the user must pass `ServiceNetworking` instance as a `depends_on` argument, but the code example then doesn't actually show this.

### Output of `pulumi about`

CLI          
Version      3.117.0
Go Version   go1.22.3
Go Compiler  gc

Plugins
KIND      NAME                              VERSION
resource  aws                               6.36.0
resource  aws-native                        0.105.0
resource  azure-native                      2.41.0
resource  command                           0.10.0
resource  gcp                               7.23.0
resource  kubernetes                        4.11.0
resource  kubernetes-cert-manager           0.0.6
resource  postgresql                        3.11.1
resource  pulumi_ceph                       4.0.0
resource  pulumi_cert_manager               4.0.0
resource  pulumi_keda                       4.0.0
resource  pulumi_rabbitmq                   4.0.0
resource  pulumi_rabbitmq_cluster_operator  4.0.0
language  python                            unknown
resource  random                            4.16.1
resource  std                               1.6.2
resource  time                              0.0.17
resource  twingate                          0.0.48

Host     
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in python: executable='/Users/blewis/Programming/infrastructure/.pixi/envs/default/bin/python3' version='3.12.3'

Current Stack: benglewis/mvp/dev

Dependencies:
NAME                              VERSION
beautifulsoup4                    4.12.3
boto3                             1.34.106
Brotli                            1.1.0
clearml                           1.15.1
cryptography                      42.0.7
importlib_resources               6.4.0
pip                               24.0
pkgutil_resolve_name              1.3.10
pulumi_aws                        6.36.0
pulumi_aws_native                 0.105.0
pulumi_azure_native               2.41.0
pulumi_ceph                       4.0.0
pulumi_cert_manager               4.0.0
pulumi_command                    0.10.0
pulumi_gcp                        7.23.0
pulumi_keda                       4.0.0
pulumi_kubernetes_cert_manager    0.0.6
pulumi_postgresql                 3.11.1
pulumi_rabbitmq                   4.0.0
pulumi_rabbitmq_cluster_operator  4.0.0
pulumi_random                     4.16.1
pulumi_std                        1.6.2
pulumi_twingate                   0.0.48
pulumiverse_time                  0.0.17
PySocks                           1.7.1
setuptools                        69.5.1
zipp                              3.17.0

Pulumi locates its logs in /var/folders/4m/d23fk4hx6_38jythgkmtprnr0000gn/T/ by default

### Additional context

It would be so much more helpful if the documentation here indicated that `pulumi-gcp` is derived from the GCP Terraform and that you can reference the Terraform documentation if stuck with documentation issues.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Thanks for taking the time to report this and sorry you had trouble here.

This issue looks like https://github.com/pulumi/pulumi-converter-terraform/issues/126 which should be fixed in the newest version of the converter. I've raised https://github.com/pulumi/pulumi-gcp/pull/2037 to bump that.
