### ISSUE TITLE
Malformed metadata.annotations pulumiLabels.%

### ISSUE THREAD

**Issue by adam-heat1** [pulumi/pulumi-gcp#2050]
### Describe what happened

I am getting the same issue that is defined in [this issue](Malformed metadata.annotations pulumiLabels.%). After seeing this I upgraded my Pulumi packages so I won't hit this in the future but that doesn't get me out of my broken state. How can I edit my state to get out of this loop? Pulumi refresh keeps the empty label inside and I don't want to destroy my state

### Sample program

```
service, err := cloudrun.NewService(ctx, appName, &cloudrun.ServiceArgs{
			Location: pulumi.String(region),
			Project:  pulumi.String(projectID),
			Name:     pulumi.String(appName),
			Template: &cloudrun.ServiceTemplateArgs{
				Spec: &cloudrun.ServiceTemplateSpecArgs{
					Containers: cloudrun.ServiceTemplateSpecContainerArray{
						&cloudrun.ServiceTemplateSpecContainerArgs{
							Image: appImage.RepoDigest,
							Ports: cloudrun.ServiceTemplateSpecContainerPortArray{
								&cloudrun.ServiceTemplateSpecContainerPortArgs{
									Name:          pulumi.String("http1"),
									ContainerPort: pulumi.Int(8080),
								},
							},
						},
					},
					ContainerConcurrency: pulumi.Int(5),
				},
				Metadata: &cloudrun.ServiceTemplateMetadataArgs{
					Annotations: pulumi.StringMap{
						"run.googleapis.com/cloudsql-instances": database.ConnectionName,
					},
				},
			},
			Traffics: cloudrun.ServiceTrafficArray{
				&cloudrun.ServiceTrafficArgs{
					Percent:        pulumi.Int(100),
					LatestRevision: pulumi.Bool(true),
				},
			},
		}, pulumi.DependsOn([]pulumi.Resource{appImage}))
		if err != nil {
			return err
		}

### Log output

```
 Details:
    [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "description": "Malformed metadata.annotations pulumiLabels.%",
            "field": "metadata.annotations"
          }
        ]
      }
    ]
    

### Output of `pulumi about`

pulumi about
CLI
Version      3.116.1
Go Version   go1.22.2
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  docker  4.5.0
resource  gcp     7.23.0
language  go      unknown

Host
OS       darwin
Version  14.3
Arch     x86_64

This project is written in go: executable='/usr/local/bin/go' version='go version go1.22.2 darwin/amd64'

Current Stack: name/project/production

TYPE                                       URN
pulumi:pulumi:Stack                        urn:pulumi:production::project::pulumi:pulumi:Stack::project-production
pulumi:providers:docker                    urn:pulumi:production::project::pulumi:providers:docker::default_4_5_0
pulumi:providers:gcp                       urn:pulumi:production":project::pulumi:providers:gcp::default_7_23_0
gcp:sql/databaseInstance:DatabaseInstance  urn:pulumi:production::project::gcp:sql/databaseInstance:DatabaseInstance::db-instance
docker:index/image:Image                   urn:pulumi:production::project::docker:index/image:Image::fantasy-rust-api
gcp:cloudrun/service:Service               urn:pulumi:production::project::gcp:cloudrun/service:Service::fantasy-rust-api
gcp:cloudscheduler/job:Job                 urn:pulumi:production::projecti::gcp:cloudscheduler/job:Job::updateAdpJob
pulumi:providers:gcp                       urn:pulumi:production::project::pulumi:providers:gcp::default_7_2_1
pulumi:providers:gcp                       urn:pulumi:production::project::pulumi:providers:gcp::default
pulumi:providers:docker                    urn:pulumi:production::project::pulumi:providers:docker::default
gcp:cloudrun/iamMember:IamMember           urn:pulumi:production::project::gcp:cloudrun/iamMember:IamMember::fantasy-rust-api-iam
gcp:cloudrun/domainMapping:DomainMapping   urn:pulumi:production::project::gcp:cloudrun/domainMapping:DomainMapping::api-domain-mapping

Found no pending operations associated with production

Backend
Name           pulumi.com
URL            https://app.pulumi.com/adam-ambrosius
User           name
Organizations  name
Token type     personal

Dependencies:
NAME                                    VERSION
cloud.google.com/go/run                 v1.3.4
dagger.io/dagger                        v0.9.3
github.com/pulumi/pulumi-docker/sdk/v4  v4.5.0
github.com/pulumi/pulumi-gcp/sdk/v7     v7.23.0
github.com/pulumi/pulumi/sdk/v3         v3.114.0

Pulumi locates its logs in by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @adam-heat1 - thank you for filing this issue. You mention there's another issue that describes this behavior, but unfortunately your link is broken - can you let us know which one you were referring to? We should be able to assist you in fixing your stack state.

**Comment by adam-heat1** [comment]
Sorry for the miscopy. Here is the issue. https://github.com/pulumi/pulumi-gcp/issues/1387

**Comment by guineveresaenger** [comment]
Awesome, thank you for the context.

Before we dive in, would you be able to send us a copy of your current stuck stack file, sensitive data removed? It would be the output of `pulumi stack export --file stack.json`. It would help us find out why `refresh` is not working for you.

You have a couple options here. 

- You can delete the service and recreate it. This is of course destructive.
- You can manually edit your stack state to remove the stuck labels. **Warning** this is potentially dangerous. Documentation for stack files is here: https://www.pulumi.com/docs/cli/commands/pulumi_stack_export/

**Comment by adam-heat1** [comment]
@guineveresaenger here is a portion of my output where the labels are.

```json
"outputs": {
          "__meta": "{\"e2b\":{\"create\":1200000000000,\"delete\":1200000000000,\"update\":1200000000000},\"schema_version\":\"2\"}",
          "autogenerateRevisionName": false,
          "id": "locations/us-central1/namespaces//services/",
          "location": "us-central1",
          "metadata": {
            "annotations": {
              "pulumiLabels.%": ""
            },
            "effectiveAnnotations": {
              "pulumiLabels.%": "",
              "run.googleapis.com/client-name": "cloud-console",
              "run.googleapis.com/ingress": "all",
              "run.googleapis.com/ingress-status": "all",
              "run.googleapis.com/operation-id": "e7",
              "serving.knative.dev/creator": "adam@.app",
              "serving.knative.dev/lastModifier": "adam@.app"
            },
            "effectiveLabels": {
              "cloud.googleapis.com/location": "us-central1"
            },
            "generation": 142,
            "labels": {},
            "namespace": "",
            "pulumiLabels": {},
            "resourceVersion": "",
            "selfLink": "/apis/serving.knative.",
            "uid": ""
          },
          "name": "",
          "project": "",
          "statuses": [
            {
              "conditions": [
                {
                  "message": "",
                  "reason": "",
                  "status": "True",
                  "type": "Ready"
                },
                {
                  "message": "",
                  "reason": "",
                  "status": "True",
                  "type": "ConfigurationsReady"
                },
                {
                  "message": "",
                  "reason": "",
                  "status": "True",
                  "type": "RoutesReady"
                }
              ],
              "latestCreatedRevisionName": "-00141-84n",
              "latestReadyRevisionName": "-00141-84n",
              "observedGeneration": 142,
              "traffics": [
                {
                  "latestRevision": true,
                  "percent": 100,
                  "revisionName": "-00141-84n",
                  "tag": "",
                  "url": ""
                }
              ],
              "url": "https://--uc.a.run.app"
            }
          ],
          "template": {
            "metadata": {
              "annotations": {
                "autoscaling.knative.dev/maxScale": "100",
                "run.googleapis.com/cloudsql-instances": ":us-central1:-instance"
              },
              "generation": 0,
              "labels": {
                "run.googleapis.com/startupProbeType": "Default"
              },
              "name": "",
              "namespace": "",
              "resourceVersion": "",
              "selfLink": "",
              "uid": ""
            },
            "spec": {
              "containerConcurrency": 5,
              "containers": [
                {
                  "args": [],
                  "commands": [],
                  "envFroms": [],
                  "envs": [
                  ],
                  "image": "us-centr",
                  "livenessProbe": null,
                  "name": "",
                  "ports": [
                    {
                      "containerPort": 8080,
                      "name": "http1",
                      "protocol": ""
                    }
                  ],
                  "resources": {
                    "limits": {
                      "cpu": "1",
                      "memory": "512Mi"
                    },
                    "requests": {}
                  },
                  "startupProbe": {
                    "failureThreshold": 1,
                    "grpc": null,
                    "httpGet": null,
                    "initialDelaySeconds": 0,
                    "periodSeconds": 240,
                    "tcpSocket": {
                      "port": 8080
                    },
                    "timeoutSeconds": 240
                  },
                  "volumeMounts": [],
                  "workingDir": ""
                }
              ],
              "serviceAccountName": "6940nt.com",
              "servingState": "",
              "timeoutSeconds": 300,
              "volumes": []
            }
          },
          "traffics": [
            {
              "latestRevision": true,
              "percent": 100,
              "revisionName": "",
              "tag": "",
              "url": ""
            }
          ]
        },
```

You can see two spots where there are `"pulumiLabels.%": "",`. How can I safely delete those? I see your second link about exporting the stack but I don't understand how to edit it with that command

**Comment by iwahbe** [comment]
Thanks! We'll take a look.

**Comment by adam-heat1** [comment]
@iwahbe where can I delete that line manually? That is what I was looking to do originally but couldn't find a way to manually update the state.

**Comment by iwahbe** [comment]
To get your state, you do `pulumi state export > mystate.json`. I would then copy the state (making sure to keep a backup in case something goes wrong: `cp mystate.json mystate.json.backup`). You can then edit `mystate.json` (just search for `"pulumiLabels.%": ""`) and run `cat mystate.json | pulumi stack import` to accept the new state.

**Comment by adam-heat1** [comment]
That is exactly what I was looking for. Thanks so much for the help!
