### ISSUE TITLE
deleteDefaultRoutesOnCreate does not work when creating network

### ISSUE THREAD

**Issue by stang** [pulumi/pulumi-gcp#208]
Hi,

I tried to use the [`deleteDefaultRoutesOnCreate`](https://github.com/pulumi/pulumi-gcp/blob/127a243a2b6ea890bb8cbc91ce51440776b27215/sdk/nodejs/compute/network.ts#L146) to create a new VPC network and have its default route deleted but the default route `0.0.0.0/0` for the newly created network is still there.

# Environment
```
pulumi version
v1.0.0-rc.1

pulumi plugin ls
NAME  KIND      VERSION     SIZE   INSTALLED  LAST USED
gcp   resource  1.0.0-rc.1  83 MB  n/a        1 minute ago
```

# How to reproduce
```
new gcp.compute.Network("example", {
  autoCreateSubnetworks: false,
  deleteDefaultRoutesOnCreate: true
});
```

**Comment by pgavlin** [comment]
@stack72 I can't find an issue in the underlying TF provider tracking this. Can you take a look?
