### ISSUE TITLE
SslMode does not exist in type Input<DatabaseInstanceSettingsIpConfiguration>

### ISSUE THREAD

**Issue by cl3nn** [pulumi/pulumi-gcp#2088]
### Describe what happened

I want to change the sslmode of my postgres cloud sql instance, according to the docs this should be posible: https://www.pulumi.com/registry/packages/gcp/api-docs/sql/databaseinstance/#sslmode_nodejs

the problem:  The sslMode property is  not known using the latest gcp plugin (   7.26.0)

### Sample program

                  
the following ipConfiguration for a google cloud sql instance:

                   ipConfiguration: {
                        ipv4Enabled: true,
                        privateNetwork: args.networkId,
                        enablePrivatePathForGoogleCloudServices: true,
                        authorizedNetworks: args.authorizedNetworks,
                        requireSsl: true,
                        sslMode: "ENCRYPTED_ONLY",
                    },

### Log output

    TSError: ⨯ Unable to compile TypeScript:
    ../../packages/database/postgresql.ts(71,25): error TS2322: Type '{ ipv4Enabled: true; privateNetwork: pulumi.Input<string>; enablePrivatePathForGoogleCloudServices: true; authorizedNetworks: gcp.types.input.sql.DatabaseInstanceSettingsIpConfigurationAuthorizedNetwork[]; requireSsl: true; sslMode: string; }' is not assignable to type 'DatabaseInstanceSettingsIpConfiguration | Promise<DatabaseInstanceSettingsIpConfiguration> | OutputInstance<...> | undefined'.
      Object literal may only specify known properties, and 'sslMode' does not exist in type 'Input<DatabaseInstanceSettingsIpConfiguration>'.

### Output of `pulumi about`

CLI          
Version      3.113.0
Go Version   go1.22.2
Go Compiler  gc

Plugins
NAME    VERSION
gcp     7.26.0
nodejs  unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in nodejs: executable=....

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @cl3nn. Thanks for reporting an issue. Can report which version of the @pulumi/gcp SDK you are using. I see the type in our SDK:

https://github.com/pulumi/pulumi-gcp/blob/faff4751a64b86070289008512a7805246545848/sdk/nodejs/types/input.ts#L62744-L62750

**Comment by cl3nn** [comment]
@iwahbe sorry we found the problem... we have a mono repo with npm workspaces...  one of the pulumi projects has a lower gcp sdk version... wich caused to the workspaces setup to use to lower sdk version.
