### ISSUE TITLE
GCP: Major version upgrade in upstream provider

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-gcp#2115]
The upstream gcp provider has announced plans for a major version release in late August 2024. We will need to do our usual set of due diligence to prepare the major version update in this provider and verify there are no significant regressions. 

TF provider announcement: [[Announcement] Upcoming Changes in Version 6.0.0 of the Google Provider· terraform-provider-google/18300](https://github.com/hashicorp/terraform-provider-google/issues/18300)

**Comment by guineveresaenger** [comment]
Closing in favor of https://github.com/pulumi/pulumi-gcp/issues/2290.
