### ISSUE TITLE
gcp.Provider leaks SA private key

### ISSUE THREAD

**Issue by redbaron** [pulumi/pulumi-gcp#214]
when pulumi runs with preconfigured credentials GOOGLE_CREDENTIALS, these are leaked (not marked as a secret) when provider is instantiated explicitly:

```
new gcp.Provider("neteng", {
        project: "anotherProject"
    })
};
```

creates resource in a stack with `credentials` output containing full serviceaccount JSON credentials unencrypted

**Comment by pgavlin** [comment]
Thanks for the report. Until this is fixed, you can avoid leaking these credentials by setting the [`additionalSecretOutputs` property in `ResourceOptions`](https://www.pulumi.com/docs/intro/concepts/programming-model/#additionalsecretoutputs):

```typescript
new gcp.Provider("neteng", {
        project: "anotherProject"
    }, { additionalSecretOutputs: [ "credentials" ] })
};
```

**Comment by mikhailshilkov** [comment]
Tested it today with the code above:

```
export GOOGLE_CREDENTIALS=$(cat ~/.config/gcloud/application_default_credentials.json)
pulumi up
pulumi stack export
```

Credentials are not stored in the state file, encrypted or not. I'll close the issue as fixed.
