### ISSUE TITLE
Create a testing branch for GCP 8.0

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-gcp#2318]
Create a branch to test a prerelease version integrating the upstream major version bump

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-gcp/issues/2290

**Comment by guineveresaenger** [comment]
Draft pull request is here: https://github.com/pulumi/pulumi-gcp/pull/2355

**Comment by guineveresaenger** [comment]
Closed via https://github.com/pulumi/pulumi-gcp/pull/2355.
