### ISSUE TITLE
Remove 0002-Add-nil-checks-for-sql-database-instance-flattening.patch

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-gcp#2319]
History:

This patch was inherited from a fork change committed in https://github.com/pulumi/pulumi-gcp/pull/602, linking to [this fork commit](https://github.com/pulumi/terraform-provider-google-beta/commit/5affe8f5a9f6). It was made to address #599.

To verify this is no longer needed, I created a SQL Database instance and tried to `.get` it, using the current patched provider. This worked as expected. Then I removed the patch and re-built the provider, and it also works as expected. It appears any buggy nil check behavior was fixed in the bridge since, and we can remove this patch.

See also: #1186.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-gcp/issues/2290

**Comment by VenelinMartinov** [comment]
When reproing did you use a partial state .get as in the original repro?

This looks very much like https://github.com/pulumi/pulumi-terraform-bridge/issues/2282, which is still an issue.

**Comment by guineveresaenger** [comment]
Update:

It turns out this patch cannot be removed at this point.

Here's a program to check if the behavior has improved:

```
import * as pulumi from "@pulumi/pulumi";
import * as gcp from "@pulumi/gcp";

// Create a new Google Cloud SQL Database Instance
const instance = new gcp.sql.DatabaseInstance("my-instance", {
    name: "my-instance",
    databaseVersion: "MYSQL_5_7",
    region: "us-central1",
    settings: {
        tier: "db-f1-micro",  // Choose an appropriate tier
        backupConfiguration: {
            enabled: true,
            startTime: "07:00",
        },
    },
    deletionProtection: false
});
//
// const inst = gcp.sql.DatabaseInstance.get(
//     "my-instance-gah",
//     "my-instance",
//     {project: <insert-project-name>}
// );
// export const version = inst.databaseVersion;
```

1. Build a provider without the patch
2. Run `pulumi up` using the local provider
3. Uncomment the `.get` function and re-run `pulumi up`

You should see an error or a success; not a panic.
Importantly, the `{project: "foo"}` line is responsible for this bug.

**Comment by guineveresaenger** [comment]
Closing this issue as wontfix.
