### ISSUE TITLE
Fix and Remove 0008-Remove-duplicative-resource-token.patch

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-gcp#2325]
This patch can be removed if we address the [context for this patch](https://github.com/pulumi/pulumi-gcp/issues/1193).

Given that the only time we can remove this patch is during a major release, where we accept breaking changes, we should probably try to do so at this time.

**Comment by VenelinMartinov** [comment]
@guineveresaenger is this issue not a duplicate of https://github.com/pulumi/pulumi-gcp/issues/1193?

**Comment by guineveresaenger** [comment]
@VenelinMartinov - one is to track the patch in general; this is specifically a sub-issue for #2290. Now that you mention it, it can go either way since we'd close both issues upon removal 🤷‍♀

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-gcp/issues/2290

**Comment by guineveresaenger** [comment]
Re-evaluating this as not release blocking. Patch context: https://github.com/pulumi/pulumi-gcp/issues/1193#issuecomment-2334945649
