### ISSUE TITLE
Remove 0010-Remove-pattern-string-from-compute-forwarding-rules.patch

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-gcp#2326]
Per https://github.com/pulumi/pulumi-gcp/issues/2324, we should be able to remove this patch.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-gcp/issues/2290

**Comment by guineveresaenger** [comment]
Closed via https://github.com/pulumi/pulumi-gcp/pull/2355.
