### ISSUE TITLE
Unable to use 'permission' with ServicePerimeterEgressPolicyEgress

### ISSUE THREAD

**Issue by terekete** [pulumi/pulumi-gcp#2364]
### Describe what happened

Trying to use the permission field the accesscontextmanager.ServicePerimeterEgressPolicyEgress resource.

```
Error: 
pulumi:pulumi:Stack egress-connected-sheets-egress-connected-sheets running
      \e[31mError\e[0m: Property perimission does not exist on 'gcp:accesscontextmanager/ServicePerimeterEgressPolicyEgressToOperationMethodSelector:ServicePerimeterEgressPolicyEgressToOperationMethodSelector'\n
      \   pulumi:pulumi:Stack egress-connected-sheets-egress-connected-sheets running
```

### Sample program

Using Pulumi YAML.

Here is an example of the program:

```yaml
program:
  resources:
    egress_policy:
      properties:
        egressFrom:
          identityType: ANY_IDENTITY
          sources:
          - accessLevel: null
        egressTo:
          operations:
          - methodSelectors:
            - perimission: bigquery.vpcsc.importData
            serviceName: bigquery.googleapis.com
          resources:
          - projects/628550087762
        perimeter: accessPolicies/${access_policy_id}/servicePerimeters/${perimeter_id}
      type: gcp:accesscontextmanager:ServicePerimeterEgressPolicy
  variables:
    access_policy_id: "881392281091"
    perimeter_id: perimeter_main
```

### Log output

message: "failed to run update: exit status 255\ncode: 255\nstdout: Updating (egress-connected-sheets):\n\n
      \   pulumi:pulumi:Stack egress-connected-sheets-egress-connected-sheets running
      \n    pulumi:pulumi:Stack egress-connected-sheets-egress-connected-sheets running
      \e[31mError\e[0m: Property perimission does not exist on 'gcp:accesscontextmanager/ServicePerimeterEgressPolicyEgressToOperationMethodSelector:ServicePerimeterEgressPolicyEgressToOperationMethodSelector'\n
      \   pulumi:pulumi:Stack egress-connected-sheets-egress-connected-sheets running
      \  on Pulumi.yaml line 10:\n    pulumi:pulumi:Stack egress-connected-sheets-egress-connected-sheets
      running   10:         \e[1;4moperations:\e[0m\n    pulumi:pulumi:Stack egress-connected-sheets-egress-connected-sheets
      running   11: \e[1;4m        - methodSelectors:\e[0m\n    pulumi:pulumi:Stack
      egress-connected-sheets-egress-connected-sheets running   12: \e[1;4m          -
      perimission: bigquery.vpcsc.importData\e[0m\n    pulumi:pulumi:Stack egress-connected-sheets-egress-connected-sheets
      running   13: \e[1;4m          serviceName: bigquery.googleapis.com\e[0m\n    pulumi:pulumi:Stack
      egress-connected-sheets-egress-connected-sheets running   14: \e[1;4m        resources:\e[0m\n
      \   pulumi:pulumi:Stack egress-connected-sheets-egress-connected-sheets running
      \  15: \e[1;4m        - projects/628550087766\e[0m\n    pulumi:pulumi:Stack
      egress-connected-sheets-egress-connected-sheets running Cannot assign '{egressFrom:
      {identityType: string, sources: List<{accessLevel: Invalid}>}, egressTo: {operations:
      List<{methodSelectors: List<{perimission: string}>, serviceName: string}>, resources:
      List<string>}, perimeter: string}' to 'gcp:accesscontextmanager/servicePerimeterEgressPolicy:ServicePerimeterEgressPolicy':\n
      \   pulumi:pulumi:Stack egress-connected-sheets-egress-connected-sheets running
      \  egressTo: Cannot assign '{operations: List<{methodSelectors: List<{perimission:
      string}>, serviceName: string}>, resources: List<string>}' to 'gcp:accesscontextmanager/ServicePerimeterEgressPolicyEgressTo:ServicePerimeterEgressPolicyEgressTo':\n
      \   pulumi:pulumi:Stack egress-connected-sheets-egress-connected-sheets running
      \    operations: Cannot assign 'List<{methodSelectors: List<{perimission: string}>,
      serviceName: string}>' to 'List<gcp:accesscontextmanager/ServicePerimeterEgressPolicyEgressToOperation:ServicePerimeterEgressPolicyEgressToOperation>':\n
      \   pulumi:pulumi:Stack egress-connected-sheets-egress-connected-sheets running
      \      Cannot assign '{methodSelectors: List<{perimission: string}>, serviceName:
      string}' to 'gcp:accesscontextmanager/ServicePerimeterEgressPolicyEgressToOperation:ServicePerimeterEgressPolicyEgressToOperation':\n
      \   pulumi:pulumi:Stack egress-connected-sheets-egress-connected-sheets running
      \        methodSelectors: Cannot assign 'List<{perimission: string}>' to 'List<gcp:accesscontextmanager/ServicePerimeterEgressPolicyEgressToOperationMethodSelector:ServicePerimeterEgressPolicyEgressToOperationMethodSelector>':\n
      \   pulumi:pulumi:Stack egress-connected-sheets-egress-connected-sheets running
      \          Cannot assign '{perimission: string}' to 'gcp:accesscontextmanager/ServicePerimeterEgressPolicyEgressToOperationMethodSelector:ServicePerimeterEgressPolicyEgressToOperationMethodSelector':\n
      \   pulumi:pulumi:Stack egress-connected-sheets-egress-connected-sheets running
      \            Existing properties are: permission, method\n    pulumi:pulumi:Stack
      egress-connected-sheets-egress-connected-sheets  15 messages\nDiagnostics:\n
      \ pulumi:pulumi:Stack (egress-connected-sheets-egress-connected-sheets):\n    \e[31mError\e[0m:
      Property perimission does not exist on 'gcp:accesscontextmanager/ServicePerimeterEgressPolicyEgressToOperationMethodSelector:ServicePerimeterEgressPolicyEgressToOperationMethodSelector'\n
      \     on Pulumi.yaml line 10:\n      10:         \e[1;4moperations:\e[0m\n      11:
      \e[1;4m        - methodSelectors:\e[0m\n      12: \e[1;4m          - perimission:
      bigquery.vpcsc.importData\e[0m\n      13: \e[1;4m          serviceName: bigquery.googleapis.com\e[0m\n
      \     14: \e[1;4m        resources:\e[0m\n      15: \e[1;4m        - projects/628550087766\e[0m\n
      \   Cannot assign '{egressFrom: {identityType: string, sources: List<{accessLevel:
      Invalid}>}, egressTo: {operations: List<{methodSelectors: List<{perimission:
      string}>, serviceName: string}>, resources: List<string>}, perimeter: string}'
      to 'gcp:accesscontextmanager/servicePerimeterEgressPolicy:ServicePerimeterEgressPolicy':\n
      \     egressTo: Cannot assign '{operations: List<{methodSelectors: List<{perimission:
      string}>, serviceName: string}>, resources: List<string>}' to 'gcp:accesscontextmanager/ServicePerimeterEgressPolicyEgressTo:ServicePerimeterEgressPolicyEgressTo':\n
      \       operations: Cannot assign 'List<{methodSelectors: List<{perimission:
      string}>, serviceName: string}>' to 'List<gcp:accesscontextmanager/ServicePerimeterEgressPolicyEgressToOperation:ServicePerimeterEgressPolicyEgressToOperation>':\n
      \         Cannot assign '{methodSelectors: List<{perimission: string}>, serviceName:
      string}' to 'gcp:accesscontextmanager/ServicePerimeterEgressPolicyEgressToOperation:ServicePerimeterEgressPolicyEgressToOperation':\n
      \           methodSelectors: Cannot assign 'List<{perimission: string}>' to
      'List<gcp:accesscontextmanager/ServicePerimeterEgressPolicyEgressToOperationMethodSelector:ServicePerimeterEgressPolicyEgressToOperationMethodSelector>':\n
      \             Cannot assign '{perimission: string}' to 'gcp:accesscontextmanager/ServicePerimeterEgressPolicyEgressToOperationMethodSelector:ServicePerimeterEgressPolicyEgressToOperationMethodSelector':\n
      \               Existing properties are: permission, method\n\nResources:\n
      \   1 unchanged\n\nDuration: 1s\n\n\nstderr: \n"

### Affected Resource(s)

Resource: accesscontextmanager.ServicePerimeterEgressPolicyEgress
Specific place it fails: accesscontextmanager.ServicePerimeterEgressPolicyEgressToOperationMethodSelector when using the permission field

### Output of `pulumi about`

NA

### Additional context

This permission field does work in terraform. We are trying to switch some infrastructure from Terraform to Pulumi.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Hey @terekete, I think you have a typo there: `perimission` - you probably meant `permission` instead.
