### ISSUE TITLE
kms.CryptoKey causes 404 due to over-escaping in URL

### ISSUE THREAD

**Issue by daveio** [pulumi/pulumi-gcp#237]
I'm using TypeScript.

`kms.CryptoKey` resources can't be created. It looks like URL generation is the issue; see below and note

`/v1/REDACTED-abcabc/cryptoKeys?alt=json&amp;cryptoKeyId=REDACTED-defdef`

which should probably be

`/v1/REDACTED-abcabc/cryptoKeys?alt=json&cryptoKeyId=REDACTED-defdef`

```
     Type                      Name                Status                  Info
     pulumi:pulumi:Stack       REDACTED     **failed**              1 error
 +   ├─ gcp:bigquery:Dataset   REDACTED   created
 +   ├─ gcp:kms:CryptoKey      REDACTED  **creating failed**     1 error
 +   └─ gcp:compute:RouterNat  REDACTED         created

Diagnostics:
  gcp:kms:CryptoKey (REDACTED):
    error: Plan apply failed: Error creating CryptoKey: googleapi: got HTTP response code 404 with body: 
      [snipped]
      <p>The requested URL <code>/v1/REDACTED-abcabc/cryptoKeys?alt=json&amp;cryptoKeyId=REDACTED-defdef</code> was not found on this server.  <ins>That’s all we know.</ins>

  pulumi:pulumi:Stack (REDACTED):
    error: update failed
```

**Comment by daveio** [comment]
Just to update: this issue is still present in 1.4.0 (of both the pulumi CLI and @pulumi/gcp).

**Comment by clstokes** [comment]
@daveio I'm not able to reproduce this. Can you provide the code you're using that causes this error?

This code works for me:
```typescript
import * as gcp from "@pulumi/gcp";

const keyring = new gcp.kms.KeyRing("keyring", {
    location: "global",
});
const exampleKey = new gcp.kms.CryptoKey("example-key", {
    keyRing: keyring.selfLink,
    rotationPeriod: "100000s",
});
```

**Comment by daveio** [comment]
ack. testing your code, will respond in the next few minutes.

**Comment by daveio** [comment]
@clstokes I think we've got the bug located.

`keyRing: keyring.selfLink` works.
`keyRing: keyring.name` doesn't but should.

That gives me a workaround, thanks.

While I've got you, do you know if there's a way to define terraform-like lifecycle rules (prevent_destroy in particular) through pulumi?

**Comment by daveio** [comment]
is Resource(name "", definition {}, options { protect: true }) the right choice for that?

**Comment by mikhailshilkov** [comment]
The [docs](https://www.pulumi.com/registry/packages/gcp/api-docs/kms/cryptokey/#keyring_nodejs) say explicitly that `keyRing` should be a full link:

> keyRing: The KeyRing that this key belongs to. Format: 'projects/{{project}}/locations/{{location}}/keyRings/{{keyRing}}'.

I'll close as by design.
