### ISSUE TITLE
Permadiff in pulumiLabels and effectiveLabels with empty labels for `gcp:container:Cluster`

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi-gcp#2395]
### Describe what happened

Similar behavior to https://github.com/pulumi/pulumi-gcp/issues/2372

A user reported seeing a diff in effectiveLabels/pulumiLabels under 8.2.0
```
gcp:container:Cluster gke-cluster  update [diff: ~effectiveLabels,pulumiLabels]
```

### Sample program

TODO

### Output of `pulumi about`

gcp:container:Cluster

### Additional context

The previous issue for the other resources like bucket and kms key are fine now, seems only gcp:container:Cluster remains problematic

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hmmm. @zbuchheit please let us know as soon as you have a repro.

**Comment by VenelinMartinov** [comment]
The resource has an overloaded `labels` field: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster

`labels` is used as a Kubernetes property and `resource_labels` are the GCP labels.

I suspect that https://github.com/pulumi/pulumi-gcp/commit/f8d6d5148205986960004f3f955dd961e23a1115#diff-6138ca86ad57734e61bf634852d39bf6930909a8055a810473adda8e591c7497 does not handle that case.

**Comment by iwahbe** [comment]
It does not. I'm guessing we will need to special case this resource.

**Comment by VenelinMartinov** [comment]
Couldn't repro so far:

```
import * as pulumi from "@pulumi/pulumi";
import * as gcp from "@pulumi/gcp";

const _default = new gcp.serviceaccount.Account("default", {
  accountId: "service-account-id-2",
  displayName: "Service Account",
});

const primary = new gcp.container.Cluster("primary", {
  name: "marcellus-wallace",
  location: "us-central1-a",
  initialNodeCount: 3,
  deletionProtection: false,
  nodeConfig: {
    serviceAccount: _default.email,
    oauthScopes: ["https://www.googleapis.com/auth/cloud-platform"],
    resourceLabels: {
      foo: "bar",
      empty: "",
    },
  },
});

```

produces no diff, unlike with https://github.com/pulumi/pulumi-gcp/issues/2372

**Comment by VenelinMartinov** [comment]
Ok, the repro is with `labels` actually:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as gcp from "@pulumi/gcp";

const _default = new gcp.serviceaccount.Account("default", {
  accountId: "service-account-id-2",
  displayName: "Service Account",
});

const primary = new gcp.container.Cluster("primary", {
  name: "marcellus-wallace",
  location: "us-central1-a",
  initialNodeCount: 3,
  deletionProtection: false,
  nodeConfig: {
    serviceAccount: _default.email,
    oauthScopes: ["https://www.googleapis.com/auth/cloud-platform"],
    labels: {
      foo: "bar",
      empty: "",
    },
  },
});

```

**Comment by iwahbe** [comment]
@VenelinMartinov I am unable to reproduce the problem on v8.2.0 with the above program.[^1]

[^1]: I changed `id-2` to `id-3`, but I don't think that will be material.

**Comment by VenelinMartinov** [comment]
Yeah, it looks like i was using `7.38.0` - `pulumi new` still gives v7.

**Comment by zbuchheit** [comment]
Happening via Go MLC will attempt a repro shortly

**Comment by zbuchheit** [comment]
the following repros for me on 8.2.0, it appears the field causing it is `resourceLabels`

<details><summary>Code Repro</summary>

```ts
import * as gcp from "@pulumi/gcp";

const serviceAccount = new gcp.serviceaccount.Account(
  "zbuchheit-service-account",
  {
    accountId: "zbuchheit-service-account",
    displayName: "zbuchheit-service-account",
  }
);

const cluster = new gcp.container.Cluster("zbuchheit-cluster", {
  name: "zbuchheit-cluster",
  initialNodeCount: 1,
  location: "us-west2",
  nodeConfig: {
    machineType: "e2-medium",
    oauthScopes: ["https://www.googleapis.com/auth/cloud-platform"],
    serviceAccount: serviceAccount.email,
  },
  resourceLabels: {
    environment: "dev",
    test: "",
  },
  deletionProtection: false,
});
```
</details>

**Comment by VenelinMartinov** [comment]
I've confirmed @zbuchheit 's repro also works for me with 8.2.0 - will investigate.
