### ISSUE TITLE
Re-creating materialized view fails (gcp.bigquery.Table)

### ISSUE THREAD

**Issue by brent-statsig** [pulumi/pulumi-gcp#2491]
### Describe what happened

package.json
```
"dependencies": {
    "@pulumi/gcp": "^8.3.1",
    "@pulumi/pulumi": "^3.112.0",
  }
```

Updating a materialize view in bigquery triggers a replacement, that fails, because the table already exists in bigquery.

### Sample program

- Create a bigquery table (gcp.bigquery.Table resource) with a materialized view
- `pulumi up`
- Update the SQL defining the materialized view
- error

### Log output

```
error: 1 error occurred:
    	* googleapi: Error 409: Already Exists: Table my-project:my-source.my-materialized-table, duplicate
    	*
```

### Output of `pulumi about`

```
pulumi about
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
Enter your passphrase to unlock config/secrets
CLI
Version      3.119.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  gcp     8.3.1
resource  gcp     8.2.0
resource  gcp     7.18.0
language  nodejs  unknown

Host
OS       darwin
Version  13.0
Arch     arm64

This project is written in nodejs: executable='/Users/brentechols/.nvm/versions/node/v20.11.1/bin/node' version='v20.11.1'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by brent-statsig** [comment]
Oh - I figured out the issue, `deleteBeforeReplace` needs to be enabled. This feels very unintuitive though, especially since so many GCP resources are globally unique by resource id, and will run into this problem. Especially with things like tables/datasets/etc, which will be referenced by their name external to pulumi, there is no "uptime" friendly way to do a replace.

Can these resources be changed to have `deleteBeforeReplace` be defaulted to true?

**Comment by VenelinMartinov** [comment]
Hey @brent-statsig, thanks for reporting and sorry you've hit this.

Glad you found a workaround, that seems like the right way to go about it. Unfortunately, you've hit a bit of a corner case with the pulumi resource model: https://github.com/pulumi/pulumi/issues/918

I'll look into adding the `deleteBeforeReplace` by default into the provider as that does help with most of these cases.
