### ISSUE TITLE
Google Cloud Registry support?

### ISSUE THREAD

**Issue by coffenbacher** [pulumi/pulumi-gcp#260]
I was looking through the Pulumi docs and I found this for AWS:
```
image: awsx.ecs.Image.fromPath("nginx", "./app"),
```

Is there an equivalent for GCR (gcr.io) images? I wasn't able to find one.

**Comment by pgavlin** [comment]
> Is there an equivalent for GCR (gcr.io) images? I wasn't able to find one.

There isn't a higher-level component for this in our GCP package, no. Under the covers, though, I believe this is just using `@pulumi/docker` and AWS ECR. I think you could achieve the same effect using `@pulumi/docker` and https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/gcp/container/#getRegistryRepository .

**Comment by coffenbacher** [comment]
Thanks @pgavlin , that ended up working fine for me.
