### ISSUE TITLE
ignore_changes not working with gcp.compute.NetworkEndpointGroup.get

### ISSUE THREAD

**Issue by emirozmen07** [pulumi/pulumi-gcp#2631]
### Describe what happened

The `ignore_changes` not working with the `gcp.compute.NetworkEndpointGroup.get` function

### Sample program

1. Create a NEG with pulumi. And connect it to the related backend pod services.
2. Make changes in NEG without pulumi.
3. Try to get the NEG with pulumi.
4. Ignore changes will not work and it will detect all changes anyway.

```
import pulumi_gcp as gcp        

gcp.compute.NetworkEndpointGroup.get(resource_name=internal_neg_name,  id=internal_neg_id, 
                  opts=pulumi.ResourceOptions(ignore_changes=["*"])
```

### Affected Resource(s)

gcp.compute.NetworkEndpointGroup.get

### Output of `pulumi about`

```
CLI          
Version      3.136.1
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  docker      4.5.5
resource  gcp         7.38.0
resource  kubernetes  4.17.1
resource  postgresql  3.11.3
language  python      3.136.1
resource  random      4.16.4

Host     
OS       darwin
Version  14.5
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Hey @emirozmen07, thanks for reporting the issue.

Unfortunately, the way ignore changes works is that it only effects the inputs to a resource, not the outputs: https://www.pulumi.com/docs/iac/concepts/options/ignorechanges/ In your case, for `.get` methods, the changes are only to the outputs, so these can not be ignored by ignoreChanges.

What are you trying to achieve here? What changes are you trying to ignore and why are they impacting your program?
