### ISSUE TITLE
preview failed gcp:container:Cluster timeout

### ISSUE THREAD

**Issue by aexei** [pulumi/pulumi-gcp#267]
### Problem description

I created a stack at GCP and implemented a ci/cd pipeline with Gitlab.

Every time the runner fails with a timeout. Tested the script on my mac and it works perfectly.

My [gitlab-ci.yml](https://pastebin.com/qXY3ECFr) is attached.

### Errors & Logs

`Diagnostics:
      pulumi:pulumi:Stack (n1000-10-staging):
        error: preview failed
      gcp:container:Cluster (gke-cluster):
        error: Preview failed: refreshing urn:pulumi:staging::XXX::gcp:container/cluster:Cluster::gke-cluster: Error reading Container Cluster "gke-cluster-XXX": Get https://container.googleapis.com/v1beta1/projects/XXX/locations/europe-west3/clusters/gke-cluster-XXX?alt=json&prettyPrint=false: Get http://XXX.XXX.XXX.XXX/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fndev.clouddns.readwrite%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control: dial tcpXXX.XXX.XXX.XXX:80: i/o timeout`

**Comment by mikhailshilkov** [comment]
This issue is 4 years old and contains no repro. Nobody has commented on it ever since. I don't think it's actionable for us. I'll assume it was some configuration issue, or the underlying issue has been fixed since.
