### ISSUE TITLE
Cannot determine zone: set in this resource, or set provider-level zone

### ISSUE THREAD

**Issue by hermanbanken** [pulumi/pulumi-gcp#269]
```typescript
new gcp.compute.InstanceFromTemplate(`myinstance`, {
		sourceInstanceTemplate: "mytemplate",
		machineType: "n1-standard-1",
		zone: "europe-west4-a",
		project: "myproject",
	}, {
		import: "https://www.googleapis.com/compute/v1/projects/myproject/zones/europe-west4-a/instances/myinstance-1",
	});
```

fails with 

```
gcp:compute:InstanceFromTemplate (myinstance):
  error: Preview failed: refreshing urn:pulumi:mystack::redacted::gcp:compute/instanceFromTemplate:InstanceFromTemplate::myinstance:
  Cannot determine zone: set in this resource, or set provider-level zone.
```

The zone is set, the project is set. The import contains the full url which is compatible with the [format](https://github.com/terraform-providers/terraform-provider-google/blob/75417ae47d046fef2202be836ee3846c7e37e18e/google/field_helpers.go#L162-L165) for [ParseInstanceFieldValue](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/field_helpers.go#L67-L69).

I want to have resources in different zones, so I can not specify the zone in the provider. How should I proceed with this?

I'm using @pulumi/gcp@2.1.0 (had the same error on @pulumi/gcp@1.9.0).

**Comment by hermanbanken** [comment]
Is it possible that gcp.compute.InstanceFromTemplate can not be imported, but gcp.compute.Instance can?

**Comment by hermanbanken** [comment]
I can confirm that I can import the instance that I tried to import with `gcp.compute.InstanceFromTemplate` using `gcp.compute.Instance`. However, the original resource is definitely created using a template. Is the import logic of InstanceFromTemplate stubbed out?

**Comment by leezen** [comment]
I'll have to look into specifically the InstanceFromTemplate logic. Separately, you should be able to have multiple providers, e.g. `new gcp.Provider('europe-provider', { project: 'xxx', zone: 'europe-west4-a', ...})`

**Comment by mjeffryes** [comment]
Closing as stale given the age of the last report (and the fact that there appear to be multiple workarounds in the discussion. However, if you are still experiencing this problem, please let us know and we can take another look!
