### ISSUE TITLE
gcp.serviceAccount.Key.privateKey should be treated as a secret

### ISSUE THREAD

**Issue by theneva** [pulumi/pulumi-gcp#280]
Hi! :wave:

I'm pretty sure this is the right place to report it, but please direct me elsewhere if I'm wrong :smile:

I use TypeScript, Pulumi 1.9.1, and `@pulumi/gcp` 2.4.0.

I created a service account key (`gcp.serviceAccount.Key`), and then created a Kubernetes Secret from that key's `privateKey` property.

https://github.com/pulumi/pulumi-gcp/blob/19ca6d1ab783ee3fc18d3c721573a469d45179fe/sdk/nodejs/serviceAccount/key.ts#L56

In the output, I noticed that the `privateKey` property, while base64 encoded, is not marked as a `secret` value (i.e., `pulumi.secret(theProperty)`.

I believe this value should be treated as a Secret so as to not show up unintentionally in build logs etc.

I'm not sure how it's common to mark specific properties as `secret`, hence the issue rather than a PR.

**Comment by farcaller** [comment]
Stumbled on this and it seems to me it's not a question but rather a bug. Reading the documentation

> With 0.17.11 of Pulumi, we now have Output<T> track if it contains secret data. If it does, we ensure that the data is encrypted before we store it in the state file.

The private key is clearly secret material and as such it should be encrypted.

**Comment by leezen** [comment]
You're totally right and I think I misread the original post. For now, you can workaround this with `{ additionalSecretOutputs: [ "privateKey" ] }`(see also: https://www.pulumi.com/docs/intro/concepts/programming-model/#additionalsecretoutputs)

**Comment by farcaller** [comment]
Thanks, a workaround was much appreciated!

**Comment by mikhailshilkov** [comment]
Tested it with 6.62.0 and the program

```
import * as gcp from "@pulumi/gcp";

const key = new gcp.serviceaccount.Key("test", {
  serviceAccountId: "some-account-id@some-project.iam.gserviceaccount.com",
});

export const a = key.privateKey;
```

and got a secret back:

```
     Type                       Name        Status           
 +   pulumi:pulumi:Stack        gcp-ts-dev  created (7s)     
 +   └─ gcp:serviceAccount:Key  test        created (2s)     


Outputs:
    a: [secret]
```

also manually verified that the secret flag is set in our schema.
