### ISSUE TITLE
Unable to create VPC-native GKE cluster (alias IP)

### ISSUE THREAD

**Issue by VojtechVitek** [pulumi/pulumi-gcp#286]
Hi,
I'm trying to create a VPC-native GKE cluster ([alias IP](https://cloud.google.com/vpc/docs/alias-ip)). However, it looks like I can't use the latest fields on the `ClusterIpAllocationPolicy` in order to do that.

```
{
  "useIpAliases": boolean,
  "createSubnetwork": boolean,
}
```
([see latest API](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#ipallocationpolicy))

vs.

https://github.com/pulumi/pulumi-gcp/blob/84d6e20f6c9f3bf13923b1b6467b79ae75630e4b/sdk/nodejs/types/input.ts#L2344-L2349

I realize that the above code is generated automatically via Terraform bridge. But I'm not really sure if the upstream Terraform already have those changes.. and how could I trigger the update process.

Can you please advice how can I regenerate the code with latest fields?
Or is there a timeline for a new SDK release?

I'm pretty new to Pulumi, so thanks for your patience.

Best,
Vojtech

**Comment by VojtechVitek** [comment]
Note to self:

```
Diagnostics:
  gcp:container:Cluster (dev1):
    error: gcp:container/cluster:Cluster resource 'dev1' has a problem: "ip_allocation_policy.0.use_ip_aliases": [REMOVED] This field is removed as of 3.0.0. If previously set to true, remove it from your config. If false, remove it.
    error: gcp:container/cluster:Cluster resource 'dev1' has a problem: "ip_allocation_policy.0.create_subnetwork": [REMOVED] This field is removed as of 3.0.0. Define an explicit google_compute_subnetwork and use subnetwork instead.
```

Looks like the two fields were actually removed from Terraform. https://github.com/terraform-providers/terraform-provider-google/issues/5154

**Comment by VojtechVitek** [comment]
I think I figured it out based on https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html#use_ip_aliases-is-now-required-on-block-google_container_cluster-ip_allocation_policy

The following ipAllocationPolicy creates VPC-native GKE cluster successfully. Uff.
```ts
  ipAllocationPolicy: {
    clusterIpv4CidrBlock: "10.0.0.0/16",
    servicesIpv4CidrBlock: "10.1.0.0/16",
  },
```


Please, feel free to close this issue. However, I'd appreciate any further pointers at how does the Terraform bridge work and how often do you guys regenerate it. I believe some basic info about this could be useful at the README.md of this repository. Thoughts?

Thank you,
Vojtech

**Comment by robertvanhoesel** [comment]
@VojtechVitek Just an fyi which I discovered today by looking at [Googles API docs on Ip Allocation](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#Cluster.IPAllocationPolicy) that you can set these values to empty strings to get the exact behavior before this release (Google picking the ranges for you).

**Comment by mikhailshilkov** [comment]
[ipAllocationPolicy](https://www.pulumi.com/registry/packages/gcp/api-docs/container/cluster/#ipallocationpolicy_nodejs) is available since a long time. Closing this issue as fixed.
