### ISSUE TITLE
Cannot create pubsub topic when authenticating with a serviceaccount

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi-gcp#292]
In our CI process we login via `gcloud auth activate-service-account --key-file=/gcp-credentials.json`. However, we are not able to perform CRUD operations on Pub/Sub topics.

We end up with the error `error: Error creating Topic: googleapi: Error 403: Request had insufficient authentication scopes.`

**Comment by leezen** [comment]
Any chance it's using KMS, in which case, you also need the roles/cloudkms.cryptoKeyEncrypterDecrypter permission on the service account?

**Comment by nesl247** [comment]
The service account has `roles/owner`, would that not be enough?

**Comment by leezen** [comment]
Sorry, I'm not a GCP expert, so I don't know if `roles/owner` would be enough. I assume you validated that you could `gcloud pubsub topics create` with the service account auth?

Another thought is that pubsub is not enabled for that project? e.g. `gcloud services enable pubsub.googleapis.com`

**Comment by nesl247** [comment]
It's definitely enabled because I run it with my account on my machine without issue. I'll have to double check, but I do recall testing it out and it worked with using `gcloud` directly, but I'm not 100% certain at this point. I meant to open up this ticket a while ago.

**Comment by nesl247** [comment]
Ok, I verified that it works just fine. I did discover a little bit of information though. I got a new computer the other day and so I had to login to gcloud through the SDK again. When I ran pulumi this morning for a project with pub/sub, it errored out because the application default credentials weren't set. I had only logged in with gcloud.

I am wondering if pulumi is for some reason requiring the application default credentials, and maybe that isn't configured when using `activate-service-account`?

**Comment by leezen** [comment]
If you want to use that particular credentials file, you should be able to do it with setting the env var `GOOGLE_CLOUD_KEYFILE_JSON=<path to key file>` -- please see the section on configuration in https://www.pulumi.com/docs/intro/cloud-providers/gcp/

Closing for now, but please feel free to re-open if the above didn't answer your question.
