### ISSUE TITLE
`pulumi plugin install resource gcp` is super slow

### ISSUE THREAD

**Issue by remorses** [pulumi/pulumi-gcp#299]
When i run the command `pulumi plugin install resource gcp` it takes about 14 minutes to download the plugin, as you can see below the estimated time is 13 minutes
```
❯ pulumi plugin install resource gcp 2.8.0
[resource plugin gcp-2.8.0] installing
Downloading plugin: 1.44 MiB / 29.55 MiB [=>--------------------]   4.88% 13m51s
```

I am in italy and have a good internet connection, while downloading i was at 70 Mb/s

![Schermata 2020-03-15 alle 21 53 01](https://user-images.githubusercontent.com/31321188/76710381-5f541780-6707-11ea-8f00-ea13f47d8a37.png)

**Comment by remorses** [comment]
Now it downloads again in about 6 seconds
However it would be cool to know the cause of the issue.

**Comment by lukehoban** [comment]
These plugins are currently served from an API running in us-west-2, and notably that API does not currently have a CDN in front of it.  That is likely the reason for the poor performance you saw, and is something we are working on improving.

**Comment by remorses** [comment]
but now it is running fast again, is it because it has been cached?

**Comment by lukehoban** [comment]
It's hard to say.  With this setup (without global distribution and without a CDN) performance is going to be very dependent on Internet routing.  Serving from a CDN will provide more consistent (and better) performance.

**Comment by muhajirdev** [comment]
I am also having the same issue with aws

```
[resource plugin aws-1.29.0] installing
Downloading plugin: 332.22 KiB / 64.56 MiB [>-----------------]   0.50% 1h51m15s
```

**Comment by codedevote** [comment]
I am experiencing the same issue. It is really annoying if you have to wait for an hour until a plugin is downloaded. That sums up, if you need more than one plugin :-(

**Comment by lukehoban** [comment]
We're actively working on some improvements to this in our backend infrastructure.  Expecting to have some significant improvements to performance here in the next few weeks.

**Comment by actraiser** [comment]
I am experiencing very low download speeds for the plugin in the last days. The download happens during the CI/CD-Pipeline execution on GitLab. Since this is a recurring process, it is not just annoying but slows down each deployments by magnitudes. Is there any workaround / command line flag to somehow speed up the process?

![Bildschirmfoto 2020-10-05 um 06 20 07](https://user-images.githubusercontent.com/5455/95040113-02d03e00-06d3-11eb-9d48-abf92f0eb8f1.png)

**Comment by leezen** [comment]
Closing this out as since mid-May, we've been serving plugins via Cloudfront CDN.
