### ISSUE TITLE
Location for Cloud Run IAM policy is required

### ISSUE THREAD

**Issue by floyd-may** [pulumi/pulumi-gcp#301]
The `Location` property of `Pulumi.Gcp.CloudRun.IamPolicyArgs` should be marked required. Without it, the provider gets 404s when attempting to read or write the policy.

**Comment by leezen** [comment]
@pgavlin could this be a bug in how we generate the type information?

**Comment by pgavlin** [comment]
No: this property is not listed as required in the upstream TF schema. https://github.com/terraform-providers/terraform-provider-google/blob/master/google/iam_cloud_run_service.go#L31-L36

**Comment by pgavlin** [comment]
I think this property is optional because it can be inferred from `project`, but I'm not sure. @stack72 any ideas, or should we open a bug in the TF provider?

Regardless, I am going to close this issue--if there is an upstream bug here, we'll use that to track.

**Comment by floyd-may** [comment]
Respectfully, I'd appreciate if this were left open, as it affects the experience with Pulumi.Gcp. I had to do a fair bit of reverse-engineering just to understand what was wrong and how to fix it. I'm experimenting with Pulumi because I was dissatisfied with my experience with Terraform. If SOP is "not our bug" anytime the underlying Terraform provider doesn't do the right thing, then that forces me, as an end-user, to need to care about the presence of the underlying providers, making Pulumi an intentionally leaky abstraction that forces me to understand both it and Terraform. It really weakens the value proposition of Pulumi over Terraform, in my _humble_ opinion.

**Comment by lukehoban** [comment]
Just want to clarify that this is actually a by-design part of the API here.

The `location` for many resources in the Pulumi GCP provider can be provided in one of two ways:
1. As a property on the resource (`location: `)
2. As provide configuration (`gcp:location`)

Neither of these is required.  Both of these are optional.  But at least one of them must be provided.

Because of this, the property on the resource cannot be marked as "required", as it is not required when the provider level configuration has been provided.

**Comment by floyd-may** [comment]
Hi @lukehoban I appreciate the clarification. It seems that the absence of both is detectable inside Pulumi (i.e. not Terraform)? If I omit the location in both places, rather than getting an error message, I get a low-level error that doesn't say anything to the effect of "you didn't specify the location for this resource".

Is it not possible for Pulumi, for those resources that need a location specified, to produce a helpful error message guiding the user to specify the location?

**Comment by lukehoban** [comment]
@floyd-may What exactly is the error message you see?  It does sound like this boils down to reporting a better error - which definitely should be possible.

**Comment by floyd-may** [comment]
Sure thing @lukehoban! I've sanitized the error below and replaced my project identifier with `<gce-project-id>` and my cloud run service name with `<cloudrun-service-name>`. I had to go spelunking through terraform's source code to figure out what was wrong with that URL. The double slash between `location` and `services` clued me in, but it was most certainly a yak-shaving exercise to figure out what the source of this error was.
```
Error setting IAM policy for cloudrun service "v1/projects/<gce-project-id>/locations//services/<cloudrun-service-name>": googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/v1/projects/<gce-project-id>/locations//services/<cloudrun-service-name>:setIamPolicy</code> was not found on this server.  <ins>That’s all we know.</ins>
```

The relevant code for the Cloud Run IAM Policy is here:
```csharp
using cloudrun = Pulumi.Gcp.CloudRun;
// (snip)

    // service is a cloudrun.Service here.
    var policy = new cloudrun.IamPolicy("workflow-sync", new cloudrun.IamPolicyArgs {
        Service = service.Name,
        // Location = service.Location, // this is the line that I added to fix the error
        PolicyData = policyData
    });
```

**Comment by floyd-may** [comment]
@lukehoban any chance we can reopen this and call it a Real Bug? 🙏

**Comment by openlyDarwin** [comment]
FWIW I just hit a very similar problem here

```
gcp:cloudrun:IamPolicy (policy):
    error: 1 error occurred:
    	* Error setting IAM policy for cloudrun service "v1/projects/PROJECT/locations/ZONE/services/service": googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
    <html lang=en>
      <meta charset=utf-8>
      <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
      <title>Error 404 (Not Found)!!1</title>
      <style>
        *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
      </style>
      <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
      <p><b>404.</b> <ins>That’s an error.</ins>
      <p>The requested URL <code>/v1/projects/PROJECT/locations/ZONE/services/service:setIamPolicy</code> was not found on this server.  <ins>That’s all we know.</ins>
```

with the following `main.go`:

```
package main

import (
	"github.com/pulumi/pulumi-gcp/sdk/v5/go/gcp"
	"github.com/pulumi/pulumi-gcp/sdk/v5/go/gcp/cloudrun"
        ...
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		gcpProvider, err := gcp.NewProvider(ctx, "name", &gcp.ProviderArgs{
			Project: pulumi.String("PROJECT"),
			Region:  pulumi.String("REGION"),
			Zone:    pulumi.String("ZONE"),
		})
		if err != nil {
			return err
		}
		...
		_, err = cloudrun.NewIamPolicy(ctx, "policy", &cloudrun.IamPolicyArgs{
			// Location:   pulumi.String("us-central1"), // un-commenting this results in a successful pulumi up
			Service:    crService.Name,
			PolicyData: pulumi.String(crServiceIAMPolicy.PolicyData),
		}, pulumi.Provider(gcpProvider))
		if err != nil {
			return err
		}
		return nil
	})
}
```

The repro steps:

1. instantiate a new GCP provider with an explicit `Zone` argument
2. pass that provider to `cloudrun.NewIamPolicy`
