### ISSUE TITLE
"unexpected archive source" while trying to create BucketObject

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-gcp#34]
The following code:

``` js
let bucket = new gcp.storage.Bucket("bucket", {});
let data = new gcp.storage.BucketObject("object", {
    bucket: bucket.name,
    source: new pulumi.asset.AssetArchive({
        ".": new pulumi.asset.FileArchive("./javascript"),
    }),
});
```

fails to be run by `pulumi update`:

```
Previewing changes:

     Type                   Name                         Plan       Info
 +   pulumi:pulumi:Stack    gcp-blablabla-gcp-blablabla  create     1 error
 +   └─ gcp:storage:Bucket  bucket                       create

Diagnostics:
  pulumi:pulumi:Stack: gcp-blablabla-gcp-blablabla
    error: unexpected archive source

error: an error occurred while advancing the preview
```

**Comment by swgillespie** [comment]
Pretty sure this is https://github.com/pulumi/pulumi/issues/280.

**Comment by mikhailshilkov** [comment]
So is there a workaround? I just want to create a Function...

**Comment by lukehoban** [comment]
This is being fixed with https://github.com/pulumi/pulumi-gcp/pull/12.

**Comment by lukehoban** [comment]
Fixed with #12.

**Comment by mikhailshilkov** [comment]
So I suppose I need to wait for 0.14.3 release?

**Comment by joeduffy** [comment]
This is an important enough fix that it warrants a new release. @matt, could you handle this? Also, @luke, will we add this example to the examples repo, pinned to that release once available?

**Comment by lukehoban** [comment]
Yes - I was planning on adding an (improved) example to the examples repo this afternoon. 

Note that you can use `”@pulumi/gcp”: “dev”` to pick up the latest build from master at any time - so you can use this even before we get the updated release out.
