### ISSUE TITLE
Cloud Functions updated only if source URL path ends with a slash

### ISSUE THREAD

**Issue by dror-g** [pulumi/pulumi-gcp#343]
When deploying Cloud Functions from a subfolder in source repository, functions are not updated on every `pulumi up` op unless the source_repository url path ends with a slash `/` .

For example:
`{repo}/moveable-aliases/master/paths/function_subfolder` will create the function no problem on first run, but on subsequent runs will not update it.

`{repo}/moveable-aliases/master/paths/function_subfolder/` on the other hand will update the function (`[diff: ~sourceRepository]`) on every Pulumi run.

Not sure if a bug or a feature, as it can actually save needless updates if there's a 'force update' flag available to be set.

**Comment by mikhailshilkov** [comment]
It looks like this has been fixed since 2020. I tried the following program:

```py
const functionPython = new gcp.cloudfunctions.Function("python-func", {
    runtime: "python37",
    entryPoint: "handler",
    sourceRepository: {
        url: "https://source.developers.google.com/projects/myorganisation/repos/bitbucket_myrepo/moveable-aliases/myb/paths/myfunction",
    },
    region: "us-central1",
    triggerHttp: true,
    availableMemoryMb: 128,
});
```

then I do get diffs on changing the repository path:

```
~ sourceRepository: {
  ~ url: "https://source.developers.google.com/projects/myorganisation/repos/bitbucket_myrepo/moveable-aliases/myb/paths/myfunction" => "https://source.developers.google.com/projects/myorganisation/repos/bitbucket_myrepo/moveable-aliases/myb/paths/myfunction2"
}
```
