### ISSUE TITLE
The invoker resource of CallbackFunction doesn't follow given provider

### ISSUE THREAD

**Issue by nomeaning777** [pulumi/pulumi-gcp#345]
The cause is missing `parentOpts` for invoker. https://github.com/pulumi/pulumi-gcp/blob/master/sdk/nodejs/cloudfunctions/zMixins.ts#L183

For example, the behavior of the following code is not intended.
```typescript
import * as gcp from "@pulumi/gcp";
import { readFileSync } from "fs";

// Provider
const gcpProvider = new gcp.Provider("gcp-provider", {credentials: readFileSync('very-secret.json', {encoding: 'utf-8'}), project: 'project', region: 'region'});

new gcp.cloudfunctions.HttpCallbackFunction("function1",{
    callback: (req: any, res: any) => {res.send("OK");},
}, {
    provider: gcpProvider
});
```

This code generate the following resources. 
```
 +   pulumi:pulumi:Stack                      gcp-function-dev   create     
 +   ├─ gcp:cloudfunctions:CallbackFunction   function1          create     
 +   │  ├─ gcp:storage:Bucket                 function1          create     
 +   │  ├─ gcp:storage:BucketObject           function1          create     
 +   │  └─ gcp:cloudfunctions:Function        function1          create     
 +   ├─ pulumi:providers:gcp                  gcp-provider       create     
 +   └─ gcp:cloudfunctions:FunctionIamMember  function1-invoker  create     
```
The problem is that `function1-invoker` uses not `gcp-provider` but default provider because `function1-invoker` is not child of `gcp:cloudfunctions:CallbackFunction`.

**Comment by leezen** [comment]
Thanks for pointing this out. As a temporary workaround, you can use a transformation to ensure that the provider is set correctly: https://www.pulumi.com/docs/intro/concepts/programming-model/#transformations.

**Comment by mikhailshilkov** [comment]
Fixed by https://github.com/pulumi/pulumi-gcp/commit/4d136cd19dd1d94b2d7bf49b6227e5ec6c2ebb37
