### ISSUE TITLE
Support config connector deployment

### ISSUE THREAD

**Issue by ghoullier** [pulumi/pulumi-gcp#389]
Hi!

Is there any plan to support Google Cloud Config Connector https://cloud.google.com/config-connector/docs/overview / Kubernetes Config Connector https://github.com/GoogleCloudPlatform/k8s-config-connector ?

**Comment by mjeffryes** [comment]
If you're still interested in this topic please file an issue on https://github.com/pulumi/pulumi-kubernetes-operator as that's likely where we'd consider a project like this
