### ISSUE TITLE
How to verify NotificationChannel using VerifyNotificationChannel ?

### ISSUE THREAD

**Issue by ghoullier** [pulumi/pulumi-gcp#390]
Hi!

According to [NotificationChannel::verificationStatus documentation](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/gcp/monitoring/#NotificationChannel-verificationStatus), it's possible to update status using: VerifyNotificationChannel.

```js
    /**
     * Indicates whether this channel has been verified or not. On a ListNotificationChannels or GetNotificationChannel
     * operation, this field is expected to be populated.If the value is UNVERIFIED, then it indicates that the channel is
     * non-functioning (it both requires verification and lacks verification); otherwise, it is assumed that the channel
     * works.If the channel is neither VERIFIED nor UNVERIFIED, it implies that the channel is of a type that does not require
     * verification or that this specific channel has been exempted from verification because it was created prior to
     * verification being required for channels of this type.This field cannot be modified using a standard
     * UpdateNotificationChannel operation. To change the value of this field, you must call VerifyNotificationChannel.
     */
```

But there is no VerifyNotificationChannel declaration in the @pulumi/gcp repository.

How can I verify NotificationChannel using VerifyNotificationChannel?

**Comment by leezen** [comment]
You'll have to call the API directly: https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.notificationChannels/verify

You could setup a dynamic provider to run as part of your stack to only perform the verification on create: https://www.pulumi.com/docs/intro/concepts/programming-model/#dynamicproviders

**Comment by ghoullier** [comment]
Thanks for your reply 🙇🏼‍♂️
