### ISSUE TITLE
Cluster update: Expected diff to not require deletion or replacement

### ISSUE THREAD

**Issue by blankenshipz** [pulumi/pulumi-gcp#394]
I just recently upgraded an older project from version `0.18.3` to version `3.15.0` of the GCP plugin and from `0.17.25` to `2.7.1` of pulumi itself.

I'm trying to add:

```
  releaseChannel: {
    channel: "STABLE"
  },
```

to a cluster definition which should be an update in place but the up is panic'ing 

```
  pulumi:pulumi:Stack (cluster):
    panic: fatal: An assertion has failed: Expected diff to not require deletion or replacement during Update...
```

Is this a known issue?

**Comment by leezen** [comment]
Not in particular, but one thing I've seen work in the past has been to go from pre-1.0 to 1.0 to 2.0 as the checkpoint migration sometimes works better and might avoid this type of issue.
