### ISSUE TITLE
Support pubsub subscription filters

### ISSUE THREAD

**Issue by robertsahlin** [pulumi/pulumi-gcp#397]
There is no property to set pubsub subscription filters. Should be easy and fast to implement. https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions/create

**Comment by robertsahlin** [comment]
Will this fix also trickle down into Pulumi and address the issue? https://github.com/GoogleCloudPlatform/magic-modules/pull/3759

**Comment by leezen** [comment]
Yes, that should do it
