### ISSUE TITLE
Ignore "sandbox.gke.io/runtime" labels on GKE node pools

### ISSUE THREAD

**Issue by ddgenome** [pulumi/pulumi-gcp#398]
When you create a [GKE sandbox node pool](https://cloud.google.com/kubernetes-engine/docs/concepts/sandbox-pods), GKE automatically adds the following label to the node pool:

    "sandbox.gke.io/runtime": "gvisor"

On subsequent updates, Pulumi tries to delete that label. Since the underlying provider requires replacement when node pool labels are changed, this results in a lengthy create replacement and delete original cycle. Since doing this effectively makes no change because GKE adds the label every time, this replace cycle occurs every time `pulumi up` is run.

I work around this by adding the above label to the NodePoolArgs _after_ creation. If you try to have them there when creating the node pool, you get the following error:

```
error creating NodePool: googleapi: Error 400: Node labels with key "sandbox.gke.io/runtime" are managed by GKE and must not be manually specified., badRequest
```

Is there any way to tell Pulumi to ignore discrepancies in certain properties, like this specific label, when computing its plan?

**Comment by leezen** [comment]
One way around this would be to `ignoreChanges` on the labels: https://www.pulumi.com/docs/intro/concepts/programming-model/#ignorechanges

**Comment by ddgenome** [comment]
Thanks for the tip @leezen! Unfortunately, I want to manage the other labels using Pulumi and, as far as I know, the `ignoreChanges` options would only allow ignoring _all_ the labels, not just the one added by GKE.

**Comment by ddgenome** [comment]
This no longer appears to be an issue. Perhaps it got fixed in the Terraform upstream.
