### ISSUE TITLE
Changing `initialNodeCount` cause `NodePool` to be marked as `replace`

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi-gcp#412]
Changing the `initialNodeCount` should not cause the `NodePool` to be replaced. If you go into the GCP console, and change the current node size to whatever you want this value to be, and then do a refresh, and then a preview, there is no difference.

**Comment by mjeffryes** [comment]
This behavior is determined by the upstream https://github.com/hashicorp/terraform-provider-google If you're still experiencing this issue; I would recommend filing a ticket on that project
