### ISSUE TITLE
GCP Workflows without YAML

### ISSUE THREAD

**Issue by tomdavidson** [pulumi/pulumi-gcp#421]
Im excited about GCP [Workflows](https://cloud.google.com/workflows) but not excited about using YAML as a programming language.  Any existing plans to support Workflows in Pulumi?

**Comment by stack72** [comment]
Hi @tomdavidson 

So Workflows are now supported in pulumi-gcp - https://www.pulumi.com/docs/reference/pkg/gcp/workflows/workflow/

Please let us know if there are any further issues

Paul
