### ISSUE TITLE
Provisioning error shows incorrect project number

### ISSUE THREAD

**Issue by ddunkin** [pulumi/pulumi-gcp#46]
When trying to bring up a stack that included a `gcp.sql.DatabaseInstance`, I got this error:
```
Plan apply failed: Error, failed to create instance unleash: googleapi: Error 403: Access Not Configured. Cloud SQL Admin API has not been used in project 563584335869 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sqladmin.googleapis.com/overview?project=563584335869 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured
```

I do have sqladmin.googleapis.com enabled, but 563584335869 is not my project.

**Comment by ddunkin** [comment]
After further investigation, I found 563584335869 is the project number for Firebase CLI, which I installed in the past.

I ran `gcloud auth application-default login` and now `pulumi up` works as expected.

**Comment by aclowkey** [comment]
Same thing happens in Terraform.. Thanks

**Comment by RuneStone0** [comment]
Issue still apply when running an app locally through `dev_appserver.py`, even after running `gcloud auth application-default login` as suggested.
