### ISSUE TITLE
[Install] File name too long error

### ISSUE THREAD

**Issue by alexandradeas** [pulumi/pulumi-gcp#466]
when running `pulumi new gcp-go` I ran into the error

```
Installing dependencies...

-> unzip /home/alexandra/go/pkg/mod/cache/download/github.com/pulumi/pulumi-gcp/sdk/v4/@v/v4.0.0.zip: open /home/alexandra/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v4@v4.0.0.tmp-783098231/dotnet/DataLoss/Inputs/PreventionDeidentifyTemplateDeidentifyConfigInfoTypeTransformationsTransformationPrimitiveTransformationCharacterMaskConfigCharactersToIgnoreArgs.cs: file name too long
unzip /home/alexandra/go/pkg/mod/cache/download/github.com/pulumi/pulumi-gcp/sdk/v4/@v/v4.0.0.zip: open /home/alexandra/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v4@v4.0.0.tmp-783098231/dotnet/DataLoss/Inputs/PreventionDeidentifyTemplateDeidentifyConfigInfoTypeTransformationsTransformationPrimitiveTransformationCharacterMaskConfigCharactersToIgnoreArgs.cs: file name too long
```

This is run from linux on an ext4 partition which has a limit on the number of bytes in a filename of 255, with the string `/home/alexandra/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v4@v4.0.0.tmp-077155514/dotnet/DataLoss/Inputs/PreventionDeidentifyTemplateDeidentifyConfigInfoTypeTransformationsTransformationPrimitiveTransformationCharacterMaskConfigCharactersToIgnoreArgs.cs` equaling 255 bytes

**Comment by alexandradeas** [comment]
It appears based on https://en.wikipedia.org/wiki/Comparison_of_file_systems that this filename limit appears on a large number of commonly used file systems although I don't have a method to verify this

**Comment by filip-zyzniewski** [comment]
This is easier to hit with ecryptfs: https://bugs.launchpad.net/ecryptfs/+bug/344878

**Comment by t0yv0** [comment]
Wonder if there is a workaround, before we find a fix for this.

It sounds like GOPATH defaults to $HOME/go [1]. If the system in question is say Ubuntu, then /home/user will typically use ecryptfs but the general filesystem would not. Perhaps something like this:

```
mkdir -p /w/go
cd /w
GOPATH=/w/go pulumi new gcp-go
```

Too make sure the project is avoiding the ecryptfs. Something like this helped me before with a similar Scala issue. I need to get a linux VM to repro this one though to be more precise here.


[1] Quote: The GOPATH environment variable specifies the location of your workspace. It defaults to a directory named go inside your home directory, so $HOME/go on Unix

**Comment by t0yv0** [comment]
Trying with

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

```
/dev/sda1 on / type ext4 (rw,relatime)
```

Cannot repro, works as expected. The file is present still `PreventionDeidentifyTemplateDeidentifyConfigInfoTypeTransformationsTransformationPrimitiveTransformationCharacterMaskConfigCharactersToIgnoreArgs.cs` in the 4.9.1 SDK. 

I guess this would only affect users with ecryptfs encrypted /home partition. I wonder if this affects any other OS-s.

**Comment by mikhailshilkov** [comment]
Our current design of code generation tools relies on long-ish file names quite heavily. I don't think we want to change anything here, and above-255 file path is going to stay as a requirement. In any case, a potential improvement would need to be done in https://github.com/pulumi/pulumi and not in the GCP provider itself.
