### ISSUE TITLE
`<Resource>.get(...)` requires resource id and name to be specified redundantly

### ISSUE THREAD

**Issue by geekflyer** [pulumi/pulumi-gcp#48]
In GCP for most resources there is no separate notion of a an ID and name (unlike AWS, where resources often have a random ID and a separate deterministic name).

When using the `.get` method on GCP resources pulumi requires the ID / name to be specified redundantly and if one of them is omitted or does not match the other one, the whole `.get` fails.

So far I can confirm this issue exists with GCS buckets and GKE clusters. Probably this issue exists with many more resource types.

Here's an example to reproduce the issue when using GCS buckets:

In the examples below I will assume that gsutil AND pulumi have been already configured to use the gcp project `my-project` (i.e. via `pulumi config set gcp:project my-project`). I will add some example code and paste the output (error or sucess) after a `pulumi preview` of the example code.

Prerequisite: create GCS bucket via `gsutil mb gs://pulumi-experiment-bucket`

### 1. FAILURE with lookup by ID only:
```ts
import * as gcp from '@pulumi/gcp';

const myBucket = gcp.storage.Bucket.get(
  'my-bucket',
  'pulumi-experiment-bucket'
);
```
yields:
```
Previewing changes:

     Type                   Name                                            Plan       Info
 +   pulumi:pulumi:Stack    pulumi-query-experiments-christian-experiments  create
 >-  └─ gcp:storage:Bucket  my-bucket                                       read       1 error

Diagnostics:
  gcp:storage:Bucket: my-bucket
    error: Preview failed: refreshing urn:pulumi:christian-experiments::pulumi-query-experiments::gcp:storage/bucket:Bucket::my-bucket: Error reading Storage Bucket "": googleapi: Error 400: Required parameter: project, required

error: an error occurred while advancing the preview
```
Note: The error message says `project` is required, even though it is already set in the pulumi provider config, so this error message is at the very least misleading.

### 2. FAILURE when specifying non-matching ID and name:

```ts
import * as gcp from '@pulumi/gcp';

const myBucket = gcp.storage.Bucket.get(
  'my-bucket',
  'pulumi-experiment-bucket-foo',
  {name: 'pulumi-experiment-bucket'}
);
```
yields:
```
Previewing changes:

     Type                   Name                                            Plan       Info
 +   pulumi:pulumi:Stack    pulumi-query-experiments-christian-experiments  create
 >-  └─ gcp:storage:Bucket  my-bucket                                       read       1 error

Diagnostics:
  gcp:storage:Bucket: my-bucket
    error: Preview failed: reading resource urn:pulumi:christian-experiments::pulumi-query-experiments::gcp:storage/bucket:Bucket::my-bucket yielded an unexpected ID;expected pulumi-experiment-bucket-foo, got pulumi-experiment-bucket

error: an error occurred while advancing the preview
➜ 
```

### 3. SUCCESS when specifying id and name redundantly

```ts
import * as gcp from '@pulumi/gcp';

const myBucket = gcp.storage.Bucket.get(
  'my-bucket',
  'pulumi-experiment-bucket',
  {name: 'pulumi-experiment-bucket'}
);
```
yields:
```
Previewing changes:

     Type                   Name                                            Plan       Info
 +   pulumi:pulumi:Stack    pulumi-query-experiments-christian-experiments  create
 >-  └─ gcp:storage:Bucket  my-bucket                                       read

info: 2 changes previewed:
    + 1 resource to create
    >-1 resource to read
```

## Summary
So in summary importing / querying a resource this way only works when the same name and id are specified redundantly and otherwise one gets rather confusing error messages.

### This behaviour is confusing for the following 2 reasons:
1. As an initial user one assumes that specifying  an `id` like `pulumi-experiment-bucket` should be enough to uniquely identify the resource (i.e. the GCS bucket).
2. The type signature of `.get` marks the third function parameter (i.e. BucketState) AND the `name` property as optional, even though they are in practice always required as demonstrated above.

For comparison: The equivalent terraform data source only requires the `name` property and no additional ID: https://www.terraform.io/docs/providers/google/r/storage_bucket.html#argument-reference

### Desired behaviour
Only require ID or name param to lookup a resource.

**Comment by lukehoban** [comment]
Thanks @geekflyer for the detailed write up. This is indeed unfortunate. It looks like this is related to the underlying behavior of the Google Terraform provider. Though we’ll need to figure out a way to make the `.get` experience simpler here.

**Comment by joeduffy** [comment]
I believe @jen20 is actively looking into this, so reassigning.

**Comment by jen20** [comment]
This is covered in the work I am doing to resolve #55. I have a prototype working which allows the following Pulumi program to import a node pool:

```typescript
import * as gcp from "@pulumi/gcp";

const defaultPool = gcp.container.NodePool.get("default-pool", "us-central1-a/test-ci/default-pool", {
    project: "pulumi-development",
});

// Export the DNS name of the bucket
export const nodePoolVersion = defaultPool.version;
```

I think it is possible to remove the dependency on `project` being specified such that resources in the project associated with the default provider instance can be imported solely by ID without redundancy, which I think will resolve this issue.

There is still some work to do to move all the changes from my scratch copy into the correct places in the Pulumi repo structure - most of the changes are in `pulumi/pulumi-terraform` rather than GCP provider directly. I'm hoping to land this either later tonight or tomorrow evening.

**Comment by jen20** [comment]
OK, I had misread and mis-recalled the Terraform provider requirement for the `gcp:project` configuration item to be the project *id* and not the project *name*. With the following configuration:

```shell
$ pulumi config
KEY                                              VALUE
gcp:project                                      pulumi-development
```

The following program:

```typescript
import * as gcp from "@pulumi/gcp";

const defaultPool = gcp.container.NodePool.get("default-pool", "us-central1-a/test-ci/default-pool");

export const nodePoolVersion = defaultPool.version;
```

Executes as one would hope:

```shell
$ pulumi up
Previewing update (gcp-55-dev):

     Type                       Name               Plan
 +   pulumi:pulumi:Stack        gcp-55-gcp-55-dev  create
 >-  └─ gcp:container:NodePool  default-pool       read

Resources:
    2 changes
    + 1 to create
    >-1 to read

Do you want to perform this update? yes
Updating (gcp-55-dev):

     Type                       Name               Status
 +   pulumi:pulumi:Stack        gcp-55-gcp-55-dev  created
 >-  └─ gcp:container:NodePool  default-pool       read

Outputs:
    nodePoolVersion: "1.9.7-gke.3"

Resources:
    2 changes
    + 1 created
    >-1 read

Duration: 9.798929989s
```
