### ISSUE TITLE
Please update to latest terraform provider

### ISSUE THREAD

**Issue by geekflyer** [pulumi/pulumi-gcp#49]
Current pulumi GCP is based on terraform google provider 1.16.2 which is months old and misses lots of features (terraform gcp provider is moving fast these days!), please pull in latest terraform google provider (1.18.0+).

Related slack conversation https://pulumi-community.slack.com/archives/C84L4E3N1/p1538015271000100

**Comment by lukehoban** [comment]
Definitely plan to update this very soon. 

Our current target is to update there at least once a milestone (4-5 weeks) but also on demand when key things become available. We last updated on 8/8 though - so we’re a little behind on that.  @pgavlin was working on an update last week but ran into a problem that we’ll need to work around. 

Automating the updates would be great - though there are currently two manual steps required which we would need to figure out how to automate;
1. Dependency management reconcilliation - we’re merging dependency information from both dep and govendor, which is tricky and can lead to manual intervention being necessary. 
2. Mapping new resources and data sources into namespaces.  This is not metadata driven, and currently requires small scale API design thinking.
