### ISSUE TITLE
Labels in logging.Metric are being converted to camel case

### ISSUE THREAD

**Issue by Tahvok** [pulumi/pulumi-gcp#497]
**Configuration**
Pulumi 2.16.2
I'm using python:
pulumi-gcp: 4.6.0
I've also tested with an older version of pulumi 2.8.2 and pulumi-gcp 3.12.0
So it doesn't seem like a recent bug.

**How to replicate**
If you create the following logging.Metric (not full code):
```
logging.Metric(
            ...
            label_extractors={
                "instance_id": "EXTRACT(resource.labels.instance_id)"
            },
            metric_descriptor={
                ...
                "labels": [
                    {
                        "key": "instance_id",
                        "value_type": "STRING",
                    }
                ],
                ...
            }
        )
```

It will fail with the following error:
```
googleapi: Error 400: No label descriptor found for label extractor with key instanceId
```

**Workaround**
Use a different key.

**Comment by leezen** [comment]
I believe this is running into a problem with the snake case to camel case tables and `instance_id` being in that table. For now, I would suggest the workaround described in https://github.com/pulumi/pulumi/issues/3151#issuecomment-704509706

**Comment by Tahvok** [comment]
I confirm that this works for me
