### ISSUE TITLE
race condition when changing resource ids leads to inconsistent state

### ISSUE THREAD

**Issue by geekflyer** [pulumi/pulumi-gcp#50]
This issue pertains to certain resource types, for example `gcp.projects.IAMMember` and the order of creation / deletion of those resources. It leads to inconsistencies between what was defined in code vs what's ending up as actual configuration / resources in the cloud provider.

Example:
1. create this code:
```ts
import * as gcp from '@pulumi/gcp';

new gcp.projects.IAMMember(`my-id`, {
  member: `user:john@doe.com`,
  role: 'roles/bigquery.user',
  project: 'my-project'
});
```
2. Run `pulumi up`. This will grant john@doe.com the bigquery role.
3. Make a change to the resource id:
```ts
import * as gcp from '@pulumi/gcp';

new gcp.projects.IAMMember(`my-id-changed`, {
  member: `user:john@doe.com`,
  role: 'roles/bigquery.user',
  project: 'my-project'
});
```
4. Run `pulumi up`.

### Expected Result
The user john@doe.com gets granted the role`roles/bigquery.user`.

### Actual Result
In step 4 pulumi **first** creates a new IAMMember with the resource id `my-id-changed` and _afterwards_ deletes the resource `my-id`.
The end result is that the user does NOT get the role `roles/bigquery.user` even though pulumi's state thinks that is the case.

This is probably a wider issue, either with the gcp provider or pulumi itself and IAMMember is just an example.
Fyi terraform replaces the resources in the correct order (i.e. delete old one first, create new one after).

**Comment by lukehoban** [comment]
I believe this is fundamentally https://github.com/pulumi/pulumi/issues/918. 

A workaround until first class support is available would be to mark these as delete-before-create or to support user-specified delete before create (https://github.com/pulumi/pulumi/issues/1620).

**Comment by lukehoban** [comment]
There is nothing unique we would do here beyond addressing pulumi/pulumi#918 and/or pulumi/pulumi#1620, so I'll go ahead and close this out and we can track those two issues as solutions to help address this.
