### ISSUE TITLE
Importing gcp:compute/firewall:Firewall always fails with "one of 'allow,deny' must be specified" error

### ISSUE THREAD

**Issue by shirpx** [pulumi/pulumi-gcp#508]
the next simple import of GCP firewall rule command:
`pulumi import gcp:compute/firewall:Firewall default projects/my-test-project/global/firewalls/my-firwall-rule
`
returns the next errors:
```
error: gcp:compute/firewall:Firewall resource 'my-firwall-rule' has a problem: "deny": one of `allow,deny` must be specified
error: gcp:compute/firewall:Firewall resource 'my-firwall-rule' has a problem: "allow": one of `allow,deny` must be specified
```
looks like a bug or maybe something is missing from the docs, https://www.pulumi.com/docs/reference/pkg/gcp/compute/firewall/#import

**Comment by clstokes** [comment]
I've shared a workaround for this at https://github.com/pulumi/pulumi-gcp/issues/505#issuecomment-771753910.

**Comment by eschley** [comment]
Is there any way to see what the name of the field its having a problem with? I tried the import via the way recommended in #505 and got the same issue.  If I call get and export it seems to print out all of the fields just fine.

Fails with the above error
`ssh_bastion = gcp.compute.Firewall("ssh-bastion", network="https://www.googleapis.com/compute/v1/projects/test/global/networks/test", opts=ResourceOptions(import_="ssh-bastion"))`

Seems to print out everything I should need
```
ssh_bastion = gcp.compute.Firewall.get("ssh-bastion", "ssh-bastion")
pulumi.export("ssh-bastion", ssh_bastion)
```
I also tried importing the network and referencing it but same error.  What field is is trying to validate?

**Comment by eschley** [comment]
Interestingly, if I add id to the ResourceOptions and reference the network that I already imported then it seemed to work?

`ssh_bastion = gcp.compute.Firewall("ssh-bastion", network=test, opts=ResourceOptions(id="ssh-bastion", import_="ssh-bastion"))`

**Comment by panthony** [comment]
I have the same issue but the workaround does not seems to generate the code like import would do.

This snippet does import the rule in the stack:

```python
allow_https = gcp.compute.Firewall(
    "default-allow-https",
    network=default,
    opts=pulumi.ResourceOptions(
        id="default-allow-https",
        import_="default-allow-https"
    )
)
```

But I do not have the code for the actual definition to replace this snippet with.

Using `Firewall.get` then `pulumi.export` does not really print anything helpful:

```bash
Outputs:
  + default-allow-https: {
      + disabled               : false
      + enable_logging         : output<string>
      + id                     : "default-allow-https"
      + log_config             : output<string>
      + priority               : 0
      + project                : "{project}"
      + self_link              : "https://www.googleapis.com/compute/v1/projects/{project}/global/firewalls/"
      + urn                    : "urn:pulumi:dev::vpc-network::gcp:compute/firewall:Firewall::default-allow-https"
    }
```

In fact, exporting a property such as `direction` which would be expected to print `ingress` returns an empty string.

**Comment by mjeffryes** [comment]
Based on the linked tickets, this issue appears to have been resolved. Please open a new issue if you encounter a similar problem.
