### ISSUE TITLE
CloudSQL Postgres IAM users

### ISSUE THREAD

**Issue by RXminuS** [pulumi/pulumi-gcp#509]
Althought Terraform seems to support the new IAM user in CloudSQL the options aren't accessible (at least in Typescript) in Pulumi yet. Is this as simple as updating the types, or is there more work to be done?

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_user

![image](https://user-images.githubusercontent.com/3949285/105058599-aec94980-5a76-11eb-8d3d-f58197ac2762.png)

**Comment by stack72** [comment]
Hi @RXminuS 

This is available - https://www.pulumi.com/docs/reference/pkg/gcp/sql/user/

Paul
