### ISSUE TITLE
Add ability to create autopilot GKE clusters

### ISSUE THREAD

**Issue by thecodeassassin** [pulumi/pulumi-gcp#532]
Google recently released their Autopilot feature for GKE. Using the API, it was as straightforward as adding this flag:

```
   "autopilot": {
      "enabled": true
    }
  ```

Docs:
https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview

**Comment by Place1** [comment]
Am I correct in my understanding that this needs to be supported in the Terraform Google Provider for Pulumi to consume?

If so, here's the upstream issue: https://github.com/hashicorp/terraform-provider-google/issues/8553

**Comment by hcharley** [comment]
It's looking like Google's Go library [was just updated](https://github.com/googleapis/google-api-go-client/pull/875) to [v0.41.0](https://github.com/googleapis/google-api-go-client/releases/tag/v0.41.0). I take it the [terraform provider](https://github.com/hashicorp/terraform-provider-google/issues/8553) needs to be updated as well.

**Comment by hcharley** [comment]
If I'm reading [issue #8553](https://github.com/hashicorp/terraform-provider-google/issues/8553) correctly, then `terraform-provider-google` will be released tomorrow with support for GKE Auto Pilot.
