### ISSUE TITLE
Default runtime for CallbackFunction is EOL and deprecated

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-gcp#533]
## Affected feature

The default runtime for `gcp.cloudfunctions.CallbackFunction` is `nodejs8`, which is deprecated per https://cloud.google.com/functions/docs/concepts/exec#runtimes.

![image](https://user-images.githubusercontent.com/293763/109258471-33626280-77af-11eb-9ce6-404b501300af.png)

https://github.com/pulumi/pulumi-gcp/blob/9b633df5a17461abc59652c62c956aeb3370403c/sdk/nodejs/cloudfunctions/zMixins.ts#L170

## Suggestion 

The default should be updated to a more modern version.

**Comment by michele** [comment]
Any chance of this being fixed?
