### ISSUE TITLE
DB Instance import

### ISSUE THREAD

**Issue by WebMago** [pulumi/pulumi-gcp#548]
### Summary
The import procedure for a DBInstance using the cli recommended by pulumi throws errors

## Expected behavior

`pulumi import gcp:sql/databaseInstance:DatabaseInstance db_instance projects/mystical-moon-307818/instances/prod-mysql`

Here I expected the code generated to be implemented on my code files. 

## Current behavior

```
gcp:sql:DatabaseInstance (db_instance):
    error: gcp:sql/databaseInstance:DatabaseInstance resource 'db_instance' has a problem: AtLeastOne: "settings": one of `clone,settings` must be specified
    error: gcp:sql/databaseInstance:DatabaseInstance resource 'db_instance' has a problem: AtLeastOne: "clone": one of `clone,settings` must be specified
    error: Preview failed: one or more inputs failed to validate

```
## Steps to reproduce

1. https://www.pulumi.com/docs/reference/pkg/gcp/sql/databaseinstance/#import
2. on my stack project with the values adjusted: `pulumi import gcp:sql/databaseInstance:DatabaseInstance db_instance projects/mystical-moon-307818/instances/prod-mysql`

## Context (Environment)

I can't import a previous DB Instance created on my GCP Provider.

**Pulumi version 2.22.0**

## Affected feature

**pulumi-gcp**

**Comment by xskif** [comment]
The same issue.

Pulumi version 3.2.1
Pulumi GCP version 5.2.0 (typescript)

**Comment by rlweb** [comment]
Same issue here!

```
Pulumi version 3.17.0
Pulumi GCP version 5.2.0 (typescript)
```

**Comment by leezen** [comment]
Typically, for a case like this, the heuristics for which inputs we flow through are incorrect. We're looking at options to improve that experience and perhaps provide more knobs for users to tune those heuristics. In the meantime, you should still be able to programmatically import this resource (https://www.pulumi.com/docs/guides/adopting/import/#pulumi-import-resource-operation)

**Comment by mikhailshilkov** [comment]
Import functionality has been significantly refactored in https://github.com/pulumi/pulumi/issues/8922 to substantially reduce the number of failures during `pulumi import` and make the generated code more truthful and complete. We haven't tested this exact issue, but we believe it's addressed by the refactoring.

I'll go ahead and close the issue - feel free if you still get issues with it after upgrading to the Pulumi CLI version 3.26.1 or above.

Read more about the changes in [Easier IaC adoption with improved `pulumi import` experience](https://www.pulumi.com/blog/changes-to-import/).
