### ISSUE TITLE
DB Instance: can't ignore changes to 'diskSize' - blocks all updates to DB instance with diskAutoresize: true

### ISSUE THREAD

**Issue by c2h5oh** [pulumi/pulumi-gcp#549]
Cloud SQL (PostgreSQL) instance created with `diskAutoresize: true` and empty `diskSize` will fail to update if autoresize has increased storage size beyond the default 10 GB, even if `ignoreChanges: [ "diskSize" ]` : 

`Error, failed to update instance settings for : googleapi: Error 400: Invalid request: The disk size cannot decrease. Current size: 37 GB, requested: 10 GB.., invalid`

```
pulumi v2.23.1
pulumi-gcp 4.15.0
```

## Expected behavior
`ignoreChanges` allows to ignore a change to diskSize that got increased by GCP because of `diskAutoresize: true`

## Current behavior
`ignoreChanges: [ "diskSize" ]` doesn't cause diskSize changes to be ignored

## Steps to reproduce
1. Create db instance with empty `diskSize` (will default to 10), `diskAutoresize: true` and `ignoreChanges: [ "diskSize" ]`
2. Insert enough data into db to cause autoresize to increase db disk size over the default 10 GB
3. Change any configuration value for that db instance and try to apply it

**Comment by komalali** [comment]
Can you provide some code to reproduce the issue?

**Comment by c2h5oh** [comment]
Sure. Create postgresql instance, db and user with:
```ts
const instance = new gcp.sql.DatabaseInstance(
    `postgres-instance`,
    {
        databaseVersion: "POSTGRES_13",
        settings: {
            tier: "db-custom-1-4096",
            availabilityType: "ZONAL",
            activationPolicy: "ALWAYS",
            diskAutoresize: true,
            diskType: "PD_SSD",
            diskSize: 10,
            ipConfiguration: {
                ipv4Enabled: true,
            }
        }
    },
    {
        ignoreChanges: [
            "diskSize"
        ],
    }
);

const user = new gcp.sql.User(
    `my-user`,
    {
        instance: instance.name,
        name: "my-user",
        password: "my-password",
    }
);

const database = new gcp.sql.Database(
    `my-database`,
    {
        instance: instance.name,
        name: `my-database`,
        charset: "UTF8",
        collation: "en_US.UTF8",
    }
);
```

Connect to that database with your favorite SQL client and generate 15 GB of data in that database:
```sql
CREATE TABLE test_data(
    col1 bigint
);

INSERT INTO test_data (col1) SELECT generate_series(1, 503316480);
```
This is going to run for a while - writing 15 GB in 32 byte rows takes some time.


Run `pulumi up` again. It will fail unless you increase `diskSize` to a value larger than the one it was resized to because of `diskAutoresize: true`.

**Comment by bmyers427** [comment]
Any updates or workarounds for this? I'm facing the same exact issue

**Comment by thomas-gallop** [comment]
Seeing this aswell,  Error, failed to update instance settings for : googleapi: Error 400: Invalid request: The disk size cannot decrease. Current size: 3803 GB, requested: 628 GB.., invalid

Using typescript with autoresize = true and disk_size not set.  

It appears running the refresh step unblocks updates to the database instance.

**Comment by gunar** [comment]
Same problem here. As @thomas-gallop mentioned, using `--refresh` fixes this.

**Comment by sbjorn** [comment]
Passing `ignore_changes=['settings.diskSize']` works well on my end. (Definitions written in python)

**Comment by mikhailshilkov** [comment]
I think this is by design. The `ignoreChanges` option makes Pulumi use the previous value, which, when sent to the API, is rejected by Google Cloud. Since the drift is created on the Google side, the use of refresh is required in this case.
