### ISSUE TITLE
Issue when importing storage bucket with lifecycleRules

### ISSUE THREAD

**Issue by sharpn** [pulumi/pulumi-gcp#559]
I am currently trying to move from TF to pulumi and whenever i attempt to import a storage bucket with lifecycle rules i get the following error.

```bash
 ~ lifecycleRules: [
          ~ [0]: {
                  ~ condition: {
                      ~ age: 30 => 30
                    }
                }
        ]
```

## Expected behavior
It should import the existing bucket into state.

## Current behavior
Shows a warning relating to the age condition and fails to import

## Steps to reproduce
1. Create a gcp bucket with lifecycle rules
2. Attempt to import it into pulumi state

## Context (Environment)
Attempting to move existing buckets created with TF to pulumi

## Affected feature

Importing of buckets into state

**Comment by leezen** [comment]
@sharpn Could you please try importing programmatically with `ignoreChanges` against `lifecycleRules`?

**Comment by sharpn** [comment]
@leezen if i run with `ignoreChanges` set to `lifecycleRules` i get this `List shorter than MinItems: Attribute supports 1 item minimum, config has 0 declared. Examine values at 'Bucket.LifecycleRules[0].Condition'.`

**Comment by leezen** [comment]
@sharpn Ah, apologies that that didn't work as I'm not super familiar with importing a bucket with lifecycle rules. We'll want to spend some time investigating why there's that `30 => 30` diff, which looks very odd, but I'm trying to see if there's a quick workaround to help you get going. My other thought on the `ignoreChanges` front is to specifically ignore the `age` condition, i.e. ignoreChanges on the nested property: `lifecycleRules[0].condition.age`

Could you also please share how you're importing if it's via the `pulumi import` CLI or programatically in code?

**Comment by sharpn** [comment]
Hey, sorry for the delay.

I have just run this command today `pulumi import gcp:storage/bucket:Bucket testing-bucket bucket-name` and the import seems to work. However when i run the `pulumi up` it says that the lifecycle rules need to change with the `30 => 30` as the thing that needs to change, i have atleast managed to import it

**Comment by mnlumi** [comment]
Retested. There's no pending changes regarding the lifecycle policy. Closing as fixed.
