### ISSUE TITLE
Cluster update fails, enable_binary_authorization conflicts with enable_autopilot

### ISSUE THREAD

**Issue by johannesdrescher** [pulumi/pulumi-gcp#560]
I ran into this issue when I enabled the autopilot option on my cluster. I thought it might have to do with the way I configured my cluster but it occurs even when no other argument is set.

### Steps to reproduce
- Run `pulumi new` in empty directory, choose `gcp-go` template
- Replace the contents of `main.go` and `go.mod` with code below
- Run `pulumi up` 

### main.go
```
package main

import (
	"github.com/pulumi/pulumi-gcp/sdk/v4/go/gcp/container"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, err := buildCluster(ctx)
		if err != nil {
			return err
		}
		return nil
	})
}

func buildCluster(ctx *pulumi.Context) (*container.Cluster, error) {
	return container.NewCluster(ctx, "cluster", &container.ClusterArgs{
		EnableAutopilot: pulumi.Bool(true),
	})
}
```

### go.mod

```
module foo

go 1.16

require (
	github.com/pulumi/pulumi-gcp/sdk/v4 v4.21.0
	github.com/pulumi/pulumi/sdk/v2 v2.25.0
)
```

### pulumi up output

```
Previewing update (production)

View Live: https://app.pulumi.com/organization/foo/production/previews/bar

     Type                      Name            Plan       Info
 +   pulumi:pulumi:Stack       foo-production  create     
     └─ gcp:container:Cluster  cluster                    1 error
 
Diagnostics:
  gcp:container:Cluster (cluster):
    error: gcp:container/cluster:Cluster resource 'cluster' has a problem: ConflictsWith: "enable_binary_authorization": conflicts with enable_autopilot. Examine values at 'Cluster.EnableBinaryAuthorization'.
```

**Comment by johannesdrescher** [comment]
I just upgraded to v5. I thought there might be a change in there that would solve this too. But unfortunately the error still occurs.

**Comment by Zubnix** [comment]
Is there a workaround available? This blocks us from deploying a new stack using pulumi :(

**Comment by johannesdrescher** [comment]
@Zubnix I was not able to find a workaround. Hoping this will be fixed soon.

**Comment by xskif** [comment]
The same:
`error: gcp:container/cluster:Cluster resource 'autopilot' has a problem: ConflictsWith: "enable_binary_authorization": conflicts with enable_autopilot. Examine values at 'Cluster.EnableBinaryAuthorization'.`

```typescript
export const k8sCluster = new gcp.container.Cluster("autopilot", {
  enableBinaryAuthorization: false, // true|false, doesn't matter
  enableAutopilot: true,
});
```

**Comment by stack72** [comment]
Hi all

I am working on a fix for this right now and it will be available in the next version of the pulumi-gcp provider in a day or 2

Paul
