### ISSUE TITLE
CloudRun: Required attribute is not set

### ISSUE THREAD

**Issue by mszewczyk-ipwt** [pulumi/pulumi-gcp#573]
`Required attribute is not set` appears when `ignore_changes` is pointing to `template.spec.containers[0].image`

## Expected behavior
Pulumi should perform the preview and show the differences.

## Current behavior
When trying to do the preview, an existing resource of type `gcp:cloudrun/service:Service` throws following errors appear:
```
  gcp:cloudrun:Service (gcp-cloudrunservice-api):
    error: gcp:cloudrun/service:Service resource 'gcp-cloudrunservice-api' has a problem: Required attribute is not set. Examine values at 'Service.Template.Spec[0].Containers[0].Resources'.
```
or
```
  gcp:cloudrun:Service (gcp-cloudrunservice-api):
    error: gcp:cloudrun/service:Service resource 'gcp-cloudrunservice-api' has a problem: Required attribute is not set. Examine values at 'Service.Template.Spec[0].Containers[0].Ports'.
```
The point of the values is a complete random, sometimes it points to parameters that are set. This happens with Python, I did not try other languages.

## Steps to reproduce
1. Declare a sample CloudRun service with nest up to `ServiceTemplateSpecContainerArgs` and also:
    * `image`
    * `ports`
    * `envs`
3. Deploy the resource with `pulumi up`
4. Change `image` value
5. Add `ResourceOptions` with `ignore_changes` set to `template.spec.containers[0].image`
6. Deploy the resource again with `pulumi up`

## Context (Environment)
I am using pulumi version 3.1.0 with plugins:
```
NAME    KIND      VERSION  SIZE    INSTALLED  LAST USED
docker  resource  3.0.0    41 MB   n/a        34 minutes ago
gcp     resource  5.2.0    104 MB  n/a        34 minutes ago
github  resource  4.0.0    40 MB   n/a        34 minutes ago
```
and python packages:
```
pulumi            3.1.0
pulumi-docker     3.0.0
pulumi-gcp        5.2.0
pulumi-github     4.0.0
```
Python version 3.9.2

## Affected feature
Pulumi is used in CI/CD and also in setting up infrastructure. While dealing just with infrastructure bits I am not able to preview anything because Pulumi is throwing these kind of errors, when I remove `ignore_changes` option or point the option to some other resource property that is not being changed then everything is OK.
I need this option, because the tag of the image is acquired from environment variable in CI/CD and when env is not used then changes should affect anything that is being changed except the `image` part.

**Comment by maxmoeschinger** [comment]
I am also having this issue. Has this ever been fixed?

**Comment by mjeffryes** [comment]
As noted in https://github.com/pulumi/pulumi-gcp/issues/827 this appears to have been fixed.
