### ISSUE TITLE
Cloud run does not return trigger url

### ISSUE THREAD

**Issue by JasperHG90** [pulumi/pulumi-gcp#585]
I'm trying to set up a cloud run application that is triggered by a pub/sub push subscription. To do this, I need to retrieve the trigger url from the cloud run service, but it doesn't appear to be an attribute.

## Expected behavior

Looking at the documentation for [cloud run services](https://www.pulumi.com/docs/reference/pkg/gcp/cloudrun/service/#servicestatus), I see that 'ServiceStatus' returns a _url_ attribute. I expect to be able to pass this url to another Pulumi resource, much like one would with a cloud function (which has a _https_trigger_url_ attribute).

## Current behavior

When I try to access the `mycloudrun.statuses.url` attribute, Pulumi errors out with `AttributeError: 'list' object has no attribute 'url'`.

## Steps to reproduce

1. I use pulumi==3.1.0 & pulumi-gcp==5.1.0
2. Use the example from [the docs](https://www.pulumi.com/docs/reference/pkg/gcp/cloudrun/service/#cloud-run-service-basic)
3. The resulting cloud run service doesn't have an `apply` method but trying to pass the resource's trigger url using `mycloudrun.statuses.url` to any other resources yields the above error.

## Context (Environment)
Personal project.

## Affected feature

N/A

**Comment by JasperHG90** [comment]
Update: from playing around with it a bit more, I see that the type of `mycloudrun.statuses` is of type 'pulumi.output.Output'. This is strange because the error says it is of type 'list'. 

Anyway, calling:

```python
mycloudrun.statuses.apply(lambda r: print(r))
```

And then `pulumi up`, returns:

```
    [{'conditions': [{'message': '', 'reason': '', 'status': 'True', 'type': 'Ready'}, {'message': '', 'reason': '', 'status': 'True', 'type': 'ConfigurationsReady'}, {'message': '', 'reason': '', 'status': 'True', 'type': 'RoutesReady'}], 'latest_created_revision_name': 'mycloudrun', 'latest_ready_revision_name': 'mycloudrun', 'observed_generation': 1, 'url': 'https://mycloudrun.a.run.app'}]
```

The URL can be accessed by doing:

```python
mycloudrun.statuses.apply(lambda r: print(r[-1].get("url")))
```

Bit of a hack but it works.

**Comment by lukehoban** [comment]
The solution you identified is indeed generally how you can access the `url`.

The output properties are actually a value that is both a list (or dict) and an `Output`.  If you access the list or dict elements, you get a new `Output` wrapping the indexed value  This allows you to also express the same thing as:

```py
mycloudrun.statuses[-1]["url"].apply(print)
```

Or in more common usage:

```py
pulumi.export("url", mycloudrun.statuses[-1]["url"])
```

**Comment by Mistic92** [comment]
How to access url with golang?
