### ISSUE TITLE
Compilation error using go in version 5.8.0

### ISSUE THREAD

**Issue by yarinm** [pulumi/pulumi-gcp#594]
```
# github.com/pulumi/pulumi-gcp/sdk/v5/go/gcp/pubsub
/Users/yarin/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v5@v5.8.0/go/gcp/pubsub/init.go:29:8: undefined: Schema
```

It seems that 5.X versions has the same compilation issue

**Comment by stack72** [comment]
Hi @yarinm 

My apologies for this - this is due to an overzealous gitignore file - I have just pushed the change and will cut a release of the provider when the build is green

Release will be tagged as v5.8.1

Paul

**Comment by stack72** [comment]
Hi @yarinm 

5.8.1 is now released!

Paul
