### ISSUE TITLE
Serverless NetworkEndpointGroup for a load balancer targeting Cloud Run Service

### ISSUE THREAD

**Issue by coderjib** [pulumi/pulumi-gcp#595]
Currently gcp.compute.NetworkEndpointGroup doesn't seem to allow to create a serverless network endpoint group, with Google Cloud Run endpoint, as described [here](https://cloud.google.com/load-balancing/docs/https/setting-up-https-serverless#creating_the_load_balancer). I am using Typescript.
Here is the corresponding gcloud command that is mentioned there:
```
gcloud compute network-endpoint-groups create SERVERLESS_NEG_NAME \
    --region=us-central1 \
    --network-endpoint-type=serverless  \
    --cloud-run-service=CLOUD_RUN_SERVICE_NAME
```
The endpoint type doesn't support `SERVERLESS`, nor there is any option to configure `cloud-run-service`.
Could you suggest what is the recommended way to configure a load balancer for a Cloud Run Service using Pulumi?
Thanks a lot

**Comment by leezen** [comment]
It looks like this validation is enforced in the upstream provider (https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_compute_network_endpoint_group.go#L83) and will require a change to the provider to support this endpoint type.

**Comment by mikhailshilkov** [comment]
I believe this is tracked upstream in https://github.com/hashicorp/terraform-provider-google/issues/12299

**Comment by kujenga** [comment]
@leezen I believe this has been resolved upstream, `SERVERLESS` is now an option here: https://github.com/hashicorp/terraform-provider-google/blob/04d0e591d9e0f6af606e2cef15749d1ba612a92b/google/services/compute/resource_compute_network_endpoint_group.go#L94

This blog post: https://cloud.google.com/blog/topics/developers-practitioners/new-terraform-module-serverless-load-balancing points to example usage of the terraform module here: https://github.com/ahmetb/cloud-run-multi-region-terraform/blob/dbf90fe505308f6ecd7ccf29fc9959b3860ac75a/main.tf#L34-L43

If that's correct, what would the steps be to resolve this issue?

**Comment by kujenga** [comment]
It appears that as of the 7.1.0 release earlier today, this is now possible with configuration like the following:

```py
neg = gcp.compute.RegionNetworkEndpointGroup(
    "neg",
    network_endpoint_type="SERVERLESS",
    region="us-east1",
    cloud_run=gcp.compute.RegionNetworkEndpointGroupCloudRunArgs(
        service=my_service.name,
    ),
)
```

relevant docs here: https://www.pulumi.com/registry/packages/gcp/api-docs/compute/regionnetworkendpointgroup/

This issue may be able to be closed out.
