### ISSUE TITLE
BigQuery Dataset generation fails with an invalid id error

### ISSUE THREAD

**Issue by oliverdain** [pulumi/pulumi-gcp#607]
I'm trying to create a BigQuery Dataset with code like the following:

```py
    ds = Dataset('product_metrics_dataset',
                 dataset_id='pm',
                 location=location,
                 project=project_id)
```
and I'm getting this error:
```
googleapi: Error 400: Invalid dataset ID "projects/fullsuitetest/datasets/pm". Dataset IDs must be alphanumeric (plus underscores and dashes) and must be at most 1024 characters long., invalid
```

it appears that the `projects/fullsuitetest/datasets/` prefix is an error, but Pulumi is adding that on my behalf. 

## Steps to reproduce

1. Try to create a `pulumi_gcp.bigquery.Dataset` specifying the `project` for the `Dataset.
2. Get the error above

Expected: It would create the Dataset and I'd be happy.
Actual: It did not create the Dataset and instead I am sad.

**Comment by leezen** [comment]
Could you please provide details on what versions of packages you're using? I was unable to reproduce this in my testing with the following package versions:

```
pulumi     3.5.1
pulumi-gcp 5.11.0
```

**Comment by oliverdain** [comment]
Here's the output of `pip freeze`. I'm not 100% sure how it works but I assume if I'm in a `venv` pulumi uses the packages from there?

```
Arpeggio==1.10.2
attrs==21.2.0
certifi==2021.5.30
chardet==4.0.0
dill==0.3.4
flake8==3.9.2
grpcio==1.38.1
idna==2.10
isort==5.9.1
mccabe==0.6.1
mypy==0.910
mypy-extensions==0.4.3
parver==0.3.1
protobuf==3.17.3
pulumi==3.6.0
pulumi-docker==3.0.0
pulumi-gcp==5.10.1
pulumi-random==4.2.0
pycodestyle==2.7.0
pydantic==1.8.2
pyflakes==2.3.1
PyYAML==5.4.1
requests==2.25.1
semver==2.13.0
six==1.16.0
toml==0.10.2
typing-extensions==3.10.0.0
urllib3==1.26.6
```

Other relevant info:

```
$ python --version
Python 3.8.9
$ pulumi plugin ls
NAME    KIND      VERSION  SIZE    INSTALLED  LAST USED
docker  resource  3.0.0    41 MB   n/a        3 weeks ago
gcp     resource  5.10.1   107 MB  n/a        1 day ago
gcp     resource  5.4.0    104 MB  n/a        3 weeks ago
random  resource  4.2.0    31 MB   n/a        3 weeks ago
```
```

**Comment by leezen** [comment]
Odd. Matching your package and plugin versions (gcp 5.10.1 and pulumi 3.6.0), I still can't replicate this. Pulumi will use the Python on the path, so if your shell is in a `venv` it should pick that up. Are you able to reproduce this in an environment from scratch?

**Comment by oliverdain** [comment]
@leezen I just created a new venv and re-ran it. This time the `Dataset` creation worked but creating a table in that `Dataset` failed with:

```
googleapi: Error 400: Invalid dataset ID "projects/verytemporary/datasets/product_metrics". Dataset IDs must be alphanumeric (plus underscores and dashes) and must be at most 1024 characters long., invalid
```

I suspect that's because I'm passing the returned `Dataset.id` as the id and that is the fully qualified id not just the name part. I should have been passing the `Dataset.dataset_id` which is just the name.

I'm a bit confused as I'm fairly sure the `Dataset` creation failed initially but the data seems to show I'm mistaken and it was the table in the dataset that failed so I'll close. Sorry for having wasted your time.
