### ISSUE TITLE
GCP Cloud functions available_memory_mb 8192 not allowed

### ISSUE THREAD

**Issue by awoehrl** [pulumi/pulumi-gcp#609]
Google allows a memory limit of 8GB for cloud functions but Pulumi spits out an error: "Allowed values for memory (in MB) are: 1024,2048,4096,128,256,512 . Got 8192"

## Steps to reproduce
`fxn = pulumi_gcp.cloudfunctions.Function(
        "cf_postgres",
        entry_point="write_dataframe_to_postgres",
        environment_variables=config_values,
        region=Config("gcp").require("region"),
        runtime="python37",
        available_memory_mb=8192,
        timeout=540,
        source_archive_bucket=bucket_cloud_functions.name,
        source_archive_object=bucket_cloud_functions_object[i].name,
        event_trigger=pulumi_gcp.cloudfunctions.FunctionEventTriggerArgs(
            event_type="google.storage.object.finalize", resource=function["bucket"],
        ),
    )`

Expected: Deploy 8GB cloud function
Actual: Error: "Allowed values for memory (in MB) are: 1024,2048,4096,128,256,512 . Got 8192"

**Comment by stack72** [comment]
Hi @awoehrl 

I have just confirmed that I can create a cloudfunction Function with 8GB memory in the latest pulumi-gcp with the following code:

```
fxn = cloudfunctions.Function(
    "eta_demo_function",
    entry_point="get_demo",
    environment_variables=config_values,
    region="us-central1",
    runtime="python37",
    available_memory_mb=8192,
    source_archive_bucket=bucket.name,
    source_archive_object=source_archive_object.name,
    trigger_http=True)
```

I am going to close this out - you will need to be on a newer version of the provider to allow this to happen

Any questions, please let me know

Paul

**Comment by awoehrl** [comment]
Thank you!
There was a  constraint in my requirements file, that I didn't know about:
_`pulumi-gcp>=4.0.0,<5.0.0`_

Removing it solved the issue!

**Comment by stack72** [comment]
Great news :)
