### ISSUE TITLE
Documentation/usage request - how to poll BigQuery job status

### ISSUE THREAD

**Issue by ColeSiegelTR** [pulumi/pulumi-gcp#635]
Hi,

Is there a way to validate that BigQuery jobs deployed from Pulumi are successful?

I’m able to create a job using code from the example here https://www.pulumi.com/docs/reference/pkg/gcp/bigquery/job/ however the Pulumi deployment returns successful whether the job passed or failed.

I see there’s a way to look up an existing job resource and view it’s `statuses` but not sure how I can make it work with polling, as it looks like calling `get` creates a new Pulumi resource with ID and I’d need to potentially check the status many times until the job is done or times out.

Is it possible to provide a code sample or explanation of how I can ensure that the Pulumi deployment does not succeed unless the BigQuery job is completed? Or if this is not possible, it would be helpful to get any other examples of Pulumi code waiting/polling for some custom status checks before completing the deployment.

Thanks a lot for any help.

**Comment by leezen** [comment]
The deployment is successful if the job creation itself is successful (vs. the job passing/failing). You could write code to simply use the ID and the corresponding Google SDK to poll for the status of the job within the apply. So something along the lines of:

```typescript
import { BigQuery } from "@google-cloud/bigquery";

...

const job = new gcp.bigquery.Job("job", {
   ...
});

job.id.apply(id => {
  const bigquery = new BigQuery();
  bigquery.job(id).get(...)
})
```
