### ISSUE TITLE
panic: fatal: An assertion has failed: Expected diff to not require deletion or replacement during Update on imported GKE cluster

### ISSUE THREAD

**Issue by nielsdemoen** [pulumi/pulumi-gcp#639]
When trying to update an imported cluster, it fails with:
 panic: fatal: An assertion has failed: Expected diff to not require deletion or replacement during Update of urn:pulumi:stack::project::gcp:container/cluster:Cluster::mycompany-cluster-staging

In this instance we're updating masterAuthorizedNetworksConfig however updating anything else in the cluster has the same affect.  The stack has two clusters, both exhibit the issue.

## Expected behavior
The object should be updated without an unexpected replacement, at minimum the diff should log what's different that would require a replacement and not an update.

## Current behavior
Panics on updates of the cluster.

## Steps to reproduce
1. Import a GKE cluster
2. Attempt an update.

We have other GKE clusters in another stack which don't have this issue, so the issue is specific to this stack.

**Comment by stack72** [comment]
Hi @nielsdemoen 

Firstly, I need to apologise for the time taken to get back to you on this. Thisnis something we are always trying to get better at.

Secondly, I'm interested in what version of Pulumi and Pulumi-gcp that this happened on - it feels that with the stack trace that this is a very old version - is that correct?

Thanks

Paul
