### ISSUE TITLE
DatabaseInstance replace logic seems wrong

### ISSUE THREAD

**Issue by jam13** [pulumi/pulumi-gcp#65]
Modifying the ipConfiguration setting for an existing DatabaseInstance triggers a replace which obviously results in data loss:
```
const instance = new gcp.sql.DatabaseInstance("master", {
    databaseVersion: "POSTGRES_9_6",
    settings: {
        tier: "db-f1-micro",
        ipConfiguration: {
            authorizedNetworks: [
                {
                    name: "VPN",
                    value: "1.2.3.4",
                },
            ],
        },
    },
});
```

I would expect this to simply update the existing resource's authorised networks.

**Comment by lukehoban** [comment]
That is unexpected - the underlying provider does not mark `ipConfiguration` or `authorizedNetworks` as `ForceNew` so changes to these should not be requiring replacement.

**Comment by lukehoban** [comment]
Yes - for `Cluster#nodeConfig` it is currently expected that that would require replacement.  The underlying reason is this: https://github.com/terraform-providers/terraform-provider-google/blob/51e63bfff2d2acba78bdbb35227669b820a4d61e/google/node_config.go#L26 is marked `ForceNew`, which I expect is ultimately a limitation in the GCP API ([ClusterUpdate does not support updating NodeConfig](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/ClusterUpdate)).

But `DatabaseInstance#settings` does not require replacement (no `ForceNew`).  So it's not clear why Pulumi would be suggesting you need to replace on changes here.

**Comment by jam13** [comment]
It is possible to change the node config in the console however, and as far as I can see this does not replace the cluster as all the resources are restored on the new nodes.

**Comment by lukehoban** [comment]
I suspect this is another case related to https://github.com/pulumi/pulumi-azure/issues/182.

**Comment by lukehoban** [comment]
Confirmed that this is another case of https://github.com/pulumi/pulumi-terraform/issues/329.

From detailed logs - we see:

```
I0302 11:45:45.371898   58867 provider_plugin.go:303] Provider[gcp, 0xc0009600f0].Diff(urn:pulumi:dev::20190226::gcp:sql/databaseInstance:DatabaseInstance::master,master-aa68e7f) success: changes=2 #replaces=[region] #stables=[databaseVersion name masterInstanceName project] delbefrepl=false
```

In particular, the `region` property is what's actually triggering the replacement.  As in the other cases in , this is:

```
			"region": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
				ForceNew: true,
			},
```

Closing this out and will track in that issue instead

**Comment by pgavlin** [comment]
This is in fact another instance of the same class of TF bug seen in 
https://github.com/pulumi/pulumi-aws/issues/451. The schema for `region` that is present in the version of the GCP TF provider that this repo is locked to does not include the `Computed` property: https://github.com/terraform-providers/terraform-provider-google/blob/v1.20.0/google/resource_sql_database_instance.go#L58-L62

**Comment by pgavlin** [comment]
Here's the TF issue: 
https://github.com/terraform-providers/terraform-provider-google/issues/2554

**Comment by alexhwoods** [comment]
Is there any follow up to this?

We're seeing this in version `7.9`
