### ISSUE TITLE
latest github release version not available in pypi

### ISSUE THREAD

**Issue by raphaelauv** [pulumi/pulumi-gcp#661]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

The latest version is 5.22 in the github repo but only 5.20 is available un pypi https://pypi.org/project/pulumi-gcp/

Thank you

**Comment by stack72** [comment]
Hi @raphaelauv 

My apologies - I am not sure what happened, I have just published v5.23.0 to correct the binary issue and can confirm that it's in PyPi

Paul
