### ISSUE TITLE
Service account resource module name wrong in python

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-gcp#668]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

See python example [here](https://www.pulumi.com/docs/reference/pkg/gcp/serviceaccount/account/)

Code looks like:

```python
import pulumi
import pulumi_gcp as gcp

service_account = gcp.service_account.Account("serviceAccount",
    account_id="service-account-id",
    display_name="Service Account")
```

but should be 

```python
import pulumi
import pulumi_gcp as gcp

service_account = gcp.serviceaccount.Account("serviceAccount",
    account_id="service-account-id",
    display_name="Service Account")
```

(`service_account` to `serviceaccount`)

**Comment by remintz** [comment]
This also happens with the code generated on a `pulumi import`. The code is generated with `gcp.service_account.Account` instead of `gcp.serviceaccount.Account`.

**Comment by mnlumi** [comment]
Duplicate of https://github.com/pulumi/pulumi-gcp/issues/722
