### ISSUE TITLE
GCP wrongly deprecated resource types

### ISSUE THREAD

**Issue by rienafairefr** [pulumi/pulumi-gcp#671]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

It seems the 5.24.0 update incorporated deprecation notices coming from the GA terraform provider. 

### Steps to reproduce

create a gcp:runtimeconfig:Variable resource with @pulumi/gcp 5.23.0 => no problem

create a gcp:runtimeconfig:Variable resourcewith @pulumi/gcp 5.24.0 => "Deprecated Resource" warning

```
  gcp:runtimeconfig:Variable (****):
    warning: urn:pulumi:config:push::gcp:runtimeconfig/variable:Variable::**** verification warning: Deprecated Resource
```

Expected: I thought pulumi/gcp used the google-beta TF provider. These resources are beta in gcp so the deprecation only concerns the google TF provider?

Actual: a bunch of deprecation warnings

**Comment by mikhailshilkov** [comment]
The following program works fine today:

```
import * as pulumi from "@pulumi/pulumi";
import * as gcp from "@pulumi/gcp";

const my_runtime_config = new gcp.runtimeconfig.Config("my-runtime-config", {description: "Runtime configuration values for my service"});
const environment = new gcp.runtimeconfig.Variable("environment", {
    parent: my_runtime_config.name,
    text: "example.com",
});
```

I'll resolve the issue as fixed.
