### ISSUE TITLE
Build fails with error: already exists, alreadyExists

### ISSUE THREAD

**Issue by stakauskas** [pulumi/pulumi-gcp#681]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Build fails if Pulumi created instance template before with the message:
```
my-instance-template (my:group$my:my$gcp:compute/instanceTemplate:InstanceTemplate)
error: 1 error occurred:
	* Error creating instance template: googleapi: Error 409: The resource 'projects/my/global/instanceTemplates/my-instance-template-my' already exists, alreadyExists
```

### Steps to reproduce

1. Create instance template / instance group with Pulumi
2. Fail the next build
3. Re-run Pulumi up
4. It will fail the whole run, because instance template already exists.

Expected: if the instance template exist, use it, or skip it.
Actual: fails build completely, which then needs manual interaction in GCP to rename template to `name-1`, move the instance on that new name, delete the template and run `pulumi up` again.

**Comment by leezen** [comment]
Could you describe your step 2 a bit more? Just to confirm, at this point, you've already had a fully successful run of the program? Or is it the case that at this point, the resource has been created via `pulumi up`, but the program is still running and the build fails?

**Comment by rquitales** [comment]
This seems to be a similar error to #680 where the instanceTemplate is attempting to be recreated with exact parameters by Pulumi.  Following the suggestions from https://github.com/pulumi/pulumi-gcp/issues/680#issuecomment-1401114976, `pulumi up --refresh` should help resolve this issue.

Closing out this issue, but please reopen if you're still facing this error.
