### ISSUE TITLE
Getting error: Preview failed: transport is closing when trying to read existing resources.

### ISSUE THREAD

**Issue by atrauzzi** [pulumi/pulumi-gcp#686]
- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm trying to read in the state of existing resources.

[This](https://github.com/pulumi/pulumi-gcp/issues/599) sounds similar, but it's from a while back now.

### Steps to reproduce

```csharp
        var globalDatabaseServer = DatabaseInstance.Get(
            $"{myProject.OrganizationNameShort}-{myProject.EnvironmentNameShort}-{globalRegion.Code}",
            $"{myProject.OrganizationNameShort}-{myProject.EnvironmentNameShort}-{globalRegion.Code}",
            new()
            {
                Project = myProject.Name,
                Region = globalRegion.Location,
            }
        );
        var vpcAccessConnector = Connector.Get(
            globalRegion.Code,
            globalRegion.Code,
            new()
            {
                Region = globalRegion.Location,
            }
        );
```
Expected: Existing resources to be read.
Actual: Error when trying to `up` for both. :boom: 

![image](https://user-images.githubusercontent.com/115199/140638900-e8e6a42a-9b50-4d9d-ae4d-f72fd0483570.png)

**Comment by leezen** [comment]
Often, "transport is closing" is a side effort of some other error causing exceptions to throw. Were there any other errors as part of the output?

**Comment by mikhailshilkov** [comment]
This issue is pretty old and the included snippet doesn't provide a complete repro for the issue (it works fine in isolation). I think I'll go ahead and close the issue as inactionable. If anyone is experiencing a similar issue, please provide us with a repro. Thank you!
