### ISSUE TITLE
compute.Instance: startup_script does not follow exit code

### ISSUE THREAD

**Issue by yellowhat** [pulumi/pulumi-gcp#712]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
Hi,
consider the following example:

```python
import pulumi
from pulumi_gcp import compute

vpc = compute.Network(
    "vpc-test",
    name="vpc-test",
    auto_create_subnetworks=True,
)

vm = compute.Instance(
    "vm",
    name="vm",
    machine_type="n2d-standard-2",
    boot_disk=compute.InstanceBootDiskArgs(
        initialize_params=compute.InstanceBootDiskInitializeParamsArgs(
            image="rocky-linux-cloud/rocky-linux-8",
            type="pd-standard",
            size=20,
        ),
    ),
    network_interfaces=[
        compute.InstanceNetworkInterfaceArgs(
            network=vpc.id,
        )
    ],
    scheduling=compute.InstanceSchedulingArgs(
        automatic_restart=False,
        preemptible=True,
    ),
    metadata_startup_script="exit 0", # exit 99
)
```
I am expecting that pulumi would reflect the exit status of the `startup-script` instead `exit 0` and `exit 99` return the same result (everything is fine and deployed).

To be honest the same example in `gcloud`:
```console
gcloud compute networks create "vpc-test"

gcloud compute instances create vm \
    --image-project rocky-linux-cloud \
    --image-family rocky-linux-8 \
    --machine-type n2d-standard-2 \
    --preemptible \
    --network "vpc-test" \
    --no-address \
    --boot-disk-type pd-standard \
    --metadata startup-script="exit 99"

echo $?
```
Always return exit code 0 no matter `startup-script="exit 99"` or ` startup-script="exit 0"`.

Thanks

**Comment by leezen** [comment]
I'm not sure there's any way around this and this should be likely considered as "by design" -- reading the output status of the script depends on connectivity to the instance itself, which is highly dependent upon the way the instance's network is configured.
