### ISSUE TITLE
GCP AppEngine - traffic not migrated to new version

### ISSUE THREAD

**Issue by LouisSayers** [pulumi/pulumi-gcp#718]
## Hello!
- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
When updating the AppEngine version, a new version is created, however you have to manually migrate traffic to the new version. Only once you've done that will the old version be deleted as well.

### Steps to reproduce
My configuration for AppEngine is as follows:
```
const appEngineBackend = new gcp.appengine.StandardAppVersion("appengine-backend", {
  versionId: pulumi.interpolate`v${currentVersion}`,
  service: "my-app-engine-service",
  deleteServiceOnDestroy: false,
  runtime: "go115",
  deployment: {
    zip: {
      sourceUrl: pulumi.interpolate`https://storage.googleapis.com/${bucketDeploys.name}/backend/latest.zip`,
    },
  },
  envVariables: {
    "ENVIRONMENT": envName,
  },  automaticScaling: {
    maxConcurrentRequests: 10,
    minIdleInstances: 0,
    maxIdleInstances: 3,
    minPendingLatency: "1s",
    maxPendingLatency: "5s",
    standardSchedulerSettings: {
      targetCpuUtilization: 0.5,
      targetThroughputUtilization: 0.75,
      minInstances: 0,
      maxInstances: 10,
    },
  },
});
```

Expected: When I update `currentVersion` to a new version, I expect a new AppEngine version to be created, and for traffic to be migrated to the new version. I expect once this happens for the old version to be deleted (as it's no longer referenced). 

Actual: A new version is created, however traffic is not migrated to this new version. Because traffic has not been migrated, pulumi is unable to delete the old version. This means that the flow of creating a new AppEngine version cannot be automated entirely with pulumi.

**Comment by leezen** [comment]
I don't think the resource can be used quite in this way to get any kind of automated migration. You'll need to maintain two separate `StandardAppVersion` resources and route traffic (via https://www.pulumi.com/registry/packages/gcp/api-docs/appengine/enginesplittraffic/) as appropriate.
