### ISSUE TITLE
`get` seems to require name in too many places

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-gcp#72]
This does not work:

```typescript
gcp.container.Cluster.get("<cluster-name>", "<cluster-name>", {
    project: "<project-name>"
});

```

but this does:

```typescript
gcp.container.Cluster.get("<cluster-name>", "<cluster-name>", {
    name: "<cluster-name>",
    project: "<project-name>"
});
```

this is confusing -- why is `name` required. Is this the desired behavior?

**Comment by geekflyer** [comment]
@hausdorff isn't this a duplicate of #48  ?

**Comment by lukehoban** [comment]
I strongly suspect this is a duplicate of #48 and that it was fixed with the latest release of the `@pulumi/gcp` provider.   If you are still seeing issues with the latest fee free to reopen.
