### ISSUE TITLE
Golang sdk, serviceAccount package not exists, should be "serviceaccount". 

### ISSUE THREAD

**Issue by Mistic92** [pulumi/pulumi-gcp#722]
I'm trying to follow [docs ](https://www.pulumi.com/registry/packages/gcp/api-docs/serviceaccount/account/)but I can't use given package and it's not available in package repository

When trying to use  serviceaccount package I'm getting
```
github.com/pulumi/pulumi-gcp/sdk/v6/go/gcp/serviceAccount: module github.com/pulumi/pulumi-gcp/sdk/v6@latest found (v6.7.0), but does not contain package github.com/pulumi/pulumi-gcp/sdk/v6/go/gcp/serviceAccount
```

https://www.pulumi.com/registry/packages/gcp/api-docs/serviceaccount/account/

Also it's not available there
https://pkg.go.dev/github.com/pulumi/pulumi-gcp/sdk/v6@v6.5.0/go/gcp/serviceAccount

Looks like bug in tutorial as correct name is `serviceaccount`
https://pkg.go.dev/github.com/pulumi/pulumi-gcp/sdk/v6@v6.5.0/go/gcp/serviceaccount

**Comment by salineselin** [comment]
I ran into this issue as well when I imported a serviceaccount. the outputted code declared the go module as `serviceAccount` instead of `serviceaccount`

**Comment by burmecia** [comment]
Got same issue and the example on this page https://www.pulumi.com/registry/packages/gcp/api-docs/serviceaccount/account/ is also wrong:

```
import * as pulumi from "@pulumi/pulumi";
import * as gcp from "@pulumi/gcp";

const serviceAccount = new gcp.serviceAccount.Account("service_account", {
    accountId: "service-account-id",
    displayName: "Service Account",
});
```

It should be:

```
const serviceAccount = new gcp.serviceaccount.Account("service_account", {
    accountId: "service-account-id",
    displayName: "Service Account",
});
```

**Comment by shadiramadan** [comment]
Seriously still not fixed... The schema.json is full of issues.  I found a few typos for some other resources as well.

**Comment by anilkumarnm** [comment]
Still not fixed :-(
