### ISSUE TITLE
GetZoneArgs requires *string whereas most other args take pulumi.String()

### ISSUE THREAD

**Issue by eahrend** [pulumi/pulumi-gcp#725]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I'd like there to be consistency between all of the fooArgs structs. For example, compute.RouterNatArgs allows me to pass a project ID from organizations.Project

```GO
type RouterNatArgs struct {
        // trimming the other inputs for 
	Project pulumi.StringPtrInput
	Region pulumi.StringPtrInput
}

```

This allows me to take the outputs from organizations.Project and input it relatively easily, however the GetZoneArgs requests a pointer to a string, so while I'm sure there is a way around this, passing in an organizations.Project.ProjectID isn't as intuitive as the other fooArgs structs.

```GO
type GetZonesArgs struct {
	// Project from which to list available zones. Defaults to project declared in the provider.
	Project *string `pulumi:"project"`
	// Region from which to list available zones. Defaults to region declared in the provider.
	Region *string `pulumi:"region"`
	// Allows to filter list of zones based on their current status. Status can be either `UP` or `DOWN`.
	// Defaults to no filtering (all available zones - both `UP` and `DOWN`).
	Status *string `pulumi:"status"`
}
```

My suggestion would be to switch the *string fields to pulumi.StringPtrInput fields.

### Affected area/feature
This is specific to the GCP Golang library

**Comment by t0yv0** [comment]
I believe https://github.com/pulumi/pulumi-gcp/blob/15e67d6cdb99770e65642bbc067b6b67d301ce5d/sdk/go/gcp/compute/getZones.go#L56 takes care of this.
