### ISSUE TITLE
GCP Edgecache service deployment fails with ""defaultTtl must not be set when cacheMode is USE_ORIGIN_HEADERS or BYPASS_CACHE."

### ISSUE THREAD

**Issue by sghosh-discovery** [pulumi/pulumi-gcp#742]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I try to deploy Cloud Media Edge from pulumi, and it randomly fails with the following error:

Config validation failed"  details:{[type.googleapis.com/google.rpc.BadRequest]:{field_violations:{field:"resource.routing.path_matchers[0].route_rules[0].route_action.cdn_policy.default_ttl"  description:"defaultTtl must not be set when cacheMode is USE_ORIGIN_HEADERS or BYPASS_CACHE."}}

But the code does not even have defaultTTL set.
### Steps to reproduce

1.
2.
3.
4.

Expected: 
Actual:

**Comment by mikhailshilkov** [comment]
Since we have no repro, and the issue is quite old, I'll go ahead and close it.
