### ISSUE TITLE
[GCP] CloudBuild `availableSecrets` does not exists

### ISSUE THREAD

**Issue by xskif** [pulumi/pulumi-gcp#743]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue 
`availableSecrets` and `secretEnv` props does not exists in `gcp.cloudbuild.Trigger`

**Comment by mikhailshilkov** [comment]
Both `availableSecrets` and `secretEnvs` are now available, see https://www.pulumi.com/registry/packages/gcp/api-docs/cloudbuild/trigger/#available_secrets
