### ISSUE TITLE
[Bug] availableSecrets prop not present in TriggerBuild type definition

### ISSUE THREAD

**Issue by xskif** [pulumi/pulumi-gcp#745]
File: [themes/default/content/registry/packages/gcp/api-docs/cloudbuild/trigger/_index.md](https://www.pulumi.com/registry/packages/gcp/api-docs/cloudbuild/trigger/)

So as the title says there is a type-checking issue. I can't add "availableSecrets" prop, cause I get an error: "Object literal may only specify known properties and 'availableSecrets' does not exist in type '`Input<TriggerBuild>`'"

Meanwhile, "availableSecrets" property is documented.

**Comment by danielrbradley** [comment]
Which language are you seeing this behaviour? It looks like it might be Typescript?

Please could you provide a minimal sample of code that shows this build error?

Here's a minimal sample which passes the Typescript build:

```typescript
import * as gcp from "@pulumi/gcp";

new gcp.cloudbuild.Trigger("trigger", {
  build: {
    steps: [],
    availableSecrets: {
      secretManagers: [
        {
          env: "MY_SECRET",
          versionName: "projects/myProject/secrets/mySecret/versions/latest",
        },
      ],
    },
  },
});
```

**Comment by danielrbradley** [comment]
Please could you share which version of the `@pulumi/gcp` SDK package you're referencing. The above was tested with `v6.12.0`

**Comment by xskif** [comment]
I have `5.26.0`
I can't install `6.12.0`. For some reason `npm i @pulumi/gcp` installs `5.26.0`

**Comment by xskif** [comment]
So, ok, I've installed a specific version, and it's works
Thanks
