### ISSUE TITLE
Missing gcp.cloudtasks.QueueIamPolicy?

### ISSUE THREAD

**Issue by cakoose** [pulumi/pulumi-gcp#747]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm defining a GCP Cloud Tasks queue:

```ts
const defaultQueue = new gcp.cloudtasks.Queue('background-jobs-default', {
    location: location,
});
```

I need to grant my service account the "roles/cloudtasks.enqueuer" role on that specific queue.

With other resources types, there's a corresponding `IamPolicy` class I can use to grant a service account access to the resource. For example:
- For `gcp.storage.Bucket`, I use `gcp.storage.BucketIamPolicy`.
- For `gcp.secretmanager.Secret`, I use `gcp.secretmanager.SecretIamPolicy`.

There's no corresponding `gcp.cloudtasks.QueueIamPolicy` to grant my service account access to enqueue.

Is there some other way to define the IamPolicy for a single queue?

The new "Google Native" Pulumi API has [cloudtasks.v2.QueueIamPolicy](https://www.pulumi.com/registry/packages/google-native/api-docs/cloudtasks/v2/queueiampolicy/). Do I have to switch my entire infrastructure over to that?

### Steps to reproduce

N/A

**Comment by danielrbradley** [comment]
This doesn't appear to be supported in the upstream terraform provider. This would have to be implemented there before it can be supported in Pulumi. There doesn't appear to be [an open issue in terraform](https://github.com/hashicorp/terraform-provider-google/issues?q=is%3Aissue+is%3Aopen+QueueIamPolicy).

Yes this is available in our google-native provider. You wouldn't have to switch all your infrastructure over as you can use multiple providers in a single project. Therefore you could just use the QueueIamPolicy from the google-native provider and keep all your existing infrastructure using this provider.
