### ISSUE TITLE
Pulumi refresh : gcp:projects:IAMMember -> update [diff: ~etag] | ALL resource

### ISSUE THREAD

**Issue by raphaelauv** [pulumi/pulumi-gcp#751]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

running `pulumi refresh` on a stack without any change always update ALL my IAMMember ( I have 291 IAMMember in my stack )
because the etag "changed"

So every pulumi refresh show me

```log
    ~ 291 to update
    46 unchanged
```

### Steps to reproduce

```python
gcp.projects.IAMMember("iam_member_bigquery.admin_XXXXXXXX@XXXXXXXX.com",
                       member="user:XXXXXXXXX@XXXXXX.com",
                       project=PROJECT,
                       role="roles/bigquery.admin",
                       opts=pulumi.ResourceOptions(parent=ALL_RESOURCE, protect=True))
                          
```

in the "details" of pulumi refresh it show me

```log
~ gcp:projects/iAMMember:IAMMember: (update) 🔒
    [id=XXXXXXXXXXX/roles/bigquery.admin/user:XXXXXXX@XXXXXXX.com]
    [urn=urn:pulumi:XXXXXX-prod::XXXXX::gcp:component:all_resource$gcp:projects/iAMMember:IAMMember::iam_member_bigquery.admin_XXXXXXXX@XXXXXXXXstore.com]
    [provider=urn:pulumi:XXXXXXXXX-prod::XXXXX::pulumi:providers:gcp::default_gcp::XXX-XXXXXX-XXXXXX-XXXXX]
    --outputs:--
  ~ etag     : "BwXXqDCxmSw=" => "BwXYJjvSbgA="

```

If I enter YES then

```log
Resources:
    ~ 291 updated
    46 unchanged

Duration: 1m47s
```

**Comment by danielrbradley** [comment]
Hi, thanks for writing this up.

What's the impact of accepting the updated etag apart from the resources in the stack being updated?
- Does this cause all resources to be updated on the next deployment?
- Is there a knock on impact in your process if you detect resources being changed?

**Comment by mjeffryes** [comment]
Unfortunately, it looks like this issue hasn't seen any updates in a while. If you're still encountering this problem, could you leave a quick comment to let us know so we can prioritize it?

**Comment by raphaelauv** [comment]
I'm no longer using gcp and pulumi so I don't know but my example was reproductible

**Comment by mjeffryes** [comment]
I suspect we would have heard a lot more complaints by now if it was still a problem, but we'll take a moment to try to repro on latest.

**Comment by VenelinMartinov** [comment]
This no longer reproes on the latest pulumi-gcp
