### ISSUE TITLE
Support serverless_deployment from upstream terraform provider for Network Endpoint groups for API Gateway

### ISSUE THREAD

**Issue by knowhoper** [pulumi/pulumi-gcp#755]
Hi, 

The following code does not work - I am trying to load balance to API Gateway which proxies Cloud Run, to do so I need to create a serverless NEG for the API Gateway instance. 

```
import * as gcp from '@pulumi/gcp';
import * as pulumi from '@pulumi/pulumi';
import { id as managedCertId } from '../certs'
import { ipv4Address } from '../addresses'
import { wGw } from '../../apigateway'

console.log('default hostame', wGw);

const apiGwGatewayNEG = new gcp.compute.RegionNetworkEndpointGroup('api-gw-rneg', {
    networkEndpointType: 'SERVERLESS',
    region: 'australia-southeast1',
    cloudRun: {
        service: wGw.defaultHostname,
        urlMask: '/'
    }
});


 // HTTP-to-HTTPS resources
 const defaultBackendService = new gcp.compute.BackendService('defaultBackendService', {
    name: `${pulumi.getStack()}-api-gw-backend`,
    protocol: 'HTTP',
    portName: 'http',
    timeoutSec: 30,
    backends: [{
        group: apiGwGatewayNEG.id
    }],
});

const defaultURLMap = new gcp.compute.URLMap('defaultURLMap', {
   name: `${pulumi.getStack()}-api-gw-urlmap`,
   defaultService: defaultBackendService.id,
});


const defaultTargetHttpsProxy = new gcp.compute.TargetHttpsProxy('defaultTargetHttpsProxy', {
   name: `${pulumi.getStack()}-api-gw-https-proxy`,
   urlMap: defaultURLMap.id,
   sslCertificates: [ managedCertId ],
});

const defaultGlobalForwardingRule = new gcp.compute.GlobalForwardingRule('defaultGlobalForwardingRule', {
   name: `${pulumi.getStack()}-api-gw-fwdrule`,
   target: defaultTargetHttpsProxy.id,
   portRange: '443',
   ipAddress: ipv4Address,
});

const httpsRedirectURLMap = new gcp.compute.URLMap('httpsRedirectURLMap', {
   name: `${pulumi.getStack()}-api-gw-http-https-redirect`,
   defaultUrlRedirect: {
       httpsRedirect: true,
       redirectResponseCode: 'MOVED_PERMANENTLY_DEFAULT',
       stripQuery: false,
   },
});

const httpsRedirectTargetHttpProxy = new gcp.compute.TargetHttpProxy('httpsRedirectTargetHttpProxy', {
   name: `${pulumi.getStack()}-api-gw-http-proxy`,
   urlMap: httpsRedirectURLMap.id,
});

const httpsRedirectGlobalForwardingRule = new gcp.compute.GlobalForwardingRule('httpsRedirectGlobalForwardingRule', {
   name: `${pulumi.getStack()}-api-gw-fwdrule-http`,
   target: httpsRedirectTargetHttpProxy.id,
   portRange: '80',
   ipAddress: ipv4Address
});

export let backend = defaultBackendService;`

```

Looking at the [terraform provider](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_network_endpoint_group#serverless_deployment) this is possible using the `serverless_deployment` block, but this is unsupported in the Pulumi library. 

Is this possible? The error i receive is :

>  * Error creating RegionNetworkEndpointGroup: googleapi: Error 400: Invalid value for field 'resource.cloudRun.service': 'web-api-gw-caoqub4m.ts.gateway.dev'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)', invalid
 

 
 Any help would be much appreciated. 

Cheers
KH

**Comment by viveklak** [comment]
You should be able to specify a `RegionNetworkEndpointGroupServerlessDeployment` to  `serverlessDeployment` field to mimic the behavior from terraform.

**Comment by knowhoper** [comment]
Hi, thanks for your response. That type does not exist, nor does that field and searching online is not yielding any results. Would you mind linking the library where those exist?

**Comment by viveklak** [comment]
https://www.pulumi.com/registry/packages/gcp/api-docs/compute/regionnetworkendpointgroup/#serverlessdeployment_nodejs
you will need to import it from @pulumi/gcp's `types/output`. Perhaps you are running an older version of the pulumi-gcp sdk?

**Comment by knowhoper** [comment]
Yes, thank you this was exactly the issue. I have it now, much appreciated.  👍
