### ISSUE TITLE
RouterNat Dynamic Port Allocation support

### ISSUE THREAD

**Issue by Faithtosin** [pulumi/pulumi-gcp#764]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
[CloudNAT dynamic port allocation](https://cloud.google.com/nat/docs/ports-and-addresses#dynamic-port) is now generally available. An option to set the maximum number of ports per VM instance is missing on the [RouterNat Pulumi resource](https://www.pulumi.com/registry/packages/gcp/api-docs/compute/routernat/#:~:text=RouterNat-,RouterNat,-A%20NAT%20service).

**Comment by jkodroff** [comment]
@Faithtosin Thanks for submitting this issue. We're waiting on the Terraform provider to add this feature. Unfortunately, there's no way I'm aware of to submit a feature request to the upstream provider (Google disables GitHub issues on all relevant repos), so it's just a matter of waiting until they implement.

**Comment by Faithtosin** [comment]
@jkodroff  Thanks for the update. I found [this issue](https://github.com/hashicorp/terraform-provider-google/issues/11052) tracking the feature already.
