### ISSUE TITLE
Add a link to documentation for configuring the GCP Provider

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi-gcp#78]
@clstokes pointed me to a page on the Pulumi website which neatly documents how to configure the provider - we should consider adding a link to the README in this repository.

**Comment by clstokes** [comment]
I believe James is referring to this page - https://pulumi.io/quickstart/gcp/setup.html.

**Comment by joeduffy** [comment]
Definitely like this idea -- for all providers. Our "GitHub first" onboarding isn't great and this would help.
