### ISSUE TITLE
`Invalid address to set: []string{"cluster_autoscaling"}` with `0.16.4`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-gcp#79]
Users of the latest release of this provider have noted that they see errors when creating `gcp.container.Cluster` resources:

```
Invalid address to set: []string{"cluster_autoscaling"}
```

This will happen even after downgrading back to the `0.16.3` version of the NPM package because it affects the provider binary itself which will always load latest.  `pulumi plugin rm resource gcp 0.16.4` can likely fix this in the short term.

**Comment by sylv3r** [comment]
I can confirm this fix the problem.

**Comment by jen20** [comment]
I can reproduce this using the `gcp-ts-gke` example from pulumi/examples. Digging in now to find why this is broken.

**Comment by jen20** [comment]
The error itself is originating in the `helper/schema` library of Terraform, in [MapFieldWriter::WriteField](https://github.com/hashicorp/terraform/blob/master/helper/schema/field_writer_map.go#L64).

My first guess is that we have a problem with how we deal with Removed fields in the Terraform bridge.
