### ISSUE TITLE
url mask for RegionNetworkEndpointGroupServerlessDeployment should be optional 

### ISSUE THREAD

**Issue by knowhoper** [pulumi/pulumi-gcp#798]
### What happened?

A feature in the terraform provider isn't supported

### Steps to reproduce

Go here: https://github.com/hashicorp/terraform-provider-google/issues/11242

### Expected Behavior

URL Mask should be optional

### Actual Behavior

URL mask is mandatory

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Narrayahodeir** [comment]
Works now with the release v6.21.0 but there is another issue with creating a resource without the urlMask property: https://github.com/pulumi/pulumi-gcp/issues/804

**Comment by knowhoper** [comment]
Thanks for the update!  Hopefully resolved soon🤞
