### ISSUE TITLE
RegionNetworkEndpointGroup: Invalid value for field 'resource.creationTimestamp'

### ISSUE THREAD

**Issue by Narrayahodeir** [pulumi/pulumi-gcp#804]
### What happened?

I want to create a serverless NEG with the compute.RegionNetworkEndpointGroup resource (NodeJS SDK) and get the following error:

"Error creating RegionNetworkEndpointGroup: googleapi: Error 400: Invalid value for field 'resource.creationTimestamp': ''. Must be a match of regex '(?:[0-9a-z][0-9a-z-]{0,48})'., invalid"

The creation timestamp looks empty and isn't valid.

### Steps to reproduce

The following resource is being used:

```
const networkEndpointGroup = new gcp.compute.RegionNetworkEndpointGroup(
  'network-endpoint-group',
  {
    name: `${prefix}-neg`,
    region: gcpRegion,
    networkEndpointType: 'SERVERLESS',
    serverlessDeployment: {
      platform: 'apigateway.googleapis.com',
      resource: apiGateway.id,
    },
  }
);
```

### Expected Behavior

I expect a valid creationTimestamp and the resource being created successfully.

### Actual Behavior

After issuing `pulumi up` this error appears:

"Error creating RegionNetworkEndpointGroup: googleapi: Error 400: Invalid value for field 'resource.creationTimestamp': ''. Must be a match of regex '(?:[0-9a-z][0-9a-z-]{0,48})'., invalid"

And the resource isn't being created.

### Versions used

CLI          
Version      3.30.0
Go Version   go1.18.1

Plugins
NAME    VERSION
nodejs  16.14.0

Host     
OS       darwin
Version  12.3.1
Arch     x86_64

Name
@pulumi/google-native                         0.18.1
@pulumi/gcp                                   6.21.0

### Additional context

If I change `resource: apiGateway.id,` to `urlMask: '<gateway>'` the resource is being created. But I need the `resource` property.

With the "gcloud beta SDK" the resource can be created with the required properties (with resource instead urlmask).

The same behaviour is experienced with the google-native provider version 0.18.1.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by knowhoper** [comment]
👍

**Comment by guineveresaenger** [comment]
Tank you for filing this issue!

**Comment by mylesdavittcarma** [comment]
👍

**Comment by shaariqch** [comment]
👍

**Comment by knowhoper** [comment]
Is there any update on this issue? @Narrayahodeir

**Comment by Narrayahodeir** [comment]
> Is there any update on this issue? @Narrayahodeir

Not from my site. I guess this is an upstream issue and needs to be addressed there.

**Comment by norbertkeri** [comment]
This is mentioned in the linked issue on the pulumi project, but I'll say it here in case people don't notice it:

The error message is misleading, it actually has nothing to do with the creation timestamp. You are supposed to use the `display_name` property of the api gateway you are trying to link to, not the id (and not the name).

This will work:

```hcl
  serverless_deployment {
    platform = "apigateway.googleapis.com"
    resource = google_api_gateway_gateway.gw_gw.display_name // <- use this, instead of .id
  }
```

I'm still puzzled on why this particular API works like this, since the gcloud commands accept the id, not the display name.

**Comment by szwalkowski** [comment]
Have exactly same problem, google version 4.55.0, terraform 1.3.9

> Error: Error creating RegionNetworkEndpointGroup: googleapi: Error 400: Invalid value for field 'resource.creationTimestamp': ''. Must be a match of regex '(?:[0-9a-z][0-9a-z-]{0,48})'., invalid


```
resource "google_compute_region_network_endpoint_group" "api_anonymous_neg" {
  provider              = google-beta
  project               = var.v_gcp_project
  name                  = "api-anonymous-neg"
  region                = var.v_gcp_region
  network_endpoint_type = "SERVERLESS"
  serverless_deployment {
    platform = "apigateway.googleapis.com"
    resource = google_api_gateway_api.api_anonymous_gateway.id
  }
}
```
resource tried with google_api_gateway_gateway also - cause not clear what id for me from documentation. Either way, it does not work

**Comment by Mankee** [comment]
👍

**Comment by rshade** [comment]
I have ran your code, and it seems to work now. Can you check and see if its still broken on your side?

**Comment by Narrayahodeir** [comment]
> I have ran your code, and it seems to work now. Can you check and see if its still broken on your side?

Thanks Richard for verifying. Unfortunately I don't have access to the code anymore. I think we can close the issue since you tested it successfully.
