### ISSUE TITLE
Fix service account namespace

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-gcp#811]
We have multiple reports of the service account namespace rendering incorrectly, which also causes 404's in the registry:

* https://github.com/pulumi/pulumi-gcp/issues/722
* https://github.com/pulumi/registry/issues/758
* https://github.com/pulumi/pulumi-gcp/issues/668
* https://github.com/pulumi/pulumi-gcp/issues/580

Need to discuss internally, since this is technically a breaking change. The module name looks correct, but we need to look into what removing [this block of code](https://github.com/pulumi/pulumi-gcp/blob/master/provider/resources.go#L115-L119) would do and figure out a release strategy, since this is technically a breaking change (although I'm not sure of how many users it would affect).

**Comment by mnlumi** [comment]
Duplicate of https://github.com/pulumi/pulumi-gcp/issues/722
