### ISSUE TITLE
Not able to create a ServiceAttachment to Elastic Cloud

### ISSUE THREAD

**Issue by tleung999** [pulumi/pulumi-gcp#840]
### What happened?

I am trying to create a ServiceAttachment using this documentation - https://www.pulumi.com/registry/packages/gcp/api-docs/compute/serviceattachment/#serviceattachment.   The [Elastic Cloud documentation](https://www.elastic.co/guide/en/cloud/current/ec-traffic-filtering-psc.html) states that I need to add the Service Attachment URI as my Target Service.   

I am using us-east4 so the URI would be `projects/cloud-production-168820/regions/us-east4/serviceAttachments/proxy-psc-production-us-east4-v1-attachment`.   I tried creating the serviceAttachment using the following block.

```
this.pscendpoint = new gcp.compute.ServiceAttachment("elastic-psc-endpoint", {
            connectionPreference: "ACCEPT_AUTOMATIC",
            enableProxyProtocol: true,
            natSubnets: ["myprivatesubnet"],
            targetService: "projects/cloud-production-168820/regions/us-east4/serviceAttachments/proxy-psc-production-us-east4-v1-attachment",
            region: "us-east4"
        });
```

The error I am getting is as follows
```
Diagnostics:
  gcp:compute:ServiceAttachment (elastic-psc-endpoint):
    error: 1 error occurred:
    	* Error creating ServiceAttachment: googleapi: Error 404: The resource 'projects/peek-prod/regions/us-east4/forwardingRules/proxy-psc-production-us-east4-v1-attachment' was not found, notFound

  pulumi:pulumi:Stack (infrastructure-gcp-prod):
    error: update failed
``` 

I also used the actual full URL `https://compute.googleapis.com/compute/v1/projects/cloud-production-168820/regions/us-east4/serviceAttachments/proxy-psc-production-us-east4-v1-attachment` but I still get the same above error.

When I manually create the endpoint through the GCP UI I dont have any issues (see screenshot)
<img width="580" alt="Screen Shot 2022-06-29 at 8 02 34 PM" src="https://user-images.githubusercontent.com/4137142/176584029-1c4994bc-5a71-4dd7-8b08-cbd7104928ab.png">

I see no where in the documentation where I can declare  `All Google APIs`, `VPC-SC`, or `Published service` as an input for the resource creation.  Am I looking at the right resource to build what I see in the screenshot?   The resource points to a [How to Guide](https://cloud.google.com/vpc/docs/configure-private-service-connect-services#console) that points to the exact doc I used to create the endpoint.   Or is this capability not available for this resource yet.

### Steps to reproduce

Use this block

```
this.pscendpoint = new gcp.compute.ServiceAttachment("elastic-psc-endpoint", {
            connectionPreference: "ACCEPT_AUTOMATIC",
            enableProxyProtocol: true,
            natSubnets: ["myprivatesubnet"],
            targetService: "projects/cloud-production-168820/regions/us-east4/serviceAttachments/proxy-psc-production-us-east4-v1-attachment",
            region: "us-east4"
        });
```

### Expected Behavior

Expect the endpoint to be created and I will get a `PSC Connection ID`

### Actual Behavior

The error I am getting is as follows
```
Diagnostics:
  gcp:compute:ServiceAttachment (elastic-psc-endpoint):
    error: 1 error occurred:
    	* Error creating ServiceAttachment: googleapi: Error 404: The resource 'projects/peek-prod/regions/us-east4/forwardingRules/proxy-psc-production-us-east4-v1-attachment' was not found, notFound

  pulumi:pulumi:Stack (infrastructure-gcp-prod):
    error: update failed
``` 

### Versions used

❯ pulumi about
CLI
Version      3.35.1
Go Version   go1.18.3
Go Compiler  gc

Plugins
NAME        VERSION
ec          0.4.1
gcp         5.15.0
kubernetes  3.6.0
nodejs      unknown

Host
OS       darwin
Version  12.2.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v18.4.0'

Dependencies:
NAME                VERSION
@pulumi/kubernetes  3.6.0
@pulumi/pulumi      3.9.1
@types/node         10.17.60
@pulumi/ec          0.4.1
@pulumi/gcp         5.15.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tleung999** [comment]
Took a closer look at the google documenation https://cloud.google.com/vpc/docs/configure-private-service-connect-services#api and saw the API call was using ForwardingRule.  Sample they used are as follows.

```
POST https://compute.googleapis.com/compute/v1/projects/PROJECT_ID/regions/REGION/forwardingRules
{
  "name": ENDPOINT_NAME,
  "IPAddress": ADDRESS_URI,
  "target": SERVICE_ATTACHMENT,
  "network": NETWORK_URI,
  "serviceDirectoryRegistrations": [
      {
          "namespace": NAMESPACE,
      }
  ],
}
```

Strange thing I found when using the ForwardingRule resource https://www.pulumi.com/registry/packages/gcp/api-docs/compute/forwardingrule/ is that it is  default setting the `resource.loadBalancingScheme` to `EXTERNAL`.

```
  gcp:compute:ForwardingRule (elastic-cloud-forwarding-rule):
    error: 1 error occurred:
    	* Error creating ForwardingRule: googleapi: Error 400: Invalid value for field 'resource.loadBalancingScheme': 'EXTERNAL'. Invalid field set in Private Service Connect Forwarding Rule. This field should not be set., invalid
```

My forwardingRule resource looks like the following.
```
        this.forwardingrule = new gcp.compute.ForwardingRule("elastic-cloud-forwarding-rule", {
            name: "prod-to-elastic-cloud",
            ipAddress: this.privateip.id,
            network: "prod-network",
            target: "projects/cloud-production-168820/regions/us-east4/serviceAttachments/proxy-psc-production-us-east4-v1-attachment",
            subnetwork: "prod-network-private-us-east4",
        });
```

Do you know why this is forcing the default "EXTERNAL" loadBalancingScheme when it is not needed for this type of call?

**Comment by tleung999** [comment]
Ok so I have a half baked solution to this.   In order to make it `null` in Typescript I did the following (removed subnetwork since i didnt need it)

```
        this.forwardingrule = new gcp.compute.ForwardingRule("elastic-cloud-forwarding-rule", {
            name: "prod-to-elastic-cloud",
            ipAddress: this.privateip.id,
            network: "prod-network",
            target: "projects/cloud-production-168820/regions/us-east4/serviceAttachments/proxy-psc-production-us-east4-v1-attachment",
            loadBalancingScheme: ""
        });
```

Doing the above allowed me to create the Private Service Connection.   I like to still leave this opened so someone can address the forced default of "EXTERNAL" for the `resource.loadBalancingScheme` property.

**Comment by tleung999** [comment]
One more issue I found.  Outputs for forwarding rules does not have a way of grabbing the psc connection id.  When I `gcloud compute forwarding-rules describe prod-to-elastic-cloud` you will see a `pscConnectionId` with value.   

```
❯ gcloud compute forwarding-rules describe prod-to-elastic-cloud
IPAddress: 10.111.11.11
creationTimestamp: '2022-06-30T09:31:54.437-07:00'
id: '1461040554611601999'
kind: compute#forwardingRule
labelFingerprint: 99WmApB8rSM=
name: prod-to-elastic-cloud
network: https://www.googleapis.com/compute/v1/projects/prod/global/networks/prod-network
networkTier: PREMIUM
pscConnectionId: '42053171111487666'
pscConnectionStatus: ACCEPTED
region: https://www.googleapis.com/compute/v1/projects/prod/regions/us-east4
selfLink: https://www.googleapis.com/compute/v1/projects/prod/regions/us-east4/forwardingRules/prod-to-elastic-cloud
serviceDirectoryRegistrations:
- namespace: goog-psc-default
target: https://www.googleapis.com/compute/v1/projects/cloud-production-168820/regions/us-east4/serviceAttachments/proxy-psc-production-us-east4-v1-attachment
```

`forwardingrule.id` will return the URI of the ForwardingRule.

**Comment by lblackstone** [comment]
> Do you know why this is forcing the default "EXTERNAL" loadBalancingScheme when it is not needed for this type of call?

The [docs for this resource](https://www.pulumi.com/registry/packages/gcp/api-docs/compute/forwardingrule/#loadbalancingscheme_nodejs) note that the default is `EXTERNAL`, as well as your other options. Defaults are set by parameter rather than by configuration, so I'd guess that Google's web interface is setting it appropriately behind the scenes.

> One more issue I found. Outputs for forwarding rules does not have a way of grabbing the psc connection id. When I `gcloud compute forwarding-rules describe prod-to-elastic-cloud` you will see a `pscConnectionId` with value.

This looks unrelated to the original issue. If this is still a problem, can you file a separate issue so we don't lose track of it?

**Comment by lblackstone** [comment]
It looks like the original issue was a config problem rather than a bug in the provider, so I'm going to close this as resolved.
