### ISSUE TITLE
Incorrect input name/case for gcp RouterNat

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-gcp#841]
### Problem description

The example at https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/gcp/compute/#example-usage-router-nat-basic is not correct based on the Node SDK - specifically, the example shows `log_config`, but should be `logConfig`.

![image](https://user-images.githubusercontent.com/293763/87632775-e41f6400-c6ee-11ea-8830-604a0addaf92.png)

### Suggestions for a fix

`log_config` should be `logConfig`

**Comment by mikhailshilkov** [comment]
Verified as fixed
<img width="598" alt="image" src="https://github.com/pulumi/pulumi-gcp/assets/1454008/be838054-14da-4882-bd6f-954f781698dc">
