### ISSUE TITLE
Erroneous provider added to `gcp.iam.WorkloadIdentityPool`

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-gcp#843]
https://www.pulumi.com/registry/packages/gcp/api-docs/iam/workloadidentitypool/

```
import * as pulumi from "@pulumi/pulumi";
import * as gcp from "@pulumi/gcp";

const example = new gcp.iam.WorkloadIdentityPool("example", {workloadIdentityPoolId: "example-pool"}, {
    provider: google_beta, // not valid
});
```

**Comment by jkodroff** [comment]
The same issue exists on this page: https://www.pulumi.com/registry/packages/gcp/api-docs/firebase/hostingversion/

**Comment by jkodroff** [comment]
It looks like `WorkloadIdentityPool` is now fixed:

<img width="735" alt="image" src="https://github.com/pulumi/pulumi-gcp/assets/410614/60412dd7-a331-4bf5-ba7a-9cf72c79f2b1">

However, `HostingVersion` and `HostingSite` are still broken:

<img width="747" alt="image" src="https://github.com/pulumi/pulumi-gcp/assets/410614/b4c3b5ad-bd40-4ebe-a455-e1265f7b9f4c">

**Comment by mjeffryes** [comment]
I think this is fixed in all the examples mentioned above
