### ISSUE TITLE
Error setting disabled: Invalid address to set: []string{"disabled"}

### ISSUE THREAD

**Issue by artpogo** [pulumi/pulumi-gcp#850]
### What happened?

When applying sql user for msSQL/PostgreSQL

```
gcp:sql:User (dbname-users):
    error: refreshing urn:pulumi:sandbox::gcp:sql/user:User::dbname-users: 1 error occurred:
    	* Error setting disabled: Invalid address to set: []string{"disabled"}
```

Code used for creating users:
```
import pulumi_gcp as gcp

users = gcp.sql.User(f"{args.database_name}-users",
        instance = db_instance.name,
        project = args.project,
        name = args.db_user_name,
        password = "password"
    )
```

Issue only at refresh step, using `pulumi up --stack sandbox --yes --skip-preview` doesn't result error.
providing:
```
sql_server_user_details=gcp.sql.UserSqlServerUserDetailsArgs(
        disabled=False
)
```
Doesn't resolve issue.

### Steps to reproduce

Apply refresh resources for sql user

### Expected Behavior

Refresh is done, resource is created

### Actual Behavior

Failing to refresh with unclear error.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
We appreciate you bringing this to our attention! It looks like this is a problem with the gcp provider, so I have transferred the issue.

**Comment by mikhailshilkov** [comment]
It seems to be coming from TF: https://github.com/hashicorp/terraform-provider-google/blob/cf3ae1033bfb302bb4d7bbd3d2fba45b0adf5f85/google/resource_sql_user.go#L279

**Comment by Rob-S** [comment]
👍
>> Vote on this issue by adding a 👍 reaction.
I was expecting to see a place in the OP to provide that reaction, but don't see it there anywhere.

**Comment by dstoyanoff** [comment]
Hey guys,
It seems that the upstream issue got fixed. When can we expect that pulumi will be updated and what version should we monitor?

**Comment by viveklak** [comment]
Looks like this will be in the 4.41.0 release of the terraform provider: https://github.com/hashicorp/terraform-provider-google/issues/11891 at which point we will release it as well. Thanks for your patience!

**Comment by dstoyanoff** [comment]
Hello @viveklak, I see 4.41.0 got released a few hours ago. What version of pulumi-gcp do we need to have to receive the fix?

**Comment by viveklak** [comment]
@lblackstone has this in the works in https://github.com/pulumi/pulumi-gcp/pull/929
