### ISSUE TITLE
Erroneous documentation generation

### ISSUE THREAD

**Issue by fergusean** [pulumi/pulumi-gcp#852]
### What happened?

There are 20 instances of `Enable the PodSecurityPolicy controller for this cluster.` in the documentation for https://www.pulumi.com/registry/packages/gcp/api-docs/container/cluster/, all for booleans named `enabled`.  The Terraform docs do not have the issue, so I imagine it's an issue somewhere in the generation of the `schema.json` file, but I'm not 100% sure.

### Steps to reproduce

See [Pulumi docs](https://www.pulumi.com/registry/packages/gcp/api-docs/container/cluster/#managedprometheus_nodejs) vs [Terraform docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#nested_managed_prometheus).

### Expected Behavior

<img width="596" alt="image" src="https://user-images.githubusercontent.com/1029297/178604551-988cd5af-f1ee-48fe-80c8-f3deb8bbf3d0.png">

[Terraform sources](https://github.com/hashicorp/terraform-provider-google-beta/blob/9f70c9ca27a2a0b1070ba09d7d23f0550718717f/google-beta/resource_container_cluster.go#L802)

### Actual Behavior

<img width="781" alt="image" src="https://user-images.githubusercontent.com/1029297/178604541-288625e1-b772-4230-a592-8df3ea08412e.png">

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
@jkodroff is this related to or the same as the wider issue in the TF bridge you were already looking at?

**Comment by danielrbradley** [comment]
After discussing internally this is definitely cause by the issue documented in TF Bridge, so closing this issue as a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/529
