### ISSUE TITLE
.apply throws too late

### ISSUE THREAD

**Issue by gunar** [pulumi/pulumi-gcp#859]
### What happened?

This code throws `TypeError: Cannot read properties of undefined (reading 'url')` whereas I want to make it so that Pulumi understands that `service` was never successfully deployed in the first place:

```js
const service = new gcp.cloudrun.Service(…);
const url = service.statuses.apply((statuses) => statuses[0].url);
```

### Steps to reproduce

- Use code similar to the above to deploy to Google Cloud Run an image that, for example, doesn't listen on the right `PORT`

### Expected Behavior

- I want it to regard the `service` as invalid and to give me _that_ error message, not the one inside the `.apply` function.

### Actual Behavior

The error displayed is for the simplistic error inside the `.apply` method.

### Versions used

3.32.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by gunar** [comment]
I see, instead of getting the semi-cryptic `Cannot read properties of undefined` I could throw my own error (e.g. the container did start). Thanks for now @mikhailshilkov.

**Comment by stack72** [comment]
Hey @gunar 

So I am not quite following here... let me recap:

1. You pass a configuration to GCP for a cloudrun.Service. 
    * This valid configuration as per the GCP provider and actually creates a service?
2. You want Pulumi to be able to fail if the port mappings that you provide are not correct and return an error?

Is this a correct summary?

Paul

**Comment by viveklak** [comment]
I can't really see an improved experience we can offer here in the provider besides the suggestion in https://github.com/pulumi/pulumi-gcp/issues/859#issuecomment-1192562622. I will close this but please reopen if you disagree.

**Comment by gunar** [comment]
@stack72

1) Correct
2) Not really, the port mapping configurations are correct but (due to something app specific) the app won't listen on the port and fails to become healthy and serve traffic

The problem with throwing my own errors inside the `.apply` method is that, although it does provide me with a way to give the user a better error message, it prevents the whole of the Pulumi script to run successfully. That means stack outputs are never accessible — even outputs that don't have anything to do with the error in question and are upstream from it become inaccessible with `pulumi stack output`— because when `.apply` fails, it's a run-time error as opposed to a "compile-time" error (I'm using the term vaguely here).

This is a huge pain on `pulumi-gcp`—haven't had it with `pulumi-aws` so far. I understand it's because GCloud's API is not as solid as AWS's but I was wondering if there was anything we could do on the Pulumi side of things to improve the DX.
