### ISSUE TITLE
improve gcp config error message?

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi-gcp#860]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

was trying to deploy a GKE cluster and I thought the error message could be better around providing a command to configure
- project
- zone

[![asciicast](https://asciinema.org/a/bM0L9E1c8DSO7qKezySQuWxvt.svg)](https://asciinema.org/a/bM0L9E1c8DSO7qKezySQuWxvt)

cc @guineveresaenger

**Comment by dixler** [comment]
related to 
- https://github.com/pulumi/registry/pull/1252

**Comment by stack72** [comment]
This work will require implementing the preConfigureCallback func and checking in there

**Comment by guineveresaenger** [comment]
I'm running some diagnostics on how the TF provider authenticates here to see how we should use that authentication.
