### ISSUE TITLE
`storage.Bucket` incorrectly triggers replacement when using configured dual-region location on each update

### ISSUE THREAD

**Issue by robertvanhoesel** [pulumi/pulumi-gcp#868]
### What happened?

Since July 28 2022, Google Cloud Storage made[ _configured dual-region_](https://cloud.google.com/storage/docs/locations#predefined_dual-regions) locations generally available. 

Configured dual regions are now the preferred way of defining the location. Where previously just 3 presets were available (`NAM4`, `ASIA1`, `EUR4`) user can now configure 2 regions and specify them in the location field using the format of `{region}+{region}` (e.g. `EUROPE-WEST4+EUROPE-WEST1`).

The current GCP Provider incorrectly reads the containing [multi region](https://cloud.google.com/storage/docs/locations#location-mr) (`EU`, `US`, etc) instead of the configured dual region, causing a replacement to be scheduled.

### Steps to reproduce

Configure a bucket like below, run two subsequent `pulumi up`s and notice that on every update the bucket gets replaced because it detects a change in `location`.
```ts
new gcp.storage.Bucket( "dual-region-bucket",
    {
        location: "EUROPE-WEST4+EUROPE-WEST1"
    },
);
```

In the GCP Console you will see the bucket being created using the two regions.

![CleanShot 2022-08-04 at 16 27 30@2x](https://user-images.githubusercontent.com/6642554/182873024-fcf5f0c2-c08b-4a75-9dcd-fb6d0e7b9fbd.png)

### Expected Behavior

No changes to the bucket are detected and no replacement is scheduled.

### Actual Behavior

The provider incorrectly reads `EU` as the location instead of the configuration syntax and schedules a replacement.
```
   ++gcp:storage/bucket:Bucket: (create-replacement)
      ~ location: "EU" => "EUROPE-WEST4+EUROPE-WEST1"
```

When using a dual-region preset like `EUR4` the everything works as expected.

### Versions used

```
CLI          
Version.  3.37.0
Go Version   go1.17.12
Go Compiler   gc

Plugins
NAME   VERSION
gcp  6.32.0

Host     
OS.  darwin
Version   12.2.1
Arch   arm64

```

### Additional context

Release notes: https://cloud.google.com/storage/docs/release-notes#July_28_2022

Creating a dual region bucket through the GCP Console no longer supports using the presets and forces picking 2 regions.

<img width="578" alt="image" src="https://user-images.githubusercontent.com/6642554/182872940-38dc0d3d-eb22-4e55-80ab-eed5b83a7320.png">

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @robertvanhoesel 

We will require this to be upgraded in the TF provider before it makes it's way here - I will look into this

Paul

**Comment by mikhailshilkov** [comment]
I believe the dual-region support was added later in https://github.com/GoogleCloudPlatform/magic-modules/pull/6619

This functionality was implemented with the [`customPlacementConfig`](https://www.pulumi.com/registry/packages/gcp/api-docs/storage/bucket/#customplacementconfig_nodejs) property.

I'll go ahead and close the issue as done, please open a new one if anybody struggles with `customPlacementConfig` usage.
