### ISSUE TITLE
gcp.orgpolicy.Policy: HTTP 403 from GCP (end user credentials not supported by orgpolicy API?)

### ISSUE THREAD

**Issue by cakoose** [pulumi/pulumi-gcp#883]
### What happened?

I tried using `gcp.orgpolicy.Policy,` but I get an HTTP 403 error when doing `pulumi up`.

### Steps to reproduce

```ts
const projectId = gcp.organizations.getClientConfig().then(c => c.project);

// Cloud SQL instances must not have public IPs.
new gcp.orgpolicy.Policy('sql.restrictPublicIp', {
    parent: pulumi.interpolate`projects/${projectId}`,
    name: pulumi.interpolate`projects/${projectId}/policies/sql.restrictPublicIp`,
    spec: {
        reset: true,
    },
});
```

When I try `pulumi up`, I get an error:

```
$ pulumi up --stack=XXX
Previewing update (XXX)

View Live: https://app.pulumi.com/XXX/previews/XXX

     Type                     Name                  Plan
     pulumi:pulumi:Stack      XXX
 +   └─ gcp:orgpolicy:Policy  sql.restrictPublicIp  create

Resources:
    + 1 to create
    158 unchanged

Do you want to perform this update? yes
Updating (XXX)

View Live: https://app.pulumi.com/XXX/updates/459

     Type                     Name                  Status                  Info
     pulumi:pulumi:Stack      XXX         **failed**              1 error
 +   └─ gcp:orgpolicy:Policy  sql.restrictPublicIp  **creating failed**     1 error

Diagnostics:
  pulumi:pulumi:Stack (XXX):
    error: update failed

  gcp:orgpolicy:Policy (sql.restrictPublicIp):
    error: 1 error occurred:
    	* Error creating Policy: failed to create a diff: failed to retrieve Policy resource: googleapi: Error 403: Your application has authenticated using end user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the orgpolicy.googleapis.com. We recommend configuring the billing/quota_project setting in gcloud or using a service account through the auth/impersonate_service_account setting. For more information about service accounts and how to use them in your application, see https://cloud.google.com/docs/authentication/. If you are getting this error with curl or similar tools, you may need to specify 'X-Goog-User-Project' HTTP header for quota and billing purposes. For more information regarding 'X-Goog-User-Project' header, please check https://cloud.google.com/apis/docs/system-parameters.
    Details:
    [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "domain": "googleapis.com",
        "metadata": {
          "consumer": "projects/XXX",
          "service": "orgpolicy.googleapis.com"
        },
        "reason": "SERVICE_DISABLED"
      }
    ]
```

The "orgpolicy.googleapis.com" service is definitely enabled. It shows up when I run:

```
gcloud --project=XXX services list
```

### Expected Behavior

See above.

### Actual Behavior

See above.

### Output of `pulumi about`

```
$ pulumi about
CLI
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Host
OS       darwin
Version  12.4
Arch     x86_64

Backend
Name           pulumi.com
URL            https://app.pulumi.com/XXX
User           XXX
Organizations  XXX, XXX

Pulumi locates its logs in /var/folders/z9/2stfl58s23l38j8gbwwns0m80000gn/T/ by default
warning: Failed to get information about the plugin: failed to load language plugin : no language plugin 'pulumi-language-' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install language `
warning: Failed to load language plugin : no language plugin 'pulumi-language-' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install language `
warning: Failed to get information about the current stack: no Pulumi.yaml project file found (searching upwards from ). If you have not created a project yet, use `pulumi new` to do so
```

Node package versions:
- `@pulumi/pulumi`: 3.38.0
- `@pulumi/gcp`: 6.34.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @cakoose 

Sorry this is causing you an issue - this is what I am seeing right now:

> Error 403: Your application has authenticated using end user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the orgpolicy.googleapis.com. We recommend configuring the billing/quota_project setting in gcloud or using a service account through the auth/impersonate_service_account setting. For more information about service accounts and how to use them in your application, see https://cloud.google.com/docs/authentication/. If you are getting this error with curl or similar tools, you may need to specify 'X-Goog-User-Project' HTTP header for quota and billing purposes. For more information regarding 'X-Goog-User-Project' header, please check https://cloud.google.com/apis/docs/system-parameters

Can you tell me if you are setting env vars for your provider config for authentication?

Paul

**Comment by cakoose** [comment]
I'm not setting any environment variables explicitly.

My Pulumi.yaml and Pulumi.<stack-name>.yaml look like this:

```yaml
name: ...
runtime: nodejs
description: ...
```

```yaml
config:
  gcp:project: ...
  gcp:region: ...
  google-native:project: ...
  google-native:region: ...
```

Is there anything else?

**Comment by cakoose** [comment]
@stack72: Is there any other information I can provide?

**Comment by iam-yan** [comment]
Encounter the same issue when following the tutorial. It seems that we should use service account instead of `gcloud auth application-default login`, doesn't it?

@cakoose Have you fixed it?

**Comment by iam-yan** [comment]
For anyone being struggled with this issue and end up here...

I've fixed it by setting an env variable for service account to authorize my pulumi code:
`export GOOGLE_APPLICATION_CREDENTIALS=/path/to/your/key-file.json`

fyi @cakoose

**Comment by mikhailshilkov** [comment]
This issue has been sitting in "awaiting feedback" for a while. Since we haven't heard back, I'll go ahead and close it. Please open a new issue if anybody still experiences issues with the provider.

**Comment by cakoose** [comment]
@mikhailshilkov: I believe I answered @stack72's request for more information. Is there anything else you need?

**Comment by mikhailshilkov** [comment]
@cakoose Has @iam-yan's suggestion worked for you? The issue definitely feels like the auth setup isn't quite working for you.

**Comment by mikhailshilkov** [comment]
Pulumi supports the full range of authentication options [documented for Google Cloud](https://cloud.google.com/docs/authentication). `GOOGLE_APPLICATION_CREDENTIALS` in particular is described in https://cloud.google.com/docs/authentication/application-default-credentials

**Comment by cakoose** [comment]
From the GCP docs:

> ADC searches for credentials in the following locations:
> 1. [GOOGLE_APPLICATION_CREDENTIALS environment variable](https://cloud.google.com/docs/authentication/application-default-credentials#GAC)
> 2. [User credentials set up with the Google Cloud CLI](https://cloud.google.com/docs/authentication/application-default-credentials#personal)
> 3. [The attached service account, as provided by the metadata server](https://cloud.google.com/docs/authentication/application-default-credentials#attached-sa)

Is this a correct assessment of the situation:
1. By default, Pulumi is using my `gcloud` user credentials ("$HOME/.config/gcloud/application_default_credentials.json").
2. For this particular operation, those credentials don't work.
3. I need to create some kind of service account with some set of permissions.
4. I need create a JSON key for that service account and download it locally.
5. I need  to set `GOOGLE_APPLICATION_CREDENTIALS=/path/to/key.json`, which causes Pulumi to use that _instead_ of my `gcloud` user credentials.

What about API calls to manipulate other resources. Those were working fine with my user credentials, but I worry that they will stop working when using the service account credentials. How does Pulumi know which credentials to use for which resource?

**Comment by mikhailshilkov** [comment]
Yes, I think this is correct.

Pulumi will use the same credentials for all resources by default. If you want to use different credentials for a single resource, there is probably a way to do so via an [explicit provider](https://www.pulumi.com/docs/intro/concepts/resources/providers/#explicit-provider-configuration) and passing the service account key to its [`credentials` property](https://www.pulumi.com/registry/packages/gcp/installation-configuration/#configuration-reference).
