### ISSUE TITLE
unable to find required configuration setting: GCP Project

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-gcp#890]
The [new auth config validation](https://github.com/pulumi/pulumi-gcp/pull/882) is causing deployments to break that do not set the default `gcp:project` key.

Initial thoughts:

This chunk of code is too zealous and we can begin by removing it and roll the error into the gcloud config validation below:
https://github.com/pulumi/pulumi-gcp/blob/master/provider/resources.go#L187
That will fix things for users who have non-default settings.

We can then look into how the underlying provider works - exactly how the GCP project is required and under which circumstances

If necessary/unaccounted for in the auth helper library, we should add validation tests that take into account all authentication scenarios.

**Comment by guineveresaenger** [comment]
Upstream docs (https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#project)
say you can set `Project` on a per-resource basis and that will take precedence over global settings. Additionally the setting is Optional upstream.

What this means is:

1. you can configure `Project` on a provider level (globally) - this means `pulumi config set` _or_ env vars
2. you can configure `Project` on a per-resource level (which overrides the above)
=> running `gcloud config set project <project>` is not enough for this provider to default to a project; you must set it via either of the two means above.

It appears as though it will be tricky to tease apart where and how the Project was set. Observations:

**Project configured with gcloud but not set via 1 or 2 above, using [the changes made in this commit](https://github.com/pulumi/pulumi-gcp/pull/891/commits/efbee4936b31c54d0542234a0bf1dea1b98bfea3)**

result: success on preview, failure on update. Error is legible and clear, but this is not a fast failure as it happens on `up` not `preview`.

```
gcloud config set project pulumi-development
Updated property [core/project].
@guin:gcp-go-gke (master *)🦉 PATH=/Users/guin/go/src/github.com/pulumi/pulumi-gcp/bin:$PATH pulumi up
Previewing update (dev)

View Live: https://app.pulumi.com/guinevere/gcp-go-gke/dev/previews/07fc7b4d-88c2-4426-8f35-decd698f7a2c

     Type                   Name            Plan       
     pulumi:pulumi:Stack    gcp-go-gke-dev             
 +   └─ gcp:storage:Bucket  static-site     create     
 
Resources:
    + 1 to create
    1 unchanged

Do you want to perform this update?  [Use arrows to move, enter to select, type to filteDo you want to perform this update?  [Use arrows to move, enter to select, type to filteDo you want to perform this update? yes
Updating (dev)

View Live: https://app.pulumi.com/guinevere/gcp-go-gke/dev/updates/17

     Type                   Name            Status                  Info
     pulumi:pulumi:Stack    gcp-go-gke-dev  **failed**              1 error
 +   └─ gcp:storage:Bucket  static-site     **creating failed**     1 error
 
Diagnostics:
  gcp:storage:Bucket (static-site):
    error: 1 error occurred:
    	* project: required field is not set
 
  pulumi:pulumi:Stack (gcp-go-gke-dev):
    error: update failed
 
Resources:
    1 unchanged

Duration: 2s
```

**Project configured with gcloud and set via 1, using [the changes made in this commit](https://github.com/pulumi/pulumi-gcp/pull/891/commits/efbee4936b31c54d0542234a0bf1dea1b98bfea3)**

Results in success with a resource being created

```
pulumi config set gcp:project pulumi-development
@guin:gcp-go-gke (master *)🦉 PATH=/Users/guin/go/src/github.com/pulumi/pulumi-gcp/bin:$PATH pulumi up
Previewing update (dev)

View Live: https://app.pulumi.com/guinevere/gcp-go-gke/dev/previews/d139789f-c301-4323-8c4f-eb62038a5aaa

     Type                   Name            Plan       
     pulumi:pulumi:Stack    gcp-go-gke-dev             
 +   └─ gcp:storage:Bucket  static-site     create     
 
Resources:
    + 1 to create
    1 unchanged

Do you want to perform this update? yes
Updating (dev)

View Live: https://app.pulumi.com/guinevere/gcp-go-gke/dev/updates/19

     Type                   Name            Status      
     pulumi:pulumi:Stack    gcp-go-gke-dev              
 +   └─ gcp:storage:Bucket  static-site     created     
 
Resources:
    + 1 created
    1 unchanged

Duration: 4s
```

**Project configured with gcloud and set via 2, using [the changes made in this commit](https://github.com/pulumi/pulumi-gcp/pull/891/commits/efbee4936b31c54d0542234a0bf1dea1b98bfea3)**

```
@guin:gcp-go-gke (master *)🦉 PATH=/Users/guin/go/src/github.com/pulumi/pulumi-gcp/bin:$PATH pulumi up
Previewing update (dev)

View Live: https://app.pulumi.com/guinevere/gcp-go-gke/dev/previews/944c571e-0fa8-40f7-949d-6b769c31f4b0

     Type                   Name            Plan       
     pulumi:pulumi:Stack    gcp-go-gke-dev             
 +   └─ gcp:storage:Bucket  static-site     create     
 
Resources:
    + 1 to create
    1 unchanged

Do you want to perform this update? yes
Updating (dev)

View Live: https://app.pulumi.com/guinevere/gcp-go-gke/dev/updates/22

     Type                   Name            Status      
     pulumi:pulumi:Stack    gcp-go-gke-dev              
 +   └─ gcp:storage:Bucket  static-site     created     
 
Resources:
    + 1 created
    1 unchanged

Duration: 4s
```

**Observations**

It appears as though the auth verification check does not attempt to validate whether Project has been set. We may be stuck with not being able to fail fast on these settings.

**Comment by snamber** [comment]
Background: I posted about this issue in the Slack channel

In the end this is just a breaking change that requires (when using the automation API) a few lines of code and in the case of a custom configuration in interactive mode potentially also one line of code, but this line is even suggested in the error message.

v6.36.0 of the pulumi-gcp plugin works after adding this snippet, individual resources can still be created in different projects.

```go
s, err := auto.UpsertStackInlineSource(ctx, stackName, p.Project, deployFunc)
if err != nil {
    ...
}
if err := s.SetAllConfig(ctx, map[string]auto.ConfigValue{
    "gcp:project": {Value: p.Project},
    }); err != nil {
    ...
}
```

I can see in [the documentation](https://www.pulumi.com/registry/packages/gcp/installation-configuration/) that `gcp:project` is a required field. Maybe this requirement was just never enforced, but it seems to be according to the specification, so while this may break people's existing configs, these configs seem not to have been to spec in that case.

Maybe as an alternative to rolling back completely an additional line warning of this potential breaking change in the release notes / changelog would also do to point people in the right direction.

**Comment by stack72** [comment]
@snamber I think that's a great happy medium here :) You are correct that we did mark it as required but doesn't look like we ever enforced that - that will need to be a change we make in the next major version of the provider

I think a pulumi warning that project is not set is a good way to go here

**Comment by guineveresaenger** [comment]
Alright, so here's what I looked into.

My goal is to pass a warning to the Pulumi logger, which I believe for these kinds of providers would use the [host client Log function](https://github.com/pulumi/pulumi/blob/master/pkg/resource/provider/host.go#L94). We call `PreConfigureCallback` as [part of the provider Configure function](https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfbridge/provider.go#L542). (Side note: I _think_ we can use HostClient logging on the provider here because the provider itself is a resource and thus has a URN?)

So... what we could do here is change the signature of `PreConfigureCallback` to include a hostClient and probably a Context as well.
Then if the provider logger works as expected, a nice warning could flash by that says something to the effect of "hey we see you didn't set a Project; we assume this is because you know what you're doing and set it on a per-resource basis but just in case that wasn't it, now you have a hint on which settings to tweak in your config"

The downside here is we're changing the function signature of preConfigureCallback, so implementation would look like this:

1. update TF bridge & cut a release
2. find all uses of `preConfigureCallback` in providers using this library and match the signature ([there are more than I expected](https://github.com/search?p=3&q=org%3Apulumi+preConfigureCallback&type=Code))
3. profit 😛 

Alternately, we could print a warning to stdout using `fmt`. Less pretty, wouldn't get written to the overall logs, would be extremely easy to do.

Is there a logger that we have access to in `preConfigureCallback` that I'm not aware of?
