### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by andyndang** [pulumi/pulumi-gcp#892]
File: [themes/default/content/registry/packages/gcp/api-docs/pubsub/subscription/_index.md](https://www.pulumi.com/registry/packages/gcp/api-docs/pubsub/subscription/)

Using this example it's generating the wrong "Delivery Type"

<img width="704" alt="image" src="https://user-images.githubusercontent.com/26821974/188242806-39891396-f50d-40b2-82e0-bb052dd30de8.png">

**Comment by mikhailshilkov** [comment]
I'm not sure which example out of five is referenced here... Also, unclear what the expected outcome of the example is.

I'll close it as no-repro, feel free to provide a code snippet to reproduce the problem if you feel like it still exists.
