### ISSUE TITLE
BigQuery + Pubsub push example is incorrect

### ISSUE THREAD

**Issue by andyndang** [pulumi/pulumi-gcp#894]
File: [themes/default/content/registry/packages/gcp/api-docs/pubsub/subscription/_index.md](https://www.pulumi.com/registry/packages/gcp/api-docs/pubsub/subscription/)

Example from https://www.pulumi.com/registry/packages/gcp/api-docs/pubsub/subscription/#pubsub-subscription-push-bq
The resulted subscription has the wrong type (need to be "BigQuery")

<img width="535" alt="Screen Shot 2022-09-06 at 1 12 24 PM" src="https://user-images.githubusercontent.com/26821974/188729350-f737e61b-0e09-4dc9-bd4a-888023fed0f1.png">

**Comment by viveklak** [comment]
I tried this out and the subscription created seems as expected:
<img width="722" alt="Screen Shot 2022-09-07 at 4 13 40 PM" src="https://user-images.githubusercontent.com/1094518/189005519-e5179c68-a2cf-4ae9-a0ae-010b683ffdfc.png">

Are you sure you copied the right example? https://www.pulumi.com/registry/packages/gcp/api-docs/pubsub/subscription/#pubsub-subscription-push-bq
