### ISSUE TITLE
GCP - AlloyDB Support

### ISSUE THREAD

**Issue by eh-93** [pulumi/pulumi-gcp#896]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Is it possible to provision an AlloyDB instance using Pulumi?
https://cloud.google.com/alloydb

If not is it possible to connect cloud run to an existing instance? 

### Affected area/feature
GCP, AlloyDB

**Comment by jkisk** [comment]
Hello, provisioning AlloyDB doesn't seem to be supported yet in this provider, that will happen when it is added to the upstream terraform provider.  There seems to be some data migration support but not provisioning support in our [pulumi-google-native](pulumi.com/registry/packages/google-native) provider, which can be used alongside pulumi-gcp.  Provisioning of an AlloyDB instance will be added to the [pulumi-google-native](pulumi.com/registry/packages/google-native) provider when it is available in the google discovery api that we use to autogenerate that provider daily.

**Comment by mikhailshilkov** [comment]
AlloyDB support has been added in https://www.pulumi.com/registry/packages/gcp/api-docs/alloydb/
