### ISSUE TITLE
Update docs - service_account field should be mandatory instead of optional

### ISSUE THREAD

**Issue by ferancona** [pulumi/pulumi-gcp#906]
File: [themes/default/content/registry/packages/gcp/api-docs/eventarc/trigger/_index.md](https://www.pulumi.com/registry/packages/gcp/api-docs/eventarc/trigger/)

The _service_account_ input seems to be a mandatory field for **gcp.eventrac.Trigger()**.

**Comment by viveklak** [comment]
@ferancona thanks for opening the issue! I believe its not entirely necessary to have the service account specified (though I expect this is by far the most common and recommended way to manage access to event arc triggers). For instance, you could grant `roles/run.invoker` role to all users and set the destination to a cloud run service. In which case the cloud run service account should have privileges to execute the trigger.

FWIW the service account is also marked optional by the Google terraform provider: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/eventarc_trigger#service_account
