### ISSUE TITLE
Cloud run job

### ISSUE THREAD

**Issue by LoicMahieu** [pulumi/pulumi-gcp#914]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Google has introduced "Run jobs": https://cloud.google.com/run/docs/create-jobs
Is there any supports of this in Pulumi ?

Thanks

**Comment by viveklak** [comment]
This is blocked on https://github.com/hashicorp/terraform-provider-google/issues/11743

**Comment by lblackstone** [comment]
I'm not sure if https://www.pulumi.com/registry/packages/google-native/api-docs/run/v2/job/ is the same API, but if so, you should be able to use this with our native provider.

**Comment by viveklak** [comment]
> I'm not sure if https://www.pulumi.com/registry/packages/google-native/api-docs/run/v2/job/ is the same API, but if so, you should be able to use this with our native provider.

Sadly its very unclear how v2 is to be used. See https://github.com/pulumi/pulumi-google-native/issues/639. v1 api might be a better alternative which the native provider supports. Not sure if the specific feature is supported in that API.

**Comment by SimonMacIntyre** [comment]
> I'm not sure if https://www.pulumi.com/registry/packages/google-native/api-docs/run/v2/job/ is the same API, but if so, you should be able to use this with our native provider.

Unfortunately this one is bugged due to Googles docs missing endpoints, or something to that effect. 
https://github.com/pulumi/pulumi-google-native/issues/639

So it doesn't have a solution on google native nor on classic.

**Comment by mikhailshilkov** [comment]
I believe this has been added since the issue was open: https://www.pulumi.com/registry/packages/gcp/api-docs/cloudrunv2/job/
