### ISSUE TITLE
Somehow the generation of a gcp vpcaccess connector's ID output is invalid regex

### ISSUE THREAD

**Issue by SimonMacIntyre** [pulumi/pulumi-gcp#923]
### What happened?

> Error creating Connector: googleapi: Error 400: Connector ID must follow the pattern ^[a-z][-a-z0-9]{0,23}[a-z0-9]$.

The name passed to this was something like `staging-company-project` and will fail when the regex validation of the connector ID output fails. 

I don't know what it is exactly, I think it might be the length going over 24 characters. 

https://user-images.githubusercontent.com/1260938/194893535-4a4df433-1391-4e5a-880d-b521e1057ed6.mov

Renaming the Connector to simply "connector" fixes this bug.

### Steps to reproduce

Try to make a [gcp.vpcaccess.connector](https://www.pulumi.com/registry/packages/gcp/api-docs/vpcaccess/connector/) with a name with at least 2 hyphens and like 20 characters. 

### Expected Behavior

For my name to be valid and not cause side effects in an output field

### Actual Behavior

Fails due to invalid ID output for Connector

### Output of `pulumi about`

```
CLI          
Version      3.42.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME        VERSION
cloudflare  4.12.1
gcp         6.38.0
nodejs      unknown
random      4.8.2

Host     
OS       darwin
Version  12.5.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v18.7.0'


### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @SimonMacIntyre, thank you for getting in touch about this!

In this case, your name `staging-company-project` is under Google's character limit, but after Pulumi appends its auto-generated suffix, it's over the limit.

It is possible to disable Pulumi's naming suffix and use exactly the name you provide, although that comes with some trade-offs. See the [naming docs](https://www.pulumi.com/docs/intro/concepts/resources/names/#autonaming) for an explanation.

I hope that helps.

**Comment by SimonMacIntyre** [comment]
Ah I see, thanks for the explanation, makes sense.
