### ISSUE TITLE
Missing livenessProbe for Cloud Run in Go package

### ISSUE THREAD

**Issue by Mistic92** [pulumi/pulumi-gcp#932]
## Issue details
 There is no livenessProbe available to set. Looks like parameters are the same to startup probe, just different name. 
 https://cloud.google.com/run/docs/configuring/healthchecks#liveness-probes

### Affected area/feature

Go package `github.com/pulumi/pulumi-gcp/sdk/v6 v6.41.0`

**Comment by guineveresaenger** [comment]
Hi @Mistic92 - we will support this as soon as [this change is pulled into an upstream release](https://github.com/hashicorp/terraform-provider-google-beta/pull/4788) - soon hopefully! 🤞

**Comment by mikhailshilkov** [comment]
The upstream PR was merged and `livenessProbe` is now available: https://www.pulumi.com/registry/packages/gcp/api-docs/cloudrun/service/#livenessprobe_nodejs
