### ISSUE TITLE
gcp.cloudfunctions.HttpCallbackFunction should support minInstances and maxInstances

### ISSUE THREAD

**Issue by 0xJem** [pulumi/pulumi-gcp#933]
Both properties are not available in the `HttpCallbackFunctionArgs` type for the HttpCallbackFunction convenience constructor.

Once deployed, I can set the min and max instances through GCP console, so these properties are valid.

**Comment by roothorp** [comment]
Hi @0xJem, thanks for the issue! I'm adding this to our work stack for prioritization in future iterations.

These properties are available in the core cloudfunctions.Function type, but HttpCallbackFunction is implemented as a mixin and as such the min and max Instances need to be added by hand.

**Comment by 0xJem** [comment]
Hi! Is there a way to set these properties after using the HttpCallbackFunction constructor? I couldn't see a way to do that. It would be a good workaround in the meantime.
