### ISSUE TITLE
https://www.pulumi.com/registry/packages/gcp/api-docs/sql/database page actually points the yet another DBInstance docs page

### ISSUE THREAD

**Issue by palladius** [pulumi/pulumi-gcp#961]
File: [themes/default/content/registry/packages/gcp/api-docs/sql/database/_index.md](https://www.pulumi.com/registry/packages/gcp/api-docs/sql/database/)

Note that these two pages:

* https://www.pulumi.com/registry/packages/gcp/api-docs/sql/database/
* https://www.pulumi.com/registry/packages/gcp/api-docs/sql/databaseinstance/
Both document the databaseinstance object.

If then i. want to create a DB I need to scrape the API/code page. It's doable, but a lot more work.
I'm convinced this is a mistake in the docs.

**Comment by danielrbradley** [comment]
Hi, thanks for flagging this @palladius 

I've had a quick look through the two pages and they appear to document different underlying resources. This can be seen most clearly by looking at the input properties section:

DatabaseInstance:
![image](https://user-images.githubusercontent.com/331676/208521389-3292fb5f-58a3-4c17-badf-06e3b95bbc4b.png)

Database:
![image](https://user-images.githubusercontent.com/331676/208521566-425c913e-daa2-4918-aef8-79eb98734477.png)

The database instance must be created first, then the database can be created within that.

Some of the examples are shared between pages as they encompass creating both parts as to be a more complete example. 

I'll close this as by-design, but please let me know if I've misinterpreted what you were flagging up.
