### ISSUE TITLE
Missing generated_id Output for gcp.compute.BackendService (classic) [python]

### ISSUE THREAD

**Issue by sunilrr** [pulumi/pulumi-gcp#988]
### What happened?

1. Create new GCP compute backend service
2. Refer Output property 'generated_id' in pulumi (python)

Purpose: Construct JWT audience code of IAP

[Documentation](https://www.pulumi.com/registry/packages/gcp/api-docs/compute/backendservice/#generated_id_python)

### Expected Behavior

generated_id refer to the unique number generated by GCP

### Steps to reproduce

Sample in documentation can be used as-is.

```python
import pulumi
import pulumi_gcp as gcp

api_backend = gcp.compute.BackendService("default",
    cdn_policy=gcp.compute.BackendServiceCdnPolicyArgs(
        cache_key_policy=gcp.compute.BackendServiceCdnPolicyCacheKeyPolicyArgs(
            include_host=True,
            include_http_headers=["X-My-Header-Field"],
            include_protocol=True,
            include_query_string=True,
        ),
        cache_mode="USE_ORIGIN_HEADERS",
    ),
    enable_cdn=True)

backend_id = api_backend.generated_id
```

### Output of `pulumi about`

CLI          
Version      3.53.1
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME           VERSION
command        0.5.2
cp-deploy      0.1.0
gcp            6.40.0
google-native  0.26.0
python         unknown
random         4.8.2

Host     
OS       darwin
Version  13.2
Arch     arm64

This project is written in python: executable='/opt/homebrew/bin/python3' version='3.10.9
'

Backend        
Name           XYZ
URL            gs://pulumi-states-dev
User           sunilr
Organizations  

Pulumi locates its logs in /var/folders/7p/sw8t54p91pvcz1d5gm3c_26c0000gp/T/ by default
warning: Failed to get information about the Pulumi program's dependencies: exit status 2
warning: Failed to get information about the current stack: No current stack
warning: A new version of Pulumi is available. To upgrade from version '3.53.1' to '3.54.0', run

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Hello @sunilrr thanks for reporting this issue.

It might be helpful if you could share the output and error you're seeing in the CLI when running `pulumi up`. I'm assuming from your description that the `generated_id` is either being returned as nil, empty (or zero maybe) or throwing an error.

When quickly reproducing this in typescript:

```typescript
const _default = new gcp.compute.BackendService("default", {
  cdnPolicy: {
    cacheKeyPolicy: {
      includeHost: true,
      includeHttpHeaders: ["X-My-Header-Field"],
      includeProtocol: true,
      includeQueryString: true,
    },
    cacheMode: "USE_ORIGIN_HEADERS",
  },
  enableCdn: true,
});

export const generatedId = _default.generatedId;
```

The deployment succeeds and I see the output:

```
generatedId: 9.033009296946491e+18
```

When inspecting the internal gRPC calls I can see:
```json
  {
    "method": "/pulumirpc.ResourceMonitor/RegisterResourceOutputs",
    "request": {
      "urn": "urn:pulumi:dev::scratch::pulumi:pulumi:Stack::scratch-dev",
      "outputs": { "generatedId": 9033009296946491000 }
    },
    "response": {},
    "metadata": { "mode": "server" }
  }
```

I suspect the issue may be related to the size of the number being greater than 32 bits. I'm inquiring internally to find out how 64-bit numbers should be supported.

**Comment by danielrbradley** [comment]
Out of interest, what do you need this `generatedId` for in your program? Is there knock-on impact of not having this number - i.e. other resources that depend on this identifier rather than the name?

It looks as if this is a purely internal indentifier which isn't shown in the UI and isn't even returned as part of their console API responses.

**Comment by sunilrr** [comment]
Backend is fronted with Identity Aware Proxy.

JWT Audience Code takes below format,

`/projects/$PROJECT_NUMBER/global/backendServices/$BACKEND_SERVICE_ID`

Idea is to inject this as environment variable to Cloud Run instance.
Missing details in audience is the 'service id' which is most likely the generated id.

Pulumi python code,
`
self.iap_names = pulumi.Output.all(args.core.project.number, self.api_backend_service.generated_id, self.load_balancer.backend_service.generated_id).apply(
            lambda l: f"projects/{l[0]}/iap_web/compute/services/{l[1]},projects/{l[0]}/iap_web/compute/services/{l[2]}"
        )
`

Error message,
`E       AttributeError: 'BackendService' object has no attribute 'generated_id'`

**Comment by sunilrr** [comment]
To clarify above above fails in unit tests, so never tested with 'pulumi up'.

Is it possible the issue occurs only in unit tests?

**Comment by sunilrr** [comment]
Upgrading pulumi-gcp from 6.32.0 to 6.49.0 fixed it!!

I guess generated_id was includes after 6.32.0.
