### ISSUE TITLE
Can't autoscale default-pool in GKE

### ISSUE THREAD

**Issue by Pithikos** [pulumi/pulumi-gcp#999]
### What happened?

I have gone through all API references and It seems impossible to make a simple GKE cluster with default-pool autoscaling turned on.

A [past workaround](https://github.com/pulumi/pulumi/issues/2054) of using `remove_default_node_pool=True` seems outdated now, since GKE requires the default-pool with at least 1 node when creating a standard cluster. A bit dissapointing since simply wrapping `gcloud` with Python actually works, which was what I was doing before trying out Pulumi.

I list a few workarounds below that I've tried but to no avail.

**Workaround 1 not working**

```python
defaul_pool =  container.NodePool(
        "default-pool",
        # REQUIRES CLUSTER NAME
        location="europe-central2-a",
        autoscaling={..}
        ..
)

cluster = container.Cluster(
        "mycluster",
        location="europe-central2-a",
        node_pools=[default_pool],
        ..
)
```

**Workaround 2 not working**

```python
container.Cluster(
        "mycluster",
        location="europe-central2-a",
        remove_default_node_pool=True,   # Error 400: Cluster.initial_node_count must be greater than zero.,
)
```

**Workaround 3 not working**

```python
container.Cluster(
        "mycluster",
        location="europe-central2-a",
        remove_default_node_pool=True,
        node_autoscaling={..}  # INVALID KEYWORD
)
```

**Workaround 4 not working**

```python
container.Cluster(
        "mycluster",
        location="europe-central2-a",
        remove_default_node_pool=True,
        node_config={
            "autoscaling": {..}  # INVALID KEYWORD
        }
)
```

### Expected Behavior

Allow me to somehow enable autoscaling for default-pool in GKE.

### Steps to reproduce

```python
container.Cluster(
        "mycluster",
        location="europe-central2-a",
        remove_default_node_pool=True,
)
```

Gives

```
  gcp:container:Cluster (cluster-staging):
    error: 1 error occurred:
    	* googleapi: Error 400: Cluster.initial_node_count must be greater than zero., badRequest
```

### Output of `pulumi about`

CLI          
Version      3.55.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME        VERSION
command     0.7.1
gcp         6.50.0
kubernetes  3.24.1
python      unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @Pithikos, sorry for the frustration.

I'm not very familiar with GKE, but would it not work to create the Cluster with `node_autoscaling={..}` and without `remove_default_node_pool` and `node_pools`?

Other than that, your second workaround seems reasonable.

Not that - although I'm sure you've seen this already - [we recommend using separate node pools](https://www.pulumi.com/registry/packages/gcp/api-docs/container/cluster/#example-usage).

**Comment by Pithikos** [comment]
@thomas11 the thing is I have a very specific scenario. I need a secure gvisor pool and then a minimal default one. I've tried with autoscaling but I'm not a fan of GKE starting creating randomly pools and nodes.

In the end I went with the suggested solution, mainly because I need to have 100% control of the pools, so the slower startup although annoying, I can live with. But still I don't understand why it's not possible to both start the cluster with a default pool and just make alterations to that existing pool later on. That is possible via the UI and gcloud.

Anyway happy that I got something working now. Just that it took quite many days of trial and error.

**Comment by jkodroff** [comment]
AFAICT, there's 2 errors in the example:

1. It looks like AutoPilot clusters must be regional.
2. Due to a bug in the upstream TF provider, `ipAllocationPolicy` must be set to an empty object (in TS at least).

I believe the correct minimal example for an autopilot cluster is:

```typescript
const cluster = new gcloud.container.Cluster("primary", {
  enableAutopilot: true,
  location: "us-central1",
  ipAllocationPolicy: {},
});
```

(The service account resource does not appear to be necessary, or really have any effect.)

**Comment by mikhailshilkov** [comment]
Thank you @jkodroff for a working example.

Since we haven't heard back, I'll go ahead and close this stale issue.
